/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* top =  1  *)
(* src = "dut.sv:1.1-6.10" *)
module dut(a, b);
  (* src = "dut.sv:2.8-2.9" *)
  input a;
  wire a;
  (* src = "dut.sv:3.15-3.16" *)
  output [3:0] b;
  wire [3:0] b;
  assign b = { a, a, a, a };
endmodule
