/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* keep =  1  *)
(* top =  1  *)
(* src = "dut.sv:6.1-16.10" *)
module top();
  (* src = "dut.sv:11.7-11.8" *)
  wire [47:0] s;
  (* keep = 32'd1 *)
  (* src = "dut.sv:15.17-15.39" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967295),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _0_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  assign s = 48'h000000000000;
endmodule
