/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* top =  1  *)
(* src = "dut.sv:326.1-328.10" *)
module abc9_test037(o);
  (* src = "dut.sv:326.28-326.29" *)
  output o;
  wire o;
  (* module_not_derived = 32'd1 *)
  (* src = "dut.sv:327.7-327.44" *)
  MUXF7 m (
    .I0(1'h1),
    .I1(1'h0),
    .O(o),
    .S(o)
  );
endmodule
