/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* interfaces_replaced_in_module =  1  *)
(* src = "dut.sv:59.1-92.10" *)
module \SubModule1$interfaces$$paramod\MyInterface\WIDTH=s32'00000000000000000000000000000100 (clk, rst, sig, outOther, \u_MyInterface.mysig_out , \u_MyInterface.setting , \u_MyInterface.passThrough , \u_MyInterface.other_setting );
  (* src = "dut.sv:60.17-60.20" *)
  input clk;
  wire clk;
  (* src = "dut.sv:61.17-61.20" *)
  input rst;
  wire rst;
  (* src = "dut.sv:63.23-63.26" *)
  input [1:0] sig;
  wire [1:0] sig;
  (* src = "dut.sv:64.25-64.33" *)
  output [21:0] outOther;
  wire [21:0] outOther;
  (* src = "dut.sv:59.1-92.10" *)
  output [1:0] \u_MyInterface.mysig_out ;
  wire [1:0] \u_MyInterface.mysig_out ;
  (* src = "dut.sv:59.1-92.10" *)
  input [0:0] \u_MyInterface.setting ;
  wire [0:0] \u_MyInterface.setting ;
  (* src = "dut.sv:59.1-92.10" *)
  output [15:0] \u_MyInterface.passThrough ;
  wire [15:0] \u_MyInterface.passThrough ;
  (* src = "dut.sv:59.1-92.10" *)
  output [3:0] \u_MyInterface.other_setting ;
  wire [3:0] \u_MyInterface.other_setting ;
  (* src = "dut.sv:68.3-76.8" *)
  wire [1:0] _0_;
  (* src = "dut.sv:59.1-92.10" *)
  wire [1:0] \MyInterfaceInstanceInSub.mysig_out ;
  (* src = "dut.sv:59.1-92.10" *)
  wire [21:0] \MyInterfaceInstanceInSub.other_setting ;
  (* src = "dut.sv:59.1-92.10" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] \MyInterfaceInstanceInSub.passThrough ;
  (* src = "dut.sv:59.1-92.10" *)
  wire [0:0] \MyInterfaceInstanceInSub.setting ;
  \$_XNOR_  _1_ (
    .A(sig[0]),
    .B(\u_MyInterface.setting ),
    .Y(_0_[0])
  );
  \$_XNOR_  _2_ (
    .A(\u_MyInterface.setting ),
    .B(sig[1]),
    .Y(_0_[1])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.3-76.8" *)
  \$_DFF_PP0_  \u_MyInterface.mysig_out_reg[0]  /* _3_ */ (
    .C(clk),
    .D(_0_[0]),
    .Q(\u_MyInterface.mysig_out [0]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.3-76.8" *)
  \$_DFF_PP0_  \u_MyInterface.mysig_out_reg[1]  /* _4_ */ (
    .C(clk),
    .D(_0_[1]),
    .Q(\u_MyInterface.mysig_out [1]),
    .R(rst)
  );
  (* src = "dut.sv:80.14-85.4" *)
  \SubModule2$interfaces$$paramod\MyInterface\WIDTH=s32'00000000000000000000000000000100$paramod\MyInterface\WIDTH=s32'00000000000000000000000000010110  u_SubModule2 (
    .clk(clk),
    .rst(rst),
    .\u_MyInterfaceInSub2.mysig_out (\u_MyInterface.mysig_out ),
    .\u_MyInterfaceInSub2.other_setting (\u_MyInterface.other_setting ),
    .\u_MyInterfaceInSub2.passThrough (\u_MyInterface.passThrough ),
    .\u_MyInterfaceInSub2.setting (\u_MyInterface.setting ),
    .\u_MyInterfaceInSub3.mysig_out (sig),
    .\u_MyInterfaceInSub3.other_setting (\MyInterfaceInstanceInSub.other_setting ),
    .\u_MyInterfaceInSub3.passThrough (\MyInterfaceInstanceInSub.passThrough ),
    .\u_MyInterfaceInSub3.setting (1'h0)
  );
  assign \MyInterfaceInstanceInSub.setting  = 1'h0;
  assign \MyInterfaceInstanceInSub.mysig_out  = sig;
  assign outOther = \MyInterfaceInstanceInSub.other_setting ;
endmodule

(* interfaces_replaced_in_module =  1  *)
(* src = "dut.sv:94.1-117.10" *)
module \SubModule2$interfaces$$paramod\MyInterface\WIDTH=s32'00000000000000000000000000000100$paramod\MyInterface\WIDTH=s32'00000000000000000000000000010110 (clk, rst, \u_MyInterfaceInSub3.other_setting , \u_MyInterfaceInSub3.mysig_out , \u_MyInterfaceInSub2.passThrough , \u_MyInterfaceInSub2.mysig_out , \u_MyInterfaceInSub2.other_setting , \u_MyInterfaceInSub2.setting , \u_MyInterfaceInSub3.passThrough , \u_MyInterfaceInSub3.setting );
  (* src = "dut.sv:96.17-96.20" *)
  input clk;
  wire clk;
  (* src = "dut.sv:97.17-97.20" *)
  input rst;
  wire rst;
  (* src = "dut.sv:94.1-117.10" *)
  output [21:0] \u_MyInterfaceInSub3.other_setting ;
  wire [21:0] \u_MyInterfaceInSub3.other_setting ;
  (* src = "dut.sv:94.1-117.10" *)
  input [1:0] \u_MyInterfaceInSub3.mysig_out ;
  wire [1:0] \u_MyInterfaceInSub3.mysig_out ;
  (* src = "dut.sv:94.1-117.10" *)
  output [15:0] \u_MyInterfaceInSub2.passThrough ;
  wire [15:0] \u_MyInterfaceInSub2.passThrough ;
  (* src = "dut.sv:94.1-117.10" *)
  input [1:0] \u_MyInterfaceInSub2.mysig_out ;
  wire [1:0] \u_MyInterfaceInSub2.mysig_out ;
  (* src = "dut.sv:94.1-117.10" *)
  output [3:0] \u_MyInterfaceInSub2.other_setting ;
  wire [3:0] \u_MyInterfaceInSub2.other_setting ;
  (* src = "dut.sv:94.1-117.10" *)
  input [0:0] \u_MyInterfaceInSub2.setting ;
  wire [0:0] \u_MyInterfaceInSub2.setting ;
  (* src = "dut.sv:94.1-117.10" *)
  output [15:0] \u_MyInterfaceInSub3.passThrough ;
  wire [15:0] \u_MyInterfaceInSub3.passThrough ;
  (* src = "dut.sv:94.1-117.10" *)
  input [0:0] \u_MyInterfaceInSub3.setting ;
  wire [0:0] \u_MyInterfaceInSub3.setting ;
  \$_NOT_  _0_ (
    .A(\u_MyInterfaceInSub3.mysig_out [0]),
    .Y(\u_MyInterfaceInSub3.other_setting [3])
  );
  \$_NOT_  _1_ (
    .A(\u_MyInterfaceInSub3.mysig_out [1]),
    .Y(\u_MyInterfaceInSub3.other_setting [6])
  );
  \$_ORNOT_  _2_ (
    .A(\u_MyInterfaceInSub3.mysig_out [1]),
    .B(\u_MyInterfaceInSub3.mysig_out [0]),
    .Y(\u_MyInterfaceInSub3.other_setting [5])
  );
  \$_XOR_  _3_ (
    .A(\u_MyInterfaceInSub3.mysig_out [0]),
    .B(\u_MyInterfaceInSub3.mysig_out [1]),
    .Y(\u_MyInterfaceInSub3.other_setting [4])
  );
  assign { \u_MyInterfaceInSub3.other_setting [21:7], \u_MyInterfaceInSub3.other_setting [2:0] } = { 10'h000, \u_MyInterfaceInSub3.mysig_out , 6'h38 };
  assign \u_MyInterfaceInSub3.passThrough  = 16'hxxxx;
  assign \u_MyInterfaceInSub2.other_setting  = 4'hx;
  assign \u_MyInterfaceInSub2.passThrough  = 16'hc87c;
endmodule

(* top =  1  *)
(* interfaces_replaced_in_module =  1  *)
(* src = "dut.sv:3.1-29.10" *)
module TopModule(clk, rst, outOther, sig, flip, sig_out, passThrough);
  (* src = "dut.sv:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "dut.sv:5.17-5.20" *)
  input rst;
  wire rst;
  (* src = "dut.sv:6.25-6.33" *)
  output [21:0] outOther;
  wire [21:0] outOther;
  (* src = "dut.sv:7.23-7.26" *)
  input [1:0] sig;
  wire [1:0] sig;
  (* src = "dut.sv:8.17-8.21" *)
  input flip;
  wire flip;
  (* src = "dut.sv:9.24-9.31" *)
  output [1:0] sig_out;
  wire [1:0] sig_out;
  (* src = "dut.sv:10.25-10.36" *)
  output [15:0] passThrough;
  wire [15:0] passThrough;
  (* src = "dut.sv:3.1-29.10" *)
  wire [1:0] \MyInterfaceInstance.mysig_out ;
  (* src = "dut.sv:3.1-29.10" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] \MyInterfaceInstance.other_setting ;
  (* src = "dut.sv:3.1-29.10" *)
  wire [15:0] \MyInterfaceInstance.passThrough ;
  (* src = "dut.sv:3.1-29.10" *)
  wire [0:0] \MyInterfaceInstance.setting ;
  (* src = "dut.sv:14.14-20.4" *)
  \SubModule1$interfaces$$paramod\MyInterface\WIDTH=s32'00000000000000000000000000000100  u_SubModule1 (
    .clk(clk),
    .outOther(outOther),
    .rst(rst),
    .sig(sig),
    .\u_MyInterface.mysig_out (\MyInterfaceInstance.mysig_out ),
    .\u_MyInterface.other_setting (\MyInterfaceInstance.other_setting ),
    .\u_MyInterface.passThrough (\MyInterfaceInstance.passThrough ),
    .\u_MyInterface.setting (flip)
  );
  assign \MyInterfaceInstance.setting  = flip;
  assign passThrough = \MyInterfaceInstance.passThrough ;
  assign sig_out = \MyInterfaceInstance.mysig_out ;
endmodule
