/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* top =  1  *)
(* src = "dut.sv:4.1-8.10" *)
module readmemh_rom(clk, adr, dat);
  (* src = "dut.sv:4.34-4.37" *)
  input clk;
  wire clk;
  (* src = "dut.sv:4.57-4.60" *)
  input [3:0] adr;
  wire [3:0] adr;
  (* src = "dut.sv:4.82-4.85" *)
  output [31:0] dat;
  wire [31:0] dat;
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22" *)
  wire [22:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  \$_NOT_  _11_ (
    .A(adr[0]),
    .Y(_05_)
  );
  \$_NOR_  _12_ (
    .A(adr[3]),
    .B(adr[2]),
    .Y(_06_)
  );
  \$_NOT_  _13_ (
    .A(_06_),
    .Y(_01_)
  );
  \$_NOR_  _14_ (
    .A(adr[1]),
    .B(_06_),
    .Y(_00_[1])
  );
  \$_NAND_  _15_ (
    .A(adr[0]),
    .B(adr[1]),
    .Y(_04_)
  );
  \$_XNOR_  _16_ (
    .A(adr[0]),
    .B(adr[1]),
    .Y(_07_)
  );
  \$_NOT_  _17_ (
    .A(_07_),
    .Y(_03_)
  );
  \$_MUX_  _18_ (
    .A(adr[0]),
    .B(_07_),
    .S(_06_),
    .Y(_00_[0])
  );
  \$_NAND_  _19_ (
    .A(adr[1]),
    .B(_06_),
    .Y(_02_)
  );
  \$_OR_  _20_ (
    .A(adr[2]),
    .B(adr[1]),
    .Y(_08_)
  );
  \$_XNOR_  _21_ (
    .A(adr[3]),
    .B(_08_),
    .Y(_00_[3])
  );
  \$_XNOR_  _22_ (
    .A(adr[2]),
    .B(adr[1]),
    .Y(_09_)
  );
  \$_NAND_  _23_ (
    .A(adr[0]),
    .B(_06_),
    .Y(_10_)
  );
  \$_AND_  _24_ (
    .A(_09_),
    .B(_10_),
    .Y(_00_[2])
  );
  \$_DFF_P_  \dat_reg[0]  /* _25_ */ (
    .C(clk),
    .D(_00_[0]),
    .Q(dat[0])
  );
  \$_DFF_P_  \dat_reg[1]  /* _26_ */ (
    .C(clk),
    .D(_00_[1]),
    .Q(dat[1])
  );
  \$_DFF_P_  \dat_reg[2]  /* _27_ */ (
    .C(clk),
    .D(_00_[2]),
    .Q(dat[2])
  );
  \$_DFF_P_  \dat_reg[3]  /* _28_ */ (
    .C(clk),
    .D(_00_[3]),
    .Q(dat[3])
  );
  \$_SDFF_PP0_  \dat_reg[14]  /* _29_ */ (
    .C(clk),
    .D(_04_),
    .Q(dat[14]),
    .R(_01_)
  );
  \$_SDFF_PP0_  \dat_reg[15]  /* _30_ */ (
    .C(clk),
    .D(_05_),
    .Q(dat[15]),
    .R(_01_)
  );
  \$_SDFF_PP0_  \dat_reg[23]  /* _31_ */ (
    .C(clk),
    .D(_05_),
    .Q(dat[23]),
    .R(_02_)
  );
  \$_SDFF_PP0_  \dat_reg[21]  /* _32_ */ (
    .C(clk),
    .D(_03_),
    .Q(dat[21]),
    .R(_01_)
  );
  assign { _00_[22:16], _00_[14:8], _00_[6] } = { _00_[15], _00_[4], _00_[15], _00_[4], _00_[15], _00_[4], _00_[4], _00_[4], _00_[7], _00_[5], _00_[5], _00_[7], _00_[5], _00_[5:4] };
  assign { dat[31:24], dat[22], dat[20:16], dat[13:4] } = { dat[23], 2'h0, dat[21], dat[23], 1'h0, dat[21], 2'h0, dat[21], dat[23], dat[21], 3'h0, dat[14], dat[15:14], dat[14], 1'h0, dat[15], dat[21], dat[14], dat[21] };
endmodule
