/* Generated by Yosys 0.68+1 (git sha1 bbc149ed5, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:31.1-61.10" *)
(* top =  1  *)
module array_default_struct_pattern(v, idx, o_plain, o_written, o_zero, o_dyn, o_bitwise);
  (* src = "dut.sv:32.23-32.24" *)
  input [1:0] v;
  wire [1:0] v;
  (* src = "dut.sv:33.23-33.26" *)
  input [1:0] idx;
  wire [1:0] idx;
  (* src = "dut.sv:34.23-34.30" *)
  output [9:0] o_plain;
  wire [9:0] o_plain;
  (* src = "dut.sv:35.23-35.32" *)
  output [9:0] o_written;
  wire [9:0] o_written;
  (* src = "dut.sv:36.23-36.29" *)
  output [9:0] o_zero;
  wire [9:0] o_zero;
  (* src = "dut.sv:37.23-37.28" *)
  output [4:0] o_dyn;
  wire [4:0] o_dyn;
  (* src = "dut.sv:38.23-38.32" *)
  output [3:0] o_bitwise;
  wire [3:0] o_bitwise;
  (* src = "dut.sv:43.15-43.19" *)
  wire [3:0] bits;
  (* src = "dut.sv:40.8-40.11" *)
  wire [9:0] vec;
  (* src = "dut.sv:40.8-40.11" *)
  wire [4:0] \vec[0] ;
  (* src = "dut.sv:40.8-40.11" *)
  wire [4:0] \vec[1] ;
  (* src = "dut.sv:41.8-41.12" *)
  wire [9:0] vecw;
  (* src = "dut.sv:41.8-41.12" *)
  wire [4:0] \vecw[0] ;
  (* src = "dut.sv:41.8-41.12" *)
  wire [4:0] \vecw[1] ;
  (* src = "dut.sv:42.8-42.12" *)
  wire [9:0] vecz;
  (* src = "dut.sv:42.8-42.12" *)
  wire [4:0] \vecz[0] ;
  (* src = "dut.sv:42.8-42.12" *)
  wire [4:0] \vecz[1] ;
  assign \vecz[1]  = 5'h00;
  assign \vecz[0]  = 5'h00;
  assign vecz = 10'h000;
  assign \vecw[1]  = { v, 3'h5 };
  assign \vecw[0]  = { v, 3'h5 };
  assign vecw = { v, 3'h5, v, 3'h5 };
  assign \vec[1]  = 5'h15;
  assign \vec[0]  = 5'h15;
  assign vec = 10'h2b5;
  assign bits = 4'hf;
  assign o_bitwise = 4'hf;
  assign o_dyn = 5'h15;
  assign o_zero = 10'h000;
  assign o_written = { v, 3'h5, v, 3'h5 };
  assign o_plain = 10'h2b5;
endmodule
