// aes_control with its default SecMasking=0 (key_init_qe_i / key_init_we_o are [NumSharesKey]=2 arrays).
// Multi-element unpacked-array ports flattened elem0@LSB (read_uhdm and read_slang
// flatten unpacked ports in opposite element order, so the miter/co-sim compare
// through this wrapper — same convention as the KMAC/EDN masked wrappers).
module aes_control_flat import aes_pkg::*; import aes_reg_pkg::*; (
  input  logic clk_i,
  input  logic rst_ni,
  input  logic ctrl_qe_i,
  output logic ctrl_we_o,
  input  logic ctrl_phase_i,
  input  logic ctrl_err_storage_i,
  input  aes_op_e op_i,
  input  aes_mode_e mode_i,
  input  ciph_op_e cipher_op_i,
  input  logic sideload_i,
  input  prs_rate_e prng_reseed_rate_i,
  input  logic manual_operation_i,
  input  logic key_touch_forces_reseed_i,
  input  logic start_i,
  input  logic key_iv_data_in_clear_i,
  input  logic data_out_clear_i,
  input  logic prng_reseed_i,
  input  logic mux_sel_err_i,
  input  logic sp_enc_err_i,
  input  lc_ctrl_pkg::lc_tx_t lc_escalate_en_i,
  input  logic alert_fatal_i,
  output logic alert_o,
  input  logic key_sideload_valid_i,
  input  logic [15:0] key_init_qe_i_flat,
  input  logic      [NumRegsIv-1:0] iv_qe_i,
  input  logic    [NumRegsData-1:0] data_in_qe_i,
  input  logic    [NumRegsData-1:0] data_out_re_i,
  output logic data_in_we_o,
  output sp2v_e data_out_we_o,
  output dip_sel_e data_in_prev_sel_o,
  output sp2v_e data_in_prev_we_o,
  output si_sel_e state_in_sel_o,
  output add_si_sel_e add_state_in_sel_o,
  output add_so_sel_e add_state_out_sel_o,
  output sp2v_e ctr_incr_o,
  input  sp2v_e ctr_ready_i,
  input  sp2v_e  [NumSlicesCtr-1:0] ctr_we_i,
  output sp2v_e cipher_in_valid_o,
  input  sp2v_e cipher_in_ready_i,
  input  sp2v_e cipher_out_valid_i,
  output sp2v_e cipher_out_ready_o,
  output sp2v_e cipher_crypt_o,
  input  sp2v_e cipher_crypt_i,
  output sp2v_e cipher_dec_key_gen_o,
  input  sp2v_e cipher_dec_key_gen_i,
  output logic cipher_prng_reseed_o,
  input  logic cipher_prng_reseed_i,
  output logic cipher_key_clear_o,
  input  logic cipher_key_clear_i,
  output logic cipher_data_out_clear_o,
  input  logic cipher_data_out_clear_i,
  output key_init_sel_e key_init_sel_o,
  output logic [47:0] key_init_we_o_flat,
  output iv_sel_e iv_sel_o,
  output sp2v_e  [NumSlicesCtr-1:0] iv_we_o,
  output logic prng_data_req_o,
  input  logic prng_data_ack_i,
  output logic prng_reseed_req_o,
  input  logic prng_reseed_ack_i,
  output logic start_o,
  output logic start_we_o,
  output logic key_iv_data_in_clear_o,
  output logic key_iv_data_in_clear_we_o,
  output logic data_out_clear_o,
  output logic data_out_clear_we_o,
  output logic prng_reseed_o,
  output logic prng_reseed_we_o,
  output logic idle_o,
  output logic idle_we_o,
  output logic stall_o,
  output logic stall_we_o,
  input  logic output_lost_i,
  output logic output_lost_o,
  output logic output_lost_we_o,
  output logic output_valid_o,
  output logic output_valid_we_o,
  output logic input_ready_o,
  output logic input_ready_we_o
);
  logic [7:0] key_init_qe_i [2];
  assign key_init_qe_i[0] = key_init_qe_i_flat[7:0];
  assign key_init_qe_i[1] = key_init_qe_i_flat[15:8];
  logic [23:0] key_init_we_o [2];
  assign key_init_we_o_flat[23:0] = key_init_we_o[0];
  assign key_init_we_o_flat[47:24] = key_init_we_o[1];
  aes_control u (
    .clk_i, .rst_ni, .ctrl_qe_i, .ctrl_we_o, .ctrl_phase_i, .ctrl_err_storage_i, .op_i, .mode_i, .cipher_op_i, .sideload_i, .prng_reseed_rate_i, .manual_operation_i, .key_touch_forces_reseed_i, .start_i, .key_iv_data_in_clear_i, .data_out_clear_i, .prng_reseed_i, .mux_sel_err_i, .sp_enc_err_i, .lc_escalate_en_i, .alert_fatal_i, .alert_o, .key_sideload_valid_i, .key_init_qe_i(key_init_qe_i), .iv_qe_i, .data_in_qe_i, .data_out_re_i, .data_in_we_o, .data_out_we_o, .data_in_prev_sel_o, .data_in_prev_we_o, .state_in_sel_o, .add_state_in_sel_o, .add_state_out_sel_o, .ctr_incr_o, .ctr_ready_i, .ctr_we_i, .cipher_in_valid_o, .cipher_in_ready_i, .cipher_out_valid_i, .cipher_out_ready_o, .cipher_crypt_o, .cipher_crypt_i, .cipher_dec_key_gen_o, .cipher_dec_key_gen_i, .cipher_prng_reseed_o, .cipher_prng_reseed_i, .cipher_key_clear_o, .cipher_key_clear_i, .cipher_data_out_clear_o, .cipher_data_out_clear_i, .key_init_sel_o, .key_init_we_o(key_init_we_o), .iv_sel_o, .iv_we_o, .prng_data_req_o, .prng_data_ack_i, .prng_reseed_req_o, .prng_reseed_ack_i, .start_o, .start_we_o, .key_iv_data_in_clear_o, .key_iv_data_in_clear_we_o, .data_out_clear_o, .data_out_clear_we_o, .prng_reseed_o, .prng_reseed_we_o, .idle_o, .idle_we_o, .stall_o, .stall_we_o, .output_lost_i, .output_lost_o, .output_lost_we_o, .output_valid_o, .output_valid_we_o, .input_ready_o, .input_ready_we_o
  );
endmodule
