// aes_control_fsm with SecMasking=1 (what aes_wrap / aes_core default to; the
// manifest's aes_control_fsm row is the SecMasking=0 default).  Wrapper-only
// top: aes_srcs.py seeds the closure from this file's references.
module aes_control_fsm_m_flat import aes_pkg::*; import aes_reg_pkg::*; (
  input  logic clk_i,
  input  logic rst_ni,
  input  logic ctrl_qe_i,
  output logic ctrl_we_o,
  input  logic ctrl_phase_i,
  input  logic ctrl_err_storage_i,
  input  aes_op_e op_i,
  input  aes_mode_e mode_i,
  input  ciph_op_e cipher_op_i,
  input  logic sideload_i,
  input  prs_rate_e prng_reseed_rate_i,
  input  logic manual_operation_i,
  input  logic key_touch_forces_reseed_i,
  input  logic start_i,
  input  logic key_iv_data_in_clear_i,
  input  logic data_out_clear_i,
  input  logic prng_reseed_i,
  input  logic mux_sel_err_i,
  input  logic sp_enc_err_i,
  input  lc_ctrl_pkg::lc_tx_t lc_escalate_en_i,
  input  logic alert_fatal_i,
  output logic alert_o,
  input  logic key_sideload_valid_i,
  input  logic [NumSharesKey-1:0][NumRegsKey-1:0] key_init_qe_i,
  input  logic                    [NumRegsIv-1:0] iv_qe_i,
  input  logic                  [NumRegsData-1:0] data_in_qe_i,
  input  logic                  [NumRegsData-1:0] data_out_re_i,
  output logic data_in_we_o,
  output logic data_out_we_o,
  output dip_sel_e data_in_prev_sel_o,
  output logic data_in_prev_we_o,
  output si_sel_e state_in_sel_o,
  output add_si_sel_e add_state_in_sel_o,
  output add_so_sel_e add_state_out_sel_o,
  output logic ctr_incr_o,
  input  logic ctr_ready_i,
  input  logic                 [NumSlicesCtr-1:0] ctr_we_i,
  output logic cipher_in_valid_o,
  input  logic cipher_in_ready_i,
  input  logic cipher_out_valid_i,
  output logic cipher_out_ready_o,
  output logic cipher_crypt_o,
  input  logic cipher_crypt_i,
  output logic cipher_dec_key_gen_o,
  input  logic cipher_dec_key_gen_i,
  output logic cipher_prng_reseed_o,
  input  logic cipher_prng_reseed_i,
  output logic cipher_key_clear_o,
  input  logic cipher_key_clear_i,
  output logic cipher_data_out_clear_o,
  input  logic cipher_data_out_clear_i,
  output key_init_sel_e key_init_sel_o,
  output logic [NumSharesKey-1:0][NumRegsKey-1:0] key_init_we_o,
  output iv_sel_e iv_sel_o,
  output logic                 [NumSlicesCtr-1:0] iv_we_o,
  output logic prng_data_req_o,
  input  logic prng_data_ack_i,
  output logic prng_reseed_req_o,
  input  logic prng_reseed_ack_i,
  output logic start_we_o,
  output logic key_iv_data_in_clear_we_o,
  output logic data_out_clear_we_o,
  output logic prng_reseed_o,
  output logic prng_reseed_we_o,
  output logic idle_o,
  output logic idle_we_o,
  output logic stall_o,
  output logic stall_we_o,
  input  logic output_lost_i,
  output logic output_lost_o,
  output logic output_lost_we_o,
  output logic output_valid_o,
  output logic output_valid_we_o,
  output logic input_ready_o,
  output logic input_ready_we_o
);
  aes_control_fsm #(.SecMasking(1'b1)) u (
    .clk_i, .rst_ni, .ctrl_qe_i, .ctrl_we_o, .ctrl_phase_i, .ctrl_err_storage_i, .op_i, .mode_i, .cipher_op_i, .sideload_i, .prng_reseed_rate_i, .manual_operation_i, .key_touch_forces_reseed_i, .start_i, .key_iv_data_in_clear_i, .data_out_clear_i, .prng_reseed_i, .mux_sel_err_i, .sp_enc_err_i, .lc_escalate_en_i, .alert_fatal_i, .alert_o, .key_sideload_valid_i, .key_init_qe_i, .iv_qe_i, .data_in_qe_i, .data_out_re_i, .data_in_we_o, .data_out_we_o, .data_in_prev_sel_o, .data_in_prev_we_o, .state_in_sel_o, .add_state_in_sel_o, .add_state_out_sel_o, .ctr_incr_o, .ctr_ready_i, .ctr_we_i, .cipher_in_valid_o, .cipher_in_ready_i, .cipher_out_valid_i, .cipher_out_ready_o, .cipher_crypt_o, .cipher_crypt_i, .cipher_dec_key_gen_o, .cipher_dec_key_gen_i, .cipher_prng_reseed_o, .cipher_prng_reseed_i, .cipher_key_clear_o, .cipher_key_clear_i, .cipher_data_out_clear_o, .cipher_data_out_clear_i, .key_init_sel_o, .key_init_we_o, .iv_sel_o, .iv_we_o, .prng_data_req_o, .prng_data_ack_i, .prng_reseed_req_o, .prng_reseed_ack_i, .start_we_o, .key_iv_data_in_clear_we_o, .data_out_clear_we_o, .prng_reseed_o, .prng_reseed_we_o, .idle_o, .idle_we_o, .stall_o, .stall_we_o, .output_lost_i, .output_lost_o, .output_lost_we_o, .output_valid_o, .output_valid_we_o, .input_ready_o, .input_ready_we_o
  );
endmodule
