/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* keep =  1  *)
(* dynports =  1  *)
(* src = "dut.sv:1.1-14.10" *)
(* top =  1  *)
module top(o);
  (* src = "dut.sv:1.25-1.26" *)
  output o;
  wire o;
  (* keep = 32'd1 *)
  (* src = "dut.sv:12.7-12.22" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967295),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _0_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  assign o = 1'h1;
endmodule
