/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:26.1-28.10" *)
module DUT(\intf.observe , \intf.drive );
  (* src = "dut.sv:15.9-15.16" *)
  output \intf.observe ;
  wire \intf.observe ;
  (* src = "dut.sv:14.9-14.14" *)
  input \intf.drive ;
  wire \intf.drive ;
  assign \intf.observe  = 1'hx;
endmodule

(* src = "dut.sv:34.1-40.10" *)
(* top =  1  *)
module top(a, b);
  (* src = "dut.sv:34.23-34.24" *)
  input a;
  wire a;
  (* src = "dut.sv:34.37-34.38" *)
  output b;
  wire b;
  (* src = "dut.sv:14.9-14.14" *)
  wire \conntb.drive ;
  (* src = "dut.sv:15.9-15.16" *)
  wire \conntb.observe ;
  DUT dut (
    .\intf.drive (a),
    .\intf.observe (\conntb.observe )
  );
  assign \conntb.drive  = a;
  assign b = \conntb.observe ;
endmodule
