/* Generated by Yosys 0.56+171 (git sha1 6fdcdd41d, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* src = "dut.sv:2.1-32.10" *)
(* top =  1  *)
module simple_function(clk, rst, a, b, c, q);
  (* src = "dut.sv:3.18-3.21" *)
  input clk;
  wire clk;
  (* src = "dut.sv:4.18-4.21" *)
  input rst;
  wire rst;
  (* src = "dut.sv:5.18-5.19" *)
  input a;
  wire a;
  (* src = "dut.sv:6.18-6.19" *)
  input b;
  wire b;
  (* src = "dut.sv:7.18-7.19" *)
  input c;
  wire c;
  (* src = "dut.sv:8.18-8.19" *)
  output q;
  wire q;
  wire _0_;
  wire \and_or_tree$func$dut.sv:22$1.$result ;
  (* src = "dut.sv:21.11-21.12" *)
  wire d;
  \$_AND_  _1_ (
    .A(b),
    .B(a),
    .Y(_0_)
  );
  \$_OR_  _2_ (
    .A(_0_),
    .B(c),
    .Y(\and_or_tree$func$dut.sv:22$1.$result )
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.5-30.8" *)
  \$_SDFF_PP0_  q_reg /* _3_ */ (
    .C(clk),
    .D(\and_or_tree$func$dut.sv:22$1.$result ),
    .Q(q),
    .R(rst)
  );
  assign d = \and_or_tree$func$dut.sv:22$1.$result ;
endmodule
