/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* top =  1  *)
(* src = "dut.sv:3.1-10.10" *)
module top(a, b, c, d, o_and, o_or, o_nand, o_nor, o_xor, o_xnor);
  (* src = "dut.sv:3.18-3.19" *)
  input a;
  wire a;
  (* src = "dut.sv:3.21-3.22" *)
  input b;
  wire b;
  (* src = "dut.sv:3.24-3.25" *)
  input c;
  wire c;
  (* src = "dut.sv:3.27-3.28" *)
  input d;
  wire d;
  (* src = "dut.sv:3.37-3.42" *)
  output o_and;
  wire o_and;
  (* src = "dut.sv:3.44-3.48" *)
  output o_or;
  wire o_or;
  (* src = "dut.sv:3.50-3.56" *)
  output o_nand;
  wire o_nand;
  (* src = "dut.sv:3.58-3.63" *)
  output o_nor;
  wire o_nor;
  (* src = "dut.sv:3.65-3.70" *)
  output o_xor;
  wire o_xor;
  (* src = "dut.sv:3.72-3.78" *)
  output o_xnor;
  wire o_xnor;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  \$_AND_  _06_ (
    .A(a),
    .B(b),
    .Y(_00_)
  );
  \$_AND_  _07_ (
    .A(c),
    .B(d),
    .Y(_01_)
  );
  \$_AND_  _08_ (
    .A(_00_),
    .B(_01_),
    .Y(o_and)
  );
  \$_NAND_  _09_ (
    .A(_00_),
    .B(_01_),
    .Y(o_nand)
  );
  \$_NOR_  _10_ (
    .A(a),
    .B(b),
    .Y(_02_)
  );
  \$_XNOR_  _11_ (
    .A(a),
    .B(b),
    .Y(_03_)
  );
  \$_NOR_  _12_ (
    .A(c),
    .B(d),
    .Y(_04_)
  );
  \$_XOR_  _13_ (
    .A(c),
    .B(d),
    .Y(_05_)
  );
  \$_XOR_  _14_ (
    .A(_03_),
    .B(_05_),
    .Y(o_xnor)
  );
  \$_XNOR_  _15_ (
    .A(_03_),
    .B(_05_),
    .Y(o_xor)
  );
  \$_AND_  _16_ (
    .A(_02_),
    .B(_04_),
    .Y(o_nor)
  );
  \$_NAND_  _17_ (
    .A(_02_),
    .B(_04_),
    .Y(o_or)
  );
endmodule
