/* Generated by Yosys 0.62+39 (git sha1 131911291-dirty, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* src = "dut.sv:1.1-39.10" *)
(* top =  1  *)
module gen_test7();
  wire [2:0] \cond.sub_out1 ;
  wire [2:0] \cond.sub_out2 ;
  wire [2:0] \cond.sub_out3 ;
  wire \cond.x ;
  (* \reg  = 32'd1 *)
  (* src = "dut.sv:2.12-2.16" *)
  wire [2:0] out1;
  (* \reg  = 32'd1 *)
  (* src = "dut.sv:3.12-3.16" *)
  wire [2:0] out2;
  (* src = "dut.sv:4.13-4.17" *)
  wire [2:0] out3;
  assign \cond.x  = 1'h0;
  assign \cond.sub_out3  = 3'h7;
  assign \cond.sub_out2  = 3'h0;
  assign \cond.sub_out1  = 3'h4;
  assign out3 = 3'h7;
  assign out2 = 3'h0;
  assign out1 = 3'h4;
endmodule
