/* Generated by Yosys 0.68+1 (git sha1 bbc149ed5, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:1.1-16.10" *)
(* top =  1  *)
module arr_pattern_dir(a_i, sel_i, flat_o, flat2_o);
  (* src = "dut.sv:2.23-2.26" *)
  input [31:0] a_i;
  wire [31:0] a_i;
  (* src = "dut.sv:3.23-3.28" *)
  input sel_i;
  wire sel_i;
  (* src = "dut.sv:4.23-4.29" *)
  output [63:0] flat_o;
  wire [63:0] flat_o;
  (* src = "dut.sv:5.23-5.30" *)
  output [63:0] flat2_o;
  wire [63:0] flat2_o;
  (* src = "dut.sv:7.16-7.19" *)
  wire [63:0] arr;
  (* src = "dut.sv:8.16-8.20" *)
  wire [63:0] arr2;
  (* src = "dut.sv:8.16-8.20" *)
  wire [31:0] \arr2[0] ;
  (* src = "dut.sv:8.16-8.20" *)
  wire [31:0] \arr2[1] ;
  (* src = "dut.sv:7.16-7.19" *)
  wire [31:0] \arr[0] ;
  (* src = "dut.sv:7.16-7.19" *)
  wire [31:0] \arr[1] ;
  \$_ANDNOT_  _00_ (
    .A(a_i[30]),
    .B(sel_i),
    .Y(flat_o[62])
  );
  \$_ANDNOT_  _01_ (
    .A(a_i[29]),
    .B(sel_i),
    .Y(flat_o[61])
  );
  \$_ANDNOT_  _02_ (
    .A(a_i[28]),
    .B(sel_i),
    .Y(flat_o[60])
  );
  \$_ANDNOT_  _03_ (
    .A(a_i[27]),
    .B(sel_i),
    .Y(flat_o[59])
  );
  \$_ANDNOT_  _04_ (
    .A(a_i[26]),
    .B(sel_i),
    .Y(flat_o[58])
  );
  \$_ANDNOT_  _05_ (
    .A(a_i[25]),
    .B(sel_i),
    .Y(flat_o[57])
  );
  \$_ANDNOT_  _06_ (
    .A(a_i[24]),
    .B(sel_i),
    .Y(flat_o[56])
  );
  \$_ANDNOT_  _07_ (
    .A(a_i[23]),
    .B(sel_i),
    .Y(flat_o[55])
  );
  \$_ANDNOT_  _08_ (
    .A(a_i[22]),
    .B(sel_i),
    .Y(flat_o[54])
  );
  \$_ANDNOT_  _09_ (
    .A(a_i[21]),
    .B(sel_i),
    .Y(flat_o[53])
  );
  \$_ANDNOT_  _10_ (
    .A(a_i[20]),
    .B(sel_i),
    .Y(flat_o[52])
  );
  \$_ANDNOT_  _11_ (
    .A(a_i[19]),
    .B(sel_i),
    .Y(flat_o[51])
  );
  \$_ANDNOT_  _12_ (
    .A(a_i[18]),
    .B(sel_i),
    .Y(flat_o[50])
  );
  \$_ANDNOT_  _13_ (
    .A(a_i[17]),
    .B(sel_i),
    .Y(flat_o[49])
  );
  \$_ANDNOT_  _14_ (
    .A(a_i[16]),
    .B(sel_i),
    .Y(flat_o[48])
  );
  \$_ANDNOT_  _15_ (
    .A(a_i[15]),
    .B(sel_i),
    .Y(flat_o[47])
  );
  \$_ANDNOT_  _16_ (
    .A(a_i[14]),
    .B(sel_i),
    .Y(flat_o[46])
  );
  \$_ANDNOT_  _17_ (
    .A(a_i[13]),
    .B(sel_i),
    .Y(flat_o[45])
  );
  \$_ANDNOT_  _18_ (
    .A(a_i[12]),
    .B(sel_i),
    .Y(flat_o[44])
  );
  \$_ANDNOT_  _19_ (
    .A(a_i[11]),
    .B(sel_i),
    .Y(flat_o[43])
  );
  \$_ANDNOT_  _20_ (
    .A(a_i[10]),
    .B(sel_i),
    .Y(flat_o[42])
  );
  \$_ANDNOT_  _21_ (
    .A(a_i[9]),
    .B(sel_i),
    .Y(flat_o[41])
  );
  \$_ANDNOT_  _22_ (
    .A(a_i[8]),
    .B(sel_i),
    .Y(flat_o[40])
  );
  \$_ANDNOT_  _23_ (
    .A(a_i[7]),
    .B(sel_i),
    .Y(flat_o[39])
  );
  \$_ANDNOT_  _24_ (
    .A(a_i[6]),
    .B(sel_i),
    .Y(flat_o[38])
  );
  \$_ANDNOT_  _25_ (
    .A(a_i[5]),
    .B(sel_i),
    .Y(flat_o[37])
  );
  \$_ANDNOT_  _26_ (
    .A(a_i[4]),
    .B(sel_i),
    .Y(flat_o[36])
  );
  \$_ANDNOT_  _27_ (
    .A(a_i[3]),
    .B(sel_i),
    .Y(flat_o[35])
  );
  \$_ANDNOT_  _28_ (
    .A(a_i[2]),
    .B(sel_i),
    .Y(flat_o[34])
  );
  \$_ANDNOT_  _29_ (
    .A(a_i[1]),
    .B(sel_i),
    .Y(flat_o[33])
  );
  \$_ANDNOT_  _30_ (
    .A(a_i[0]),
    .B(sel_i),
    .Y(flat_o[32])
  );
  \$_ORNOT_  _31_ (
    .A(a_i[31]),
    .B(sel_i),
    .Y(flat_o[31])
  );
  \$_ORNOT_  _32_ (
    .A(a_i[30]),
    .B(sel_i),
    .Y(flat_o[30])
  );
  \$_AND_  _33_ (
    .A(sel_i),
    .B(a_i[29]),
    .Y(flat_o[29])
  );
  \$_ORNOT_  _34_ (
    .A(a_i[28]),
    .B(sel_i),
    .Y(flat_o[28])
  );
  \$_ORNOT_  _35_ (
    .A(a_i[27]),
    .B(sel_i),
    .Y(flat_o[27])
  );
  \$_ORNOT_  _36_ (
    .A(a_i[26]),
    .B(sel_i),
    .Y(flat_o[26])
  );
  \$_ORNOT_  _37_ (
    .A(a_i[25]),
    .B(sel_i),
    .Y(flat_o[25])
  );
  \$_AND_  _38_ (
    .A(sel_i),
    .B(a_i[24]),
    .Y(flat_o[24])
  );
  \$_ORNOT_  _39_ (
    .A(a_i[23]),
    .B(sel_i),
    .Y(flat_o[23])
  );
  \$_AND_  _40_ (
    .A(sel_i),
    .B(a_i[22]),
    .Y(flat_o[22])
  );
  \$_ORNOT_  _41_ (
    .A(a_i[21]),
    .B(sel_i),
    .Y(flat_o[21])
  );
  \$_AND_  _42_ (
    .A(sel_i),
    .B(a_i[20]),
    .Y(flat_o[20])
  );
  \$_ORNOT_  _43_ (
    .A(a_i[19]),
    .B(sel_i),
    .Y(flat_o[19])
  );
  \$_ORNOT_  _44_ (
    .A(a_i[18]),
    .B(sel_i),
    .Y(flat_o[18])
  );
  \$_AND_  _45_ (
    .A(sel_i),
    .B(a_i[17]),
    .Y(flat_o[17])
  );
  \$_ORNOT_  _46_ (
    .A(a_i[16]),
    .B(sel_i),
    .Y(flat_o[16])
  );
  \$_ORNOT_  _47_ (
    .A(a_i[15]),
    .B(sel_i),
    .Y(flat_o[15])
  );
  \$_AND_  _48_ (
    .A(sel_i),
    .B(a_i[14]),
    .Y(flat_o[14])
  );
  \$_ORNOT_  _49_ (
    .A(a_i[13]),
    .B(sel_i),
    .Y(flat_o[13])
  );
  \$_ORNOT_  _50_ (
    .A(a_i[12]),
    .B(sel_i),
    .Y(flat_o[12])
  );
  \$_ORNOT_  _51_ (
    .A(a_i[11]),
    .B(sel_i),
    .Y(flat_o[11])
  );
  \$_ORNOT_  _52_ (
    .A(a_i[10]),
    .B(sel_i),
    .Y(flat_o[10])
  );
  \$_ORNOT_  _53_ (
    .A(a_i[9]),
    .B(sel_i),
    .Y(flat_o[9])
  );
  \$_AND_  _54_ (
    .A(sel_i),
    .B(a_i[8]),
    .Y(flat_o[8])
  );
  \$_ORNOT_  _55_ (
    .A(a_i[7]),
    .B(sel_i),
    .Y(flat_o[7])
  );
  \$_ORNOT_  _56_ (
    .A(a_i[6]),
    .B(sel_i),
    .Y(flat_o[6])
  );
  \$_ORNOT_  _57_ (
    .A(a_i[5]),
    .B(sel_i),
    .Y(flat_o[5])
  );
  \$_AND_  _58_ (
    .A(sel_i),
    .B(a_i[4]),
    .Y(flat_o[4])
  );
  \$_ORNOT_  _59_ (
    .A(a_i[3]),
    .B(sel_i),
    .Y(flat_o[3])
  );
  \$_ORNOT_  _60_ (
    .A(a_i[2]),
    .B(sel_i),
    .Y(flat_o[2])
  );
  \$_ORNOT_  _61_ (
    .A(a_i[1]),
    .B(sel_i),
    .Y(flat_o[1])
  );
  \$_ORNOT_  _62_ (
    .A(a_i[0]),
    .B(sel_i),
    .Y(flat_o[0])
  );
  \$_ANDNOT_  _63_ (
    .A(a_i[31]),
    .B(sel_i),
    .Y(flat_o[63])
  );
  assign \arr2[1]  = 32'd1;
  assign \arr2[0]  = a_i;
  assign arr2 = { 32'h00000001, a_i };
  assign \arr[1]  = flat_o[63:32];
  assign \arr[0]  = flat_o[31:0];
  assign arr = flat_o;
  assign flat2_o = { 32'h00000001, a_i };
endmodule
