/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* top =  1  *)
(* src = "dut.sv:2.1-14.10" *)
module dut(d, rstn, clk, q);
  (* src = "dut.sv:2.20-2.21" *)
  input d;
  wire d;
  (* src = "dut.sv:3.21-3.25" *)
  input rstn;
  wire rstn;
  (* src = "dut.sv:4.21-4.24" *)
  input clk;
  wire clk;
  (* src = "dut.sv:5.26-5.27" *)
  output q;
  wire q;
  \$_AND_  _0_ (
    .A(rstn),
    .B(d),
    .Y(q)
  );
endmodule
