/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* dynports =  1  *)
(* src = "dut.sv:15.4-20.6" *)
(* hdlname = "dut" *)
module \$paramod\dut\Width=s32'00000000000000000000000000010011 (wmask_i, x);
  (* src = "dut.sv:5.22-5.29" *)
  input [18:0] wmask_i;
  wire [18:0] wmask_i;
  (* src = "dut.sv:6.15-6.16" *)
  output signed [31:0] x;
  wire signed [31:0] x;
  assign x = { 13'h0000, wmask_i };
endmodule

(* dynports =  1  *)
(* src = "dut.sv:11.1-21.10" *)
(* top =  1  *)
module top(o);
  (* src = "dut.sv:11.23-11.24" *)
  output signed [31:0] o;
  wire signed [31:0] o;
  \$paramod\dut\Width=s32'00000000000000000000000000010011  u_dut (
    .wmask_i(19'h7ffff),
    .x(o)
  );
endmodule
