/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* top =  1  *)
(* src = "dut.sv:1.1-3.10" *)
module top(o);
  (* src = "dut.sv:1.27-1.28" *)
  output signed [63:0] o;
  wire signed [63:0] o;
  assign o = 64'h0000000000000001;
endmodule
