/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:30.4-33.6" *)
(* dynports =  1  *)
module flash_mp_data_region_sel(region_attrs_i, x);
  (* src = "dut.sv:22.29-22.43" *)
  input region_attrs_i;
  wire region_attrs_i;
  (* src = "dut.sv:23.17-23.18" *)
  output x;
  wire x;
  (* src = "dut.sv:22.29-22.43" *)
  (* unused_bits = "0" *)
  wire \region_attrs_i[0] ;
  assign x = 1'hx;
  assign \region_attrs_i[0]  = region_attrs_i;
endmodule

(* dynports =  1  *)
(* src = "dut.sv:28.1-34.10" *)
(* top =  1  *)
module top(o);
  (* src = "dut.sv:28.25-28.26" *)
  output o;
  wire o;
  flash_mp_data_region_sel u_hw_sel (
    .region_attrs_i(1'h1),
    .x(o)
  );
endmodule
