/* Generated by Yosys 0.68+1 (git sha1 bbc149ed5, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* dynports =  1  *)
(* src = "dut.sv:14.1-30.10" *)
(* top =  1  *)
module dut(hdr_i, arr_i, bundle_o, width_o);
  (* src = "dut.sv:22.32-22.37" *)
  input [3:0] hdr_i;
  wire [3:0] hdr_i;
  (* packed_elem_width = 32'd9 *)
  (* packed_outer_left = 32'd3 *)
  (* packed_outer_right = 32'd0 *)
  (* src = "dut.sv:23.32-23.37" *)
  input [35:0] arr_i;
  wire [35:0] arr_i;
  (* src = "dut.sv:24.32-24.40" *)
  output [39:0] bundle_o;
  wire [39:0] bundle_o;
  (* src = "dut.sv:25.32-25.39" *)
  output [31:0] width_o;
  wire [31:0] width_o;
  assign width_o = 32'd40;
  assign bundle_o = { hdr_i, arr_i };
endmodule
