/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "dut.sv:26.1-110.10" *)
module generate_test(clk, rst_n, data_in, operand, mode, result, extra_result);
  (* src = "dut.sv:30.18-30.21" *)
  input clk;
  wire clk;
  (* src = "dut.sv:32.45-32.52" *)
  input [31:0] data_in;
  wire [31:0] data_in;
  (* src = "dut.sv:36.35-36.47" *)
  output [7:0] extra_result;
  wire [7:0] extra_result;
  (* src = "dut.sv:34.18-34.22" *)
  input mode;
  wire mode;
  (* src = "dut.sv:33.45-33.52" *)
  input [31:0] operand;
  wire [31:0] operand;
  (* src = "dut.sv:35.45-35.51" *)
  output [31:0] result;
  wire [31:0] result;
  (* src = "dut.sv:31.18-31.23" *)
  input rst_n;
  wire rst_n;
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[0]  /* _00_ */ (
    .C(clk),
    .D(data_in[0]),
    .Q(result[0]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[1]  /* _01_ */ (
    .C(clk),
    .D(data_in[1]),
    .Q(result[1]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[2]  /* _02_ */ (
    .C(clk),
    .D(data_in[2]),
    .Q(result[2]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[3]  /* _03_ */ (
    .C(clk),
    .D(data_in[3]),
    .Q(result[3]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[4]  /* _04_ */ (
    .C(clk),
    .D(data_in[4]),
    .Q(result[4]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[5]  /* _05_ */ (
    .C(clk),
    .D(data_in[5]),
    .Q(result[5]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[6]  /* _06_ */ (
    .C(clk),
    .D(data_in[6]),
    .Q(result[6]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[7]  /* _07_ */ (
    .C(clk),
    .D(data_in[7]),
    .Q(result[7]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[8]  /* _08_ */ (
    .C(clk),
    .D(data_in[8]),
    .Q(result[8]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[9]  /* _09_ */ (
    .C(clk),
    .D(data_in[9]),
    .Q(result[9]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[10]  /* _10_ */ (
    .C(clk),
    .D(data_in[10]),
    .Q(result[10]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[11]  /* _11_ */ (
    .C(clk),
    .D(data_in[11]),
    .Q(result[11]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[12]  /* _12_ */ (
    .C(clk),
    .D(data_in[12]),
    .Q(result[12]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[13]  /* _13_ */ (
    .C(clk),
    .D(data_in[13]),
    .Q(result[13]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[14]  /* _14_ */ (
    .C(clk),
    .D(data_in[14]),
    .Q(result[14]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[15]  /* _15_ */ (
    .C(clk),
    .D(data_in[15]),
    .Q(result[15]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[16]  /* _16_ */ (
    .C(clk),
    .D(data_in[16]),
    .Q(result[16]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[17]  /* _17_ */ (
    .C(clk),
    .D(data_in[17]),
    .Q(result[17]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[18]  /* _18_ */ (
    .C(clk),
    .D(data_in[18]),
    .Q(result[18]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[19]  /* _19_ */ (
    .C(clk),
    .D(data_in[19]),
    .Q(result[19]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[20]  /* _20_ */ (
    .C(clk),
    .D(data_in[20]),
    .Q(result[20]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[21]  /* _21_ */ (
    .C(clk),
    .D(data_in[21]),
    .Q(result[21]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[22]  /* _22_ */ (
    .C(clk),
    .D(data_in[22]),
    .Q(result[22]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[23]  /* _23_ */ (
    .C(clk),
    .D(data_in[23]),
    .Q(result[23]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[24]  /* _24_ */ (
    .C(clk),
    .D(data_in[24]),
    .Q(result[24]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[25]  /* _25_ */ (
    .C(clk),
    .D(data_in[25]),
    .Q(result[25]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[26]  /* _26_ */ (
    .C(clk),
    .D(data_in[26]),
    .Q(result[26]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[27]  /* _27_ */ (
    .C(clk),
    .D(data_in[27]),
    .Q(result[27]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[28]  /* _28_ */ (
    .C(clk),
    .D(data_in[28]),
    .Q(result[28]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[29]  /* _29_ */ (
    .C(clk),
    .D(data_in[29]),
    .Q(result[29]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[30]  /* _30_ */ (
    .C(clk),
    .D(data_in[30]),
    .Q(result[30]),
    .R(rst_n)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:68.13-74.16" *)
  \$_DFF_PN0_  \result_reg[31]  /* _31_ */ (
    .C(clk),
    .D(data_in[31]),
    .Q(result[31]),
    .R(rst_n)
  );
  assign extra_result = 8'hxx;
endmodule
