/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:6.1-8.10" *)
(* top =  1  *)
module top(b, a);
  (* src = "dut.sv:6.22-6.23" *)
  input signed [31:0] b;
  wire signed [31:0] b;
  (* src = "dut.sv:6.36-6.37" *)
  output signed [31:0] a;
  wire signed [31:0] a;
  assign a = b;
endmodule
