/* Generated by Yosys 0.56+171 (git sha1 6fdcdd41d, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* dynports =  1  *)
(* src = "dut.sv:6.1-94.10" *)
(* top =  1  *)
module fsm_using_function(clock, reset, req_0, req_1, gnt_0, gnt_1);
  (* src = "dut.sv:7.1-7.6" *)
  input clock;
  wire clock;
  (* src = "dut.sv:8.1-8.6" *)
  input reset;
  wire reset;
  (* src = "dut.sv:9.1-9.6" *)
  input req_0;
  wire req_0;
  (* src = "dut.sv:10.1-10.6" *)
  input req_1;
  wire req_1;
  (* src = "dut.sv:11.1-11.6" *)
  output gnt_0;
  wire gnt_0;
  (* src = "dut.sv:12.1-12.6" *)
  output gnt_1;
  wire gnt_1;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:48.4-52.18|dut.sv:35.3-54.10|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:574.22-574.23" *)
  (* unused_bits = "2" *)
  wire [2:0] _24_;
  wire [2:0] \fsm_function$func$dut.sv:29$1.$result ;
  (* nosync = 32'd1 *)
  (* src = "dut.sv:29.21-29.54" *)
  wire \fsm_function$func$dut.sv:29$2.req_0 ;
  (* nosync = 32'd1 *)
  (* src = "dut.sv:29.21-29.54" *)
  wire \fsm_function$func$dut.sv:29$2.req_1 ;
  (* nosync = 32'd1 *)
  (* src = "dut.sv:29.21-29.54" *)
  wire [2:0] \fsm_function$func$dut.sv:29$2.state ;
  (* src = "dut.sv:27.27-27.37" *)
  wire [2:0] next_state;
  (* \reg  = 32'd1 *)
  (* src = "dut.sv:26.27-26.32" *)
  wire [2:0] state;
  \$_NOT_  _25_ (
    .A(state[2]),
    .Y(_00_)
  );
  \$_OR_  _26_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_01_)
  );
  \$_OR_  _27_ (
    .A(_01_),
    .B(_00_),
    .Y(_02_)
  );
  \$_NOT_  _28_ (
    .A(_02_),
    .Y(_24_[0])
  );
  \$_ORNOT_  _29_ (
    .A(state[0]),
    .B(state[1]),
    .Y(_03_)
  );
  \$_OR_  _30_ (
    .A(_03_),
    .B(state[2]),
    .Y(_04_)
  );
  \$_NOT_  _31_ (
    .A(_04_),
    .Y(_24_[1])
  );
  \$_ORNOT_  _32_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_05_)
  );
  \$_ANDNOT_  _33_ (
    .A(_00_),
    .B(_05_),
    .Y(_06_)
  );
  \$_MUX_  _34_ (
    .A(_03_),
    .B(_01_),
    .S(state[2]),
    .Y(_07_)
  );
  \$_ORNOT_  _35_ (
    .A(_06_),
    .B(_07_),
    .Y(_08_)
  );
  \$_NOT_  _36_ (
    .A(req_1),
    .Y(_09_)
  );
  \$_ANDNOT_  _37_ (
    .A(_09_),
    .B(_02_),
    .Y(_10_)
  );
  \$_NOT_  _38_ (
    .A(req_0),
    .Y(_11_)
  );
  \$_ANDNOT_  _39_ (
    .A(_11_),
    .B(_04_),
    .Y(_12_)
  );
  \$_OR_  _40_ (
    .A(_12_),
    .B(_10_),
    .Y(_13_)
  );
  \$_OR_  _41_ (
    .A(req_1),
    .B(req_0),
    .Y(_14_)
  );
  \$_ANDNOT_  _42_ (
    .A(_06_),
    .B(_14_),
    .Y(_15_)
  );
  \$_OR_  _43_ (
    .A(_15_),
    .B(_13_),
    .Y(_16_)
  );
  \$_ORNOT_  _44_ (
    .A(_16_),
    .B(_08_),
    .Y(\fsm_function$func$dut.sv:29$1.$result [0])
  );
  \$_OR_  _45_ (
    .A(_04_),
    .B(_11_),
    .Y(_17_)
  );
  \$_ANDNOT_  _46_ (
    .A(_06_),
    .B(_11_),
    .Y(_18_)
  );
  \$_ANDNOT_  _47_ (
    .A(_17_),
    .B(_18_),
    .Y(_19_)
  );
  \$_ANDNOT_  _48_ (
    .A(_08_),
    .B(_19_),
    .Y(\fsm_function$func$dut.sv:29$1.$result [1])
  );
  \$_OR_  _49_ (
    .A(_02_),
    .B(_09_),
    .Y(_20_)
  );
  \$_ORNOT_  _50_ (
    .A(req_0),
    .B(req_1),
    .Y(_21_)
  );
  \$_ANDNOT_  _51_ (
    .A(_06_),
    .B(_21_),
    .Y(_22_)
  );
  \$_ANDNOT_  _52_ (
    .A(_20_),
    .B(_22_),
    .Y(_23_)
  );
  \$_ANDNOT_  _53_ (
    .A(_08_),
    .B(_23_),
    .Y(\fsm_function$func$dut.sv:29$1.$result [2])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:66.1-92.4" *)
  \$_SDFF_PP0_  gnt_0_reg /* _54_ */ (
    .C(clock),
    .D(_24_[1]),
    .Q(gnt_0),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:66.1-92.4" *)
  \$_SDFF_PP0_  gnt_1_reg /* _55_ */ (
    .C(clock),
    .D(_24_[0]),
    .Q(gnt_1),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:57.1-64.4" *)
  \$_SDFF_PP1_  \state_reg[0]  /* _56_ */ (
    .C(clock),
    .D(\fsm_function$func$dut.sv:29$1.$result [0]),
    .Q(state[0]),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:57.1-64.4" *)
  \$_SDFF_PP0_  \state_reg[1]  /* _57_ */ (
    .C(clock),
    .D(\fsm_function$func$dut.sv:29$1.$result [1]),
    .Q(state[1]),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:57.1-64.4" *)
  \$_SDFF_PP0_  \state_reg[2]  /* _58_ */ (
    .C(clock),
    .D(\fsm_function$func$dut.sv:29$1.$result [2]),
    .Q(state[2]),
    .R(reset)
  );
  assign \fsm_function$func$dut.sv:29$2.req_0  = 1'hx;
  assign \fsm_function$func$dut.sv:29$2.req_1  = 1'hx;
  assign \fsm_function$func$dut.sv:29$2.state  = 3'hx;
  assign next_state = \fsm_function$func$dut.sv:29$1.$result ;
endmodule
