/* Generated by Yosys 0.68+1 (git sha1 bbc149ed5, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* top =  1  *)
(* src = "dut.sv:12.1-39.10" *)
module param_dyn_elem_select(clk, sel, din, ut_out, pipe_out, is_par);
  (* src = "dut.sv:13.25-13.28" *)
  input clk;
  wire clk;
  (* src = "dut.sv:14.25-14.28" *)
  input [2:0] sel;
  wire [2:0] sel;
  (* src = "dut.sv:15.25-15.28" *)
  input [31:0] din;
  wire [31:0] din;
  (* src = "dut.sv:16.25-16.31" *)
  output [1:0] ut_out;
  wire [1:0] ut_out;
  (* src = "dut.sv:17.25-17.33" *)
  output [31:0] pipe_out;
  wire [31:0] pipe_out;
  (* src = "dut.sv:18.25-18.31" *)
  output is_par;
  wire is_par;
  wire _00_;
  (* src = "dut.sv:29.26-29.30" *)
  (* unused_bits = "32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191" *)
  wire [191:0] pipe;
  \$_NOR_  _01_ (
    .A(sel[1]),
    .B(sel[2]),
    .Y(_00_)
  );
  \$_MUX_  _02_ (
    .A(_00_),
    .B(sel[1]),
    .S(sel[0]),
    .Y(is_par)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[0]  /* _03_ */ (
    .C(clk),
    .D(pipe[96]),
    .Q(pipe[0])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[1]  /* _04_ */ (
    .C(clk),
    .D(pipe[97]),
    .Q(pipe[1])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[2]  /* _05_ */ (
    .C(clk),
    .D(pipe[98]),
    .Q(pipe[2])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[3]  /* _06_ */ (
    .C(clk),
    .D(pipe[99]),
    .Q(pipe[3])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[4]  /* _07_ */ (
    .C(clk),
    .D(pipe[100]),
    .Q(pipe[4])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[5]  /* _08_ */ (
    .C(clk),
    .D(pipe[101]),
    .Q(pipe[5])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[6]  /* _09_ */ (
    .C(clk),
    .D(pipe[102]),
    .Q(pipe[6])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[7]  /* _10_ */ (
    .C(clk),
    .D(pipe[103]),
    .Q(pipe[7])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[8]  /* _11_ */ (
    .C(clk),
    .D(pipe[104]),
    .Q(pipe[8])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[9]  /* _12_ */ (
    .C(clk),
    .D(pipe[105]),
    .Q(pipe[9])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[10]  /* _13_ */ (
    .C(clk),
    .D(pipe[106]),
    .Q(pipe[10])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[11]  /* _14_ */ (
    .C(clk),
    .D(pipe[107]),
    .Q(pipe[11])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[12]  /* _15_ */ (
    .C(clk),
    .D(pipe[108]),
    .Q(pipe[12])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[13]  /* _16_ */ (
    .C(clk),
    .D(pipe[109]),
    .Q(pipe[13])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[14]  /* _17_ */ (
    .C(clk),
    .D(pipe[110]),
    .Q(pipe[14])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[15]  /* _18_ */ (
    .C(clk),
    .D(pipe[111]),
    .Q(pipe[15])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[16]  /* _19_ */ (
    .C(clk),
    .D(pipe[112]),
    .Q(pipe[16])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[17]  /* _20_ */ (
    .C(clk),
    .D(pipe[113]),
    .Q(pipe[17])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[18]  /* _21_ */ (
    .C(clk),
    .D(pipe[114]),
    .Q(pipe[18])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[19]  /* _22_ */ (
    .C(clk),
    .D(pipe[115]),
    .Q(pipe[19])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[20]  /* _23_ */ (
    .C(clk),
    .D(pipe[116]),
    .Q(pipe[20])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[21]  /* _24_ */ (
    .C(clk),
    .D(pipe[117]),
    .Q(pipe[21])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[22]  /* _25_ */ (
    .C(clk),
    .D(pipe[118]),
    .Q(pipe[22])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[23]  /* _26_ */ (
    .C(clk),
    .D(pipe[119]),
    .Q(pipe[23])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[24]  /* _27_ */ (
    .C(clk),
    .D(pipe[120]),
    .Q(pipe[24])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[25]  /* _28_ */ (
    .C(clk),
    .D(pipe[121]),
    .Q(pipe[25])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[26]  /* _29_ */ (
    .C(clk),
    .D(pipe[122]),
    .Q(pipe[26])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[27]  /* _30_ */ (
    .C(clk),
    .D(pipe[123]),
    .Q(pipe[27])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[28]  /* _31_ */ (
    .C(clk),
    .D(pipe[124]),
    .Q(pipe[28])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[29]  /* _32_ */ (
    .C(clk),
    .D(pipe[125]),
    .Q(pipe[29])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[30]  /* _33_ */ (
    .C(clk),
    .D(pipe[126]),
    .Q(pipe[30])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[31]  /* _34_ */ (
    .C(clk),
    .D(pipe[127]),
    .Q(pipe[31])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[96]  /* _35_ */ (
    .C(clk),
    .D(din[0]),
    .Q(pipe[96])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[97]  /* _36_ */ (
    .C(clk),
    .D(din[1]),
    .Q(pipe[97])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[98]  /* _37_ */ (
    .C(clk),
    .D(din[2]),
    .Q(pipe[98])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[99]  /* _38_ */ (
    .C(clk),
    .D(din[3]),
    .Q(pipe[99])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[100]  /* _39_ */ (
    .C(clk),
    .D(din[4]),
    .Q(pipe[100])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[101]  /* _40_ */ (
    .C(clk),
    .D(din[5]),
    .Q(pipe[101])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[102]  /* _41_ */ (
    .C(clk),
    .D(din[6]),
    .Q(pipe[102])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[103]  /* _42_ */ (
    .C(clk),
    .D(din[7]),
    .Q(pipe[103])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[104]  /* _43_ */ (
    .C(clk),
    .D(din[8]),
    .Q(pipe[104])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[105]  /* _44_ */ (
    .C(clk),
    .D(din[9]),
    .Q(pipe[105])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[106]  /* _45_ */ (
    .C(clk),
    .D(din[10]),
    .Q(pipe[106])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[107]  /* _46_ */ (
    .C(clk),
    .D(din[11]),
    .Q(pipe[107])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[108]  /* _47_ */ (
    .C(clk),
    .D(din[12]),
    .Q(pipe[108])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[109]  /* _48_ */ (
    .C(clk),
    .D(din[13]),
    .Q(pipe[109])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[110]  /* _49_ */ (
    .C(clk),
    .D(din[14]),
    .Q(pipe[110])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[111]  /* _50_ */ (
    .C(clk),
    .D(din[15]),
    .Q(pipe[111])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[112]  /* _51_ */ (
    .C(clk),
    .D(din[16]),
    .Q(pipe[112])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[113]  /* _52_ */ (
    .C(clk),
    .D(din[17]),
    .Q(pipe[113])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[114]  /* _53_ */ (
    .C(clk),
    .D(din[18]),
    .Q(pipe[114])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[115]  /* _54_ */ (
    .C(clk),
    .D(din[19]),
    .Q(pipe[115])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[116]  /* _55_ */ (
    .C(clk),
    .D(din[20]),
    .Q(pipe[116])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[117]  /* _56_ */ (
    .C(clk),
    .D(din[21]),
    .Q(pipe[117])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[118]  /* _57_ */ (
    .C(clk),
    .D(din[22]),
    .Q(pipe[118])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[119]  /* _58_ */ (
    .C(clk),
    .D(din[23]),
    .Q(pipe[119])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[120]  /* _59_ */ (
    .C(clk),
    .D(din[24]),
    .Q(pipe[120])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[121]  /* _60_ */ (
    .C(clk),
    .D(din[25]),
    .Q(pipe[121])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[122]  /* _61_ */ (
    .C(clk),
    .D(din[26]),
    .Q(pipe[122])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[123]  /* _62_ */ (
    .C(clk),
    .D(din[27]),
    .Q(pipe[123])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[124]  /* _63_ */ (
    .C(clk),
    .D(din[28]),
    .Q(pipe[124])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[125]  /* _64_ */ (
    .C(clk),
    .D(din[29]),
    .Q(pipe[125])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[126]  /* _65_ */ (
    .C(clk),
    .D(din[30]),
    .Q(pipe[126])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:31.3-36.6" *)
  \$_DFF_P_  \pipe_reg[127]  /* _66_ */ (
    .C(clk),
    .D(din[31]),
    .Q(pipe[127])
  );
  assign { pipe[160], pipe[64] } = { pipe[128], pipe[32] };
  assign pipe_out = pipe[31:0];
  assign ut_out = { 1'h0, is_par };
endmodule
