/* Generated by Yosys 0.62+39 (git sha1 131911291-dirty, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* keep =  1  *)
(* src = "dut.sv:1.1-87.10" *)
(* top =  1  *)
module top();
  wire fail;
  (* src = "dut.sv:83.9-83.29" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967295),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _0_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  assign fail = 1'h1;
endmodule
