/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* keep =  1  *)
(* src = "dut.sv:31.1-220.10" *)
(* top =  1  *)
module dut();
  (* src = "dut.sv:52.45-52.57" *)
  wire [1:0] access_fault;
  (* src = "dut.sv:44.45-44.59" *)
  wire [33:0] \csr_pmp_addr_i[0] ;
  (* src = "dut.sv:44.45-44.59" *)
  wire [33:0] \csr_pmp_addr_i[1] ;
  (* src = "dut.sv:44.45-44.59" *)
  wire [33:0] \csr_pmp_addr_i[2] ;
  (* src = "dut.sv:44.45-44.59" *)
  wire [33:0] \csr_pmp_addr_i[3] ;
  (* src = "dut.sv:43.45-43.58" *)
  wire [5:0] \csr_pmp_cfg_i[0] ;
  (* src = "dut.sv:43.45-43.58" *)
  wire [5:0] \csr_pmp_cfg_i[1] ;
  (* src = "dut.sv:42.45-42.59" *)
  wire [33:0] \pmp_req_addr_i[0] ;
  (* src = "dut.sv:42.45-42.59" *)
  wire [33:0] \pmp_req_addr_i[1] ;
  (* src = "dut.sv:39.45-39.58" *)
  wire \pmp_req_err_o[0] ;
  (* src = "dut.sv:39.45-39.58" *)
  wire \pmp_req_err_o[1] ;
  (* src = "dut.sv:41.45-41.59" *)
  wire [1:0] \pmp_req_type_i[0] ;
  (* src = "dut.sv:41.45-41.59" *)
  wire [1:0] \pmp_req_type_i[1] ;
  (* src = "dut.sv:40.45-40.56" *)
  wire [1:0] \priv_mode_i[0] ;
  (* src = "dut.sv:40.45-40.56" *)
  wire [1:0] \priv_mode_i[1] ;
  (* src = "dut.sv:46.45-46.61" *)
  wire [31:0] \region_addr_mask[0] ;
  (* src = "dut.sv:46.45-46.61" *)
  wire [31:0] \region_addr_mask[1] ;
  (* src = "dut.sv:46.45-46.61" *)
  wire [31:0] \region_addr_mask[2] ;
  (* src = "dut.sv:46.45-46.61" *)
  wire [31:0] \region_addr_mask[3] ;
  (* src = "dut.sv:50.45-50.61" *)
  wire [7:0] region_match_all;
  (* src = "dut.sv:49.45-49.60" *)
  wire [7:0] region_match_eq;
  (* src = "dut.sv:47.45-47.60" *)
  wire [7:0] region_match_gt;
  (* src = "dut.sv:48.45-48.60" *)
  wire [7:0] region_match_lt;
  (* src = "dut.sv:51.45-51.62" *)
  wire [7:0] region_perm_check;
  (* src = "dut.sv:45.45-45.62" *)
  wire [33:0] \region_start_addr[0] ;
  (* src = "dut.sv:45.45-45.62" *)
  wire [33:0] \region_start_addr[1] ;
  (* src = "dut.sv:45.45-45.62" *)
  wire [33:0] \region_start_addr[2] ;
  (* src = "dut.sv:45.45-45.62" *)
  wire [33:0] \region_start_addr[3] ;
  (* keep = 32'd1 *)
  (* src = "dut.sv:167.3-167.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967295),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _00_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:168.3-168.50" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967294),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _01_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:169.3-169.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967293),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _02_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:170.3-170.42" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967292),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _03_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:171.3-171.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967291),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _04_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:172.3-172.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967290),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _05_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:173.3-173.49" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967289),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _06_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:175.3-175.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967288),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _07_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:176.3-176.53" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967287),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _08_ (
    .A(1'h0),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:177.3-177.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967286),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _09_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:178.3-178.42" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967285),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _10_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:179.3-179.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967284),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _11_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:180.3-180.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967283),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _12_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:181.3-181.53" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967282),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _13_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:183.3-183.51" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967281),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _14_ (
    .A(1'h0),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:184.3-184.42" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967280),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _15_ (
    .A(1'h0),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:185.3-185.42" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967279),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _16_ (
    .A(1'h0),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:186.3-186.49" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967278),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _17_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:187.3-187.42" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967277),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _18_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:188.3-188.42" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967276),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _19_ (
    .A(1'h0),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:190.3-190.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967275),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _20_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:191.3-191.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967274),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _21_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:192.3-192.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967273),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _22_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:194.3-194.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967272),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _23_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:195.3-195.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967271),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _24_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:196.3-196.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967270),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _25_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:198.3-198.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967269),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _26_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:199.3-199.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967268),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _27_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:200.3-200.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967267),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _28_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:202.3-202.42" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967266),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _29_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:203.3-203.59" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967265),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _30_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:204.3-204.42" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967264),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _31_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:205.3-205.59" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967263),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _32_ (
    .A(1'h0),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:207.3-207.43" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967262),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _33_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:208.3-208.43" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967261),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _34_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:209.3-209.43" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967260),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _35_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:210.3-210.43" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967259),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _36_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:212.3-212.40" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967258),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _37_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:213.3-213.40" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967257),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _38_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:215.3-215.42" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967256),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _39_ (
    .A(1'h0),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:217.3-217.35" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967255),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _40_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:218.3-218.55" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967254),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _41_ (
    .A(1'hx),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  assign region_match_all = 8'b0000000x;
  assign region_match_eq = 8'he1;
  assign region_match_lt = 8'h0e;
  assign region_match_gt = 8'h10;
  assign \region_addr_mask[3]  = 32'd5;
  assign \region_addr_mask[2]  = 32'd5;
  assign \region_addr_mask[1]  = 32'd5;
  assign \region_addr_mask[0]  = 32'd5;
  assign \region_start_addr[3]  = 34'h111111111;
  assign \region_start_addr[2]  = 34'h111111111;
  assign \region_start_addr[1]  = 34'h111111111;
  assign \region_start_addr[0]  = 34'h000000000;
  assign \csr_pmp_addr_i[3]  = 34'h111111111;
  assign \csr_pmp_addr_i[2]  = 34'h111111111;
  assign \csr_pmp_addr_i[1]  = 34'h111111111;
  assign \csr_pmp_addr_i[0]  = 34'h000000000;
  assign region_perm_check = 8'hxx;
  assign access_fault = 2'h2;
  assign \csr_pmp_cfg_i[1]  = 6'hxx;
  assign \csr_pmp_cfg_i[0]  = 6'hxx;
  assign \pmp_req_addr_i[1]  = 34'h111111111;
  assign \pmp_req_addr_i[0]  = 34'h000000000;
  assign \pmp_req_type_i[1]  = 2'h0;
  assign \pmp_req_type_i[0]  = 2'h0;
  assign \priv_mode_i[1]  = 2'h2;
  assign \priv_mode_i[0]  = 2'h3;
  assign \pmp_req_err_o[1]  = 1'h1;
  assign \pmp_req_err_o[0]  = 1'h0;
endmodule
