/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) */

(* top =  1  *)
(* src = "dut.sv:1.1-16.10" *)
module logic_ops(in, B1, B2, B3, B4, B5, B6, B7, B8, B9, B10);
  (* src = "dut.sv:3.17-3.19" *)
  input [0:7] in;
  wire [0:7] in;
  (* src = "dut.sv:4.17-4.19" *)
  output B1;
  wire B1;
  (* src = "dut.sv:4.20-4.22" *)
  output B2;
  wire B2;
  (* src = "dut.sv:4.23-4.25" *)
  output B3;
  wire B3;
  (* src = "dut.sv:4.26-4.28" *)
  output B4;
  wire B4;
  (* src = "dut.sv:4.29-4.31" *)
  output B5;
  wire B5;
  (* src = "dut.sv:4.32-4.34" *)
  output B6;
  wire B6;
  (* src = "dut.sv:4.35-4.37" *)
  output B7;
  wire B7;
  (* src = "dut.sv:4.38-4.40" *)
  output B8;
  wire B8;
  (* src = "dut.sv:4.42-4.44" *)
  output B9;
  wire B9;
  (* src = "dut.sv:4.46-4.49" *)
  output B10;
  wire B10;
  wire _00_;
  \$_NOT_  _01_ (
    .A(in[0]),
    .Y(B7)
  );
  \$_NOR_  _02_ (
    .A(in[1]),
    .B(in[0]),
    .Y(B4)
  );
  \$_NOT_  _03_ (
    .A(B4),
    .Y(B2)
  );
  \$_NAND_  _04_ (
    .A(in[1]),
    .B(in[0]),
    .Y(B3)
  );
  \$_NOT_  _05_ (
    .A(B3),
    .Y(B1)
  );
  \$_AND_  _06_ (
    .A(B2),
    .B(B3),
    .Y(B5)
  );
  \$_NAND_  _07_ (
    .A(B2),
    .B(B3),
    .Y(B6)
  );
  \$_NOR_  _08_ (
    .A(in[3]),
    .B(in[2]),
    .Y(_00_)
  );
  \$_NAND_  _09_ (
    .A(B4),
    .B(_00_),
    .Y(B10)
  );
  \$_ANDNOT_  _10_ (
    .A(B2),
    .B(_00_),
    .Y(B9)
  );
  assign B8 = in[0];
endmodule
