/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* src = "dut.sv:1.1-8.10" *)
(* top =  1  *)
module top(a, b, c, d);
  (* src = "dut.sv:1.23-1.24" *)
  output signed [31:0] a;
  wire signed [31:0] a;
  (* src = "dut.sv:1.26-1.27" *)
  output signed [31:0] b;
  wire signed [31:0] b;
  (* src = "dut.sv:1.29-1.30" *)
  output signed [31:0] c;
  wire signed [31:0] c;
  (* src = "dut.sv:1.32-1.33" *)
  output signed [31:0] d;
  wire signed [31:0] d;
  (* src = "dut.sv:2.8-2.9" *)
  wire [31:0] \x[0] ;
  (* src = "dut.sv:2.8-2.9" *)
  wire [31:0] \x[1] ;
  (* src = "dut.sv:2.8-2.9" *)
  wire [31:0] \x[2] ;
  (* src = "dut.sv:2.8-2.9" *)
  wire [31:0] \x[3] ;
  assign \x[3]  = 32'd10;
  assign \x[2]  = 32'd11;
  assign \x[1]  = 32'd12;
  assign \x[0]  = 32'd13;
  assign d = 32'd10;
  assign c = 32'd11;
  assign b = 32'd12;
  assign a = 32'd13;
endmodule
