/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:24.1-26.10" *)
module consumer(o, \b.dat , \b.vld , \b.rst , \b.clk );
  (* src = "dut.sv:24.49-24.50" *)
  output [7:0] o;
  wire [7:0] o;
  (* src = "dut.sv:6.17-6.20" *)
  input [7:0] \b.dat ;
  wire [7:0] \b.dat ;
  (* src = "dut.sv:5.17-5.20" *)
  input \b.vld ;
  wire \b.vld ;
  (* src = "dut.sv:4.69-4.72" *)
  input \b.rst ;
  wire \b.rst ;
  (* src = "dut.sv:4.52-4.55" *)
  input \b.clk ;
  wire \b.clk ;
  \$_AND_  _0_ (
    .A(\b.dat [6]),
    .B(\b.vld ),
    .Y(o[6])
  );
  \$_AND_  _1_ (
    .A(\b.vld ),
    .B(\b.dat [5]),
    .Y(o[5])
  );
  \$_AND_  _2_ (
    .A(\b.vld ),
    .B(\b.dat [4]),
    .Y(o[4])
  );
  \$_AND_  _3_ (
    .A(\b.vld ),
    .B(\b.dat [3]),
    .Y(o[3])
  );
  \$_AND_  _4_ (
    .A(\b.vld ),
    .B(\b.dat [2]),
    .Y(o[2])
  );
  \$_AND_  _5_ (
    .A(\b.vld ),
    .B(\b.dat [1]),
    .Y(o[1])
  );
  \$_AND_  _6_ (
    .A(\b.vld ),
    .B(\b.dat [0]),
    .Y(o[0])
  );
  \$_AND_  _7_ (
    .A(\b.vld ),
    .B(\b.dat [7]),
    .Y(o[7])
  );
endmodule

(* src = "dut.sv:28.1-41.10" *)
(* top =  1  *)
module dut(clk, rst, sd, o0, o1);
  (* src = "dut.sv:29.22-29.25" *)
  input clk;
  wire clk;
  (* src = "dut.sv:30.22-30.25" *)
  input rst;
  wire rst;
  (* src = "dut.sv:31.22-31.24" *)
  input [7:0] sd;
  wire [7:0] sd;
  (* src = "dut.sv:32.22-32.24" *)
  output [7:0] o0;
  wire [7:0] o0;
  (* src = "dut.sv:33.22-33.24" *)
  output [7:0] o1;
  wire [7:0] o1;
  (* src = "dut.sv:4.52-4.55" *)
  wire \arr[0].clk ;
  (* src = "dut.sv:6.17-6.20" *)
  wire [7:0] \arr[0].dat ;
  (* src = "dut.sv:4.69-4.72" *)
  wire \arr[0].rst ;
  (* src = "dut.sv:5.17-5.20" *)
  wire \arr[0].vld ;
  (* src = "dut.sv:4.52-4.55" *)
  wire \arr[1].clk ;
  (* src = "dut.sv:6.17-6.20" *)
  wire [7:0] \arr[1].dat ;
  (* src = "dut.sv:4.69-4.72" *)
  wire \arr[1].rst ;
  (* src = "dut.sv:5.17-5.20" *)
  wire \arr[1].vld ;
  (* src = "dut.sv:4.52-4.55" *)
  wire \src.clk ;
  (* src = "dut.sv:6.17-6.20" *)
  wire [7:0] \src.dat ;
  (* src = "dut.sv:4.69-4.72" *)
  wire \src.rst ;
  (* src = "dut.sv:5.17-5.20" *)
  wire \src.vld ;
  consumer c0 (
    .\b.clk (clk),
    .\b.dat (\arr[0].dat ),
    .\b.rst (rst),
    .\b.vld (\arr[0].vld ),
    .o(o0)
  );
  consumer c1 (
    .\b.clk (clk),
    .\b.dat (\arr[1].dat ),
    .\b.rst (rst),
    .\b.vld (\arr[1].vld ),
    .o(o1)
  );
  fanout f (
    .\m[0].clk (clk),
    .\m[0].dat (\arr[0].dat ),
    .\m[0].rst (rst),
    .\m[0].vld (\arr[0].vld ),
    .\m[1].clk (clk),
    .\m[1].dat (\arr[1].dat ),
    .\m[1].rst (rst),
    .\m[1].vld (\arr[1].vld ),
    .\s.clk (clk),
    .\s.dat (\src.dat ),
    .\s.rst (rst),
    .\s.vld (\src.vld )
  );
  producer p (
    .\b.clk (clk),
    .\b.dat (\src.dat ),
    .\b.rst (rst),
    .\b.vld (\src.vld ),
    .seed(sd)
  );
  assign \arr[1].rst  = rst;
  assign \arr[1].clk  = clk;
  assign \arr[0].rst  = rst;
  assign \arr[0].clk  = clk;
  assign \src.rst  = rst;
  assign \src.clk  = clk;
endmodule

(* src = "dut.sv:17.1-22.10" *)
module fanout(\m[1].dat , \m[1].vld , \m[1].rst , \m[1].clk , \m[0].dat , \m[0].vld , \m[0].rst , \m[0].clk , \s.dat , \s.vld , \s.rst , \s.clk );
  (* src = "dut.sv:6.17-6.20" *)
  output [7:0] \m[1].dat ;
  wire [7:0] \m[1].dat ;
  (* src = "dut.sv:5.17-5.20" *)
  output \m[1].vld ;
  wire \m[1].vld ;
  input \m[1].rst ;
  wire \m[1].rst ;
  input \m[1].clk ;
  wire \m[1].clk ;
  (* src = "dut.sv:6.17-6.20" *)
  output [7:0] \m[0].dat ;
  wire [7:0] \m[0].dat ;
  (* src = "dut.sv:5.17-5.20" *)
  output \m[0].vld ;
  wire \m[0].vld ;
  input \m[0].rst ;
  wire \m[0].rst ;
  input \m[0].clk ;
  wire \m[0].clk ;
  (* src = "dut.sv:6.17-6.20" *)
  input [7:0] \s.dat ;
  wire [7:0] \s.dat ;
  (* src = "dut.sv:5.17-5.20" *)
  input \s.vld ;
  wire \s.vld ;
  (* src = "dut.sv:4.69-4.72" *)
  input \s.rst ;
  wire \s.rst ;
  (* src = "dut.sv:4.52-4.55" *)
  input \s.clk ;
  wire \s.clk ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  \$_NOT_  _06_ (
    .A(\s.dat [0]),
    .Y(\m[1].dat [0])
  );
  \$_AND_  _07_ (
    .A(\s.dat [1]),
    .B(\s.dat [0]),
    .Y(_00_)
  );
  \$_AND_  _08_ (
    .A(\s.dat [2]),
    .B(_00_),
    .Y(_01_)
  );
  \$_AND_  _09_ (
    .A(\s.dat [3]),
    .B(_01_),
    .Y(_02_)
  );
  \$_AND_  _10_ (
    .A(\s.dat [4]),
    .B(_02_),
    .Y(_03_)
  );
  \$_AND_  _11_ (
    .A(\s.dat [5]),
    .B(_03_),
    .Y(_04_)
  );
  \$_NAND_  _12_ (
    .A(\s.dat [6]),
    .B(_04_),
    .Y(_05_)
  );
  \$_XNOR_  _13_ (
    .A(\s.dat [7]),
    .B(_05_),
    .Y(\m[1].dat [7])
  );
  \$_XOR_  _14_ (
    .A(\s.dat [6]),
    .B(_04_),
    .Y(\m[1].dat [6])
  );
  \$_XOR_  _15_ (
    .A(\s.dat [5]),
    .B(_03_),
    .Y(\m[1].dat [5])
  );
  \$_XOR_  _16_ (
    .A(\s.dat [4]),
    .B(_02_),
    .Y(\m[1].dat [4])
  );
  \$_XOR_  _17_ (
    .A(\s.dat [3]),
    .B(_01_),
    .Y(\m[1].dat [3])
  );
  \$_XOR_  _18_ (
    .A(\s.dat [2]),
    .B(_00_),
    .Y(\m[1].dat [2])
  );
  \$_XOR_  _19_ (
    .A(\s.dat [1]),
    .B(\s.dat [0]),
    .Y(\m[1].dat [1])
  );
  assign \m[0].dat  = \s.dat ;
  assign \m[0].vld  = \s.vld ;
  assign \m[1].vld  = \s.vld ;
endmodule

(* src = "dut.sv:11.1-14.10" *)
module producer(seed, \b.dat , \b.vld , \b.rst , \b.clk );
  (* src = "dut.sv:11.48-11.52" *)
  input [7:0] seed;
  wire [7:0] seed;
  (* src = "dut.sv:6.17-6.20" *)
  output [7:0] \b.dat ;
  wire [7:0] \b.dat ;
  (* src = "dut.sv:5.17-5.20" *)
  output \b.vld ;
  wire \b.vld ;
  (* src = "dut.sv:4.69-4.72" *)
  input \b.rst ;
  wire \b.rst ;
  (* src = "dut.sv:4.52-4.55" *)
  input \b.clk ;
  wire \b.clk ;
  assign \b.dat  = seed;
  assign \b.vld  = 1'h1;
endmodule
