/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) */

(* src = "dut.sv:1.1-5.10" *)
module adder(a, b, y);
  (* src = "dut.sv:2.17-2.18" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "dut.sv:2.32-2.33" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "dut.sv:2.48-2.49" *)
  output [7:0] y;
  wire [7:0] y;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  \$_AND_  _26_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  \$_XOR_  _27_ (
    .A(a[0]),
    .B(b[0]),
    .Y(y[0])
  );
  \$_NAND_  _28_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_01_)
  );
  \$_NAND_  _29_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_02_)
  );
  \$_NAND_  _30_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_03_)
  );
  \$_NAND_  _31_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_04_)
  );
  \$_NAND_  _32_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_05_)
  );
  \$_NAND_  _33_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_06_)
  );
  \$_XOR_  _34_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_07_)
  );
  \$_NAND_  _35_ (
    .A(_00_),
    .B(_07_),
    .Y(_08_)
  );
  \$_NAND_  _36_ (
    .A(_06_),
    .B(_08_),
    .Y(_09_)
  );
  \$_XOR_  _37_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_10_)
  );
  \$_NAND_  _38_ (
    .A(_09_),
    .B(_10_),
    .Y(_11_)
  );
  \$_NAND_  _39_ (
    .A(_05_),
    .B(_11_),
    .Y(_12_)
  );
  \$_XOR_  _40_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_13_)
  );
  \$_NAND_  _41_ (
    .A(_12_),
    .B(_13_),
    .Y(_14_)
  );
  \$_NAND_  _42_ (
    .A(_04_),
    .B(_14_),
    .Y(_15_)
  );
  \$_XOR_  _43_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_16_)
  );
  \$_NAND_  _44_ (
    .A(_15_),
    .B(_16_),
    .Y(_17_)
  );
  \$_NAND_  _45_ (
    .A(_03_),
    .B(_17_),
    .Y(_18_)
  );
  \$_XOR_  _46_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_19_)
  );
  \$_NAND_  _47_ (
    .A(_18_),
    .B(_19_),
    .Y(_20_)
  );
  \$_NAND_  _48_ (
    .A(_02_),
    .B(_20_),
    .Y(_21_)
  );
  \$_XOR_  _49_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_22_)
  );
  \$_NAND_  _50_ (
    .A(_21_),
    .B(_22_),
    .Y(_23_)
  );
  \$_NAND_  _51_ (
    .A(_01_),
    .B(_23_),
    .Y(_24_)
  );
  \$_XNOR_  _52_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_25_)
  );
  \$_XNOR_  _53_ (
    .A(_24_),
    .B(_25_),
    .Y(y[7])
  );
  \$_XOR_  _54_ (
    .A(_21_),
    .B(_22_),
    .Y(y[6])
  );
  \$_XOR_  _55_ (
    .A(_18_),
    .B(_19_),
    .Y(y[5])
  );
  \$_XOR_  _56_ (
    .A(_15_),
    .B(_16_),
    .Y(y[4])
  );
  \$_XOR_  _57_ (
    .A(_12_),
    .B(_13_),
    .Y(y[3])
  );
  \$_XOR_  _58_ (
    .A(_09_),
    .B(_10_),
    .Y(y[2])
  );
  \$_XOR_  _59_ (
    .A(_00_),
    .B(_07_),
    .Y(y[1])
  );
endmodule

(* src = "dut.sv:27.1-61.10" *)
module alu(clk, A, B, operation, result, CF, ZF, SF);
  (* src = "dut.sv:28.8-28.11" *)
  input clk;
  wire clk;
  (* src = "dut.sv:29.14-29.15" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "dut.sv:30.14-30.15" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "dut.sv:31.14-31.23" *)
  input [3:0] operation;
  wire [3:0] operation;
  (* src = "dut.sv:32.19-32.25" *)
  output [7:0] result;
  wire [7:0] result;
  (* src = "dut.sv:33.13-33.15" *)
  output CF;
  wire CF;
  (* src = "dut.sv:34.13-34.15" *)
  output ZF;
  wire ZF;
  (* src = "dut.sv:35.13-35.15" *)
  output SF;
  wire SF;
  (* src = "dut.sv:46.2-60.5" *)
  wire _000_;
  (* src = "dut.sv:46.2-60.5" *)
  wire [8:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  (* src = "dut.sv:42.12-42.17" *)
  wire [7:0] added;
  (* \reg  = 32'd1 *)
  (* src = "dut.sv:41.12-41.15" *)
  wire [8:0] tmp;
  \$_NOR_  _045_ (
    .A(operation[2]),
    .B(operation[3]),
    .Y(_003_)
  );
  \$_ANDNOT_  _046_ (
    .A(_003_),
    .B(operation[1]),
    .Y(_002_)
  );
  \$_AND_  _047_ (
    .A(operation[0]),
    .B(_002_),
    .Y(_004_)
  );
  \$_ORNOT_  _048_ (
    .A(B[5]),
    .B(A[5]),
    .Y(_005_)
  );
  \$_ORNOT_  _049_ (
    .A(B[4]),
    .B(A[4]),
    .Y(_006_)
  );
  \$_ORNOT_  _050_ (
    .A(B[3]),
    .B(A[3]),
    .Y(_007_)
  );
  \$_ORNOT_  _051_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_008_)
  );
  \$_ORNOT_  _052_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_009_)
  );
  \$_ORNOT_  _053_ (
    .A(A[0]),
    .B(B[0]),
    .Y(_010_)
  );
  \$_XNOR_  _054_ (
    .A(B[1]),
    .B(A[1]),
    .Y(_011_)
  );
  \$_NAND_  _055_ (
    .A(_010_),
    .B(_011_),
    .Y(_012_)
  );
  \$_NAND_  _056_ (
    .A(_009_),
    .B(_012_),
    .Y(_013_)
  );
  \$_XNOR_  _057_ (
    .A(B[2]),
    .B(A[2]),
    .Y(_014_)
  );
  \$_NAND_  _058_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  \$_NAND_  _059_ (
    .A(_008_),
    .B(_015_),
    .Y(_016_)
  );
  \$_XNOR_  _060_ (
    .A(A[3]),
    .B(B[3]),
    .Y(_017_)
  );
  \$_NAND_  _061_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  \$_NAND_  _062_ (
    .A(_007_),
    .B(_018_),
    .Y(_019_)
  );
  \$_XNOR_  _063_ (
    .A(A[4]),
    .B(B[4]),
    .Y(_020_)
  );
  \$_NAND_  _064_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  \$_NAND_  _065_ (
    .A(_006_),
    .B(_021_),
    .Y(_022_)
  );
  \$_XNOR_  _066_ (
    .A(A[5]),
    .B(B[5]),
    .Y(_023_)
  );
  \$_NAND_  _067_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  \$_NAND_  _068_ (
    .A(_005_),
    .B(_024_),
    .Y(_025_)
  );
  \$_ORNOT_  _069_ (
    .A(B[6]),
    .B(A[6]),
    .Y(_026_)
  );
  \$_XNOR_  _070_ (
    .A(A[6]),
    .B(B[6]),
    .Y(_027_)
  );
  \$_NAND_  _071_ (
    .A(_025_),
    .B(_027_),
    .Y(_028_)
  );
  \$_XOR_  _072_ (
    .A(_025_),
    .B(_027_),
    .Y(_029_)
  );
  \$_MUX_  _073_ (
    .A(added[6]),
    .B(_029_),
    .S(_004_),
    .Y(_001_[6])
  );
  \$_XOR_  _074_ (
    .A(_022_),
    .B(_023_),
    .Y(_030_)
  );
  \$_MUX_  _075_ (
    .A(added[5]),
    .B(_030_),
    .S(_004_),
    .Y(_001_[5])
  );
  \$_XOR_  _076_ (
    .A(_019_),
    .B(_020_),
    .Y(_031_)
  );
  \$_MUX_  _077_ (
    .A(added[4]),
    .B(_031_),
    .S(_004_),
    .Y(_001_[4])
  );
  \$_XOR_  _078_ (
    .A(_016_),
    .B(_017_),
    .Y(_032_)
  );
  \$_MUX_  _079_ (
    .A(added[3]),
    .B(_032_),
    .S(_004_),
    .Y(_001_[3])
  );
  \$_XOR_  _080_ (
    .A(_013_),
    .B(_014_),
    .Y(_033_)
  );
  \$_MUX_  _081_ (
    .A(added[2]),
    .B(_033_),
    .S(_004_),
    .Y(_001_[2])
  );
  \$_XOR_  _082_ (
    .A(_010_),
    .B(_011_),
    .Y(_034_)
  );
  \$_MUX_  _083_ (
    .A(added[1]),
    .B(_034_),
    .S(_004_),
    .Y(_001_[1])
  );
  \$_XOR_  _084_ (
    .A(B[0]),
    .B(A[0]),
    .Y(_035_)
  );
  \$_MUX_  _085_ (
    .A(added[0]),
    .B(_035_),
    .S(_004_),
    .Y(_001_[0])
  );
  \$_AND_  _086_ (
    .A(_026_),
    .B(_028_),
    .Y(_036_)
  );
  \$_XNOR_  _087_ (
    .A(A[7]),
    .B(B[7]),
    .Y(_037_)
  );
  \$_XNOR_  _088_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  \$_MUX_  _089_ (
    .A(added[7]),
    .B(_038_),
    .S(_004_),
    .Y(_001_[7])
  );
  \$_NOR_  _090_ (
    .A(tmp[2]),
    .B(tmp[3]),
    .Y(_039_)
  );
  \$_NOR_  _091_ (
    .A(tmp[0]),
    .B(tmp[1]),
    .Y(_040_)
  );
  \$_AND_  _092_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  \$_NOR_  _093_ (
    .A(tmp[6]),
    .B(tmp[7]),
    .Y(_042_)
  );
  \$_NOR_  _094_ (
    .A(tmp[4]),
    .B(tmp[5]),
    .Y(_043_)
  );
  \$_AND_  _095_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  \$_AND_  _096_ (
    .A(_041_),
    .B(_044_),
    .Y(_000_)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFFE_PP_  \tmp_reg[0]  /* _097_ */ (
    .C(clk),
    .D(_001_[0]),
    .E(_002_),
    .Q(tmp[0])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFFE_PP_  \tmp_reg[1]  /* _098_ */ (
    .C(clk),
    .D(_001_[1]),
    .E(_002_),
    .Q(tmp[1])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFFE_PP_  \tmp_reg[2]  /* _099_ */ (
    .C(clk),
    .D(_001_[2]),
    .E(_002_),
    .Q(tmp[2])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFFE_PP_  \tmp_reg[3]  /* _100_ */ (
    .C(clk),
    .D(_001_[3]),
    .E(_002_),
    .Q(tmp[3])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFFE_PP_  \tmp_reg[4]  /* _101_ */ (
    .C(clk),
    .D(_001_[4]),
    .E(_002_),
    .Q(tmp[4])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFFE_PP_  \tmp_reg[5]  /* _102_ */ (
    .C(clk),
    .D(_001_[5]),
    .E(_002_),
    .Q(tmp[5])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFFE_PP_  \tmp_reg[6]  /* _103_ */ (
    .C(clk),
    .D(_001_[6]),
    .E(_002_),
    .Q(tmp[6])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFFE_PP_  \tmp_reg[7]  /* _104_ */ (
    .C(clk),
    .D(_001_[7]),
    .E(_002_),
    .Q(tmp[7])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFF_P_  ZF_reg /* _105_ */ (
    .C(clk),
    .D(_000_),
    .Q(ZF)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFF_P_  \result_reg[0]  /* _106_ */ (
    .C(clk),
    .D(tmp[0]),
    .Q(result[0])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFF_P_  \result_reg[1]  /* _107_ */ (
    .C(clk),
    .D(tmp[1]),
    .Q(result[1])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFF_P_  \result_reg[2]  /* _108_ */ (
    .C(clk),
    .D(tmp[2]),
    .Q(result[2])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFF_P_  \result_reg[3]  /* _109_ */ (
    .C(clk),
    .D(tmp[3]),
    .Q(result[3])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFF_P_  \result_reg[4]  /* _110_ */ (
    .C(clk),
    .D(tmp[4]),
    .Q(result[4])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFF_P_  \result_reg[5]  /* _111_ */ (
    .C(clk),
    .D(tmp[5]),
    .Q(result[5])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFF_P_  \result_reg[6]  /* _112_ */ (
    .C(clk),
    .D(tmp[6]),
    .Q(result[6])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:46.2-60.5" *)
  \$_DFF_P_  \result_reg[7]  /* _113_ */ (
    .C(clk),
    .D(tmp[7]),
    .Q(result[7])
  );
  adder adder (
    .a(A),
    .b(B),
    .y(added)
  );
  assign _001_[8] = 1'h0;
  assign tmp[8] = 1'h0;
  assign SF = result[7];
  assign CF = 1'h0;
endmodule

(* src = "dut.sv:7.1-25.10" *)
(* top =  1  *)
module alu_sub(clk, A, B, op, result);
  (* src = "dut.sv:8.8-8.11" *)
  input clk;
  wire clk;
  (* src = "dut.sv:9.14-9.15" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "dut.sv:10.14-10.15" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "dut.sv:11.14-11.16" *)
  input [3:0] op;
  wire [3:0] op;
  (* src = "dut.sv:12.19-12.25" *)
  output [7:0] result;
  wire [7:0] result;
  (* src = "dut.sv:14.7-14.9" *)
  (* unused_bits = "0" *)
  wire CF;
  (* src = "dut.sv:14.15-14.17" *)
  (* unused_bits = "0" *)
  wire SF;
  (* src = "dut.sv:14.11-14.13" *)
  (* unused_bits = "0" *)
  wire ZF;
  alu alu (
    .A(A),
    .B(B),
    .CF(CF),
    .SF(SF),
    .ZF(ZF),
    .clk(clk),
    .operation(op),
    .result(result)
  );
endmodule
