/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* dynports =  1  *)
(* src = "dut.sv:24.4-28.6" *)
(* hdlname = "prim_generic_pad_attr" *)
module \$paramod\prim_generic_pad_attr\PadTypeInGeneric=s32'00000000000000000000000000000001 (o);
  (* src = "dut.sv:14.43-14.44" *)
  output o;
  wire o;
  assign o = 1'h1;
endmodule

(* dynports =  1  *)
(* src = "dut.sv:35.4-39.6" *)
(* hdlname = "prim_pad_attr" *)
module \$paramod\prim_pad_attr\PadType=s32'00000000000000000000000000000001 (o);
  (* src = "dut.sv:20.35-20.36" *)
  output o;
  wire o;
  \$paramod\prim_generic_pad_attr\PadTypeInGeneric=s32'00000000000000000000000000000001  u_impl_generic (
    .o(o)
  );
endmodule

(* dynports =  1  *)
(* src = "dut.sv:31.1-40.10" *)
(* top =  1  *)
module top(o);
  (* src = "dut.sv:31.25-31.26" *)
  output o;
  wire o;
  \$paramod\prim_pad_attr\PadType=s32'00000000000000000000000000000001  u_prim_pad_attr (
    .o(o)
  );
endmodule
