/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* top =  1  *)
(* src = "dut.sv:5.1-7.10" *)
module dut(clk, a, b);
  (* src = "dut.sv:5.24-5.27" *)
  input clk;
  wire clk;
  (* src = "dut.sv:5.46-5.47" *)
  input [7:0] a;
  wire [7:0] a;
  (* enum_type = "$enum0" *)
  (* enum_value_00000000 = "\\pkg::ONE" *)
  (* enum_value_00000001 = "\\pkg::TWO" *)
  (* enum_value_00000010 = "\\pkg::THREE" *)
  (* enum_value_00000011 = "\\pkg::FOUR" *)
  (* enum_value_00000100 = "\\pkg::FIVE" *)
  (* src = "dut.sv:5.68-5.69" *)
  (* wiretype = "\\pkg::enum_t" *)
  output [7:0] b;
  wire [7:0] b;
  assign b = a;
endmodule
