/* Generated by Yosys 0.56+171 (git sha1 6fdcdd41d, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* src = "dut.sv:1.1-63.10" *)
(* top =  1  *)
module scopes_test_01(k, x, y);
  (* src = "dut.sv:1.35-1.36" *)
  input [3:0] k;
  wire [3:0] k;
  (* src = "dut.sv:1.56-1.57" *)
  output [15:0] x;
  wire [15:0] x;
  (* src = "dut.sv:1.59-1.60" *)
  output [15:0] y;
  wire [15:0] y;
  (* nosync = 32'd1 *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] \task_01$func$dut.sv:52$0.a ;
  (* nosync = 32'd1 *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] \task_02$func$dut.sv:53$1.a ;
  (* nosync = 32'd1 *)
  wire [15:0] \task_02$func$dut.sv:53$1.foo.x ;
  assign \task_01$func$dut.sv:52$0.a  = k;
  assign \task_02$func$dut.sv:53$1.a  = k;
  assign \task_02$func$dut.sv:53$1.foo.x  = 16'h0000;
  assign x = 16'h0000;
  assign y = 16'h0000;
endmodule
