/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* src = "dut.sv:7.1-10.10" *)
(* top =  1  *)
module top(o);
  (* src = "dut.sv:7.23-7.24" *)
  output signed [31:0] o;
  wire signed [31:0] o;
  (* src = "dut.sv:8.26-8.46" *)
  wire [31:0] x;
  assign x = 32'd2863311530;
  assign o = 32'd2863311530;
endmodule
