/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* src = "dut.v:15.1-27.10" *)
module forloops01(clk, a, b, p, q, x, y);
  (* src = "dut.v:15.26-15.29" *)
  input clk;
  wire clk;
  (* src = "dut.v:15.31-15.32" *)
  input a;
  wire a;
  (* src = "dut.v:15.34-15.35" *)
  input b;
  wire b;
  (* src = "dut.v:15.54-15.55" *)
  output [3:0] p;
  wire [3:0] p;
  (* src = "dut.v:15.57-15.58" *)
  output [3:0] q;
  wire [3:0] q;
  (* src = "dut.v:15.60-15.61" *)
  output [3:0] x;
  wire [3:0] x;
  (* src = "dut.v:15.63-15.64" *)
  output [3:0] y;
  wire [3:0] y;
  (* src = "dut.v:16.10-16.11" *)
  wire signed [31:0] k;
  \$_NOT_  _0_ (
    .A(a),
    .Y(q[3])
  );
  \$_NOT_  _1_ (
    .A(b),
    .Y(q[2])
  );
  \$_NOR_  _2_ (
    .A(a),
    .B(b),
    .Y(y[2])
  );
  \$_XOR_  _3_ (
    .A(a),
    .B(b),
    .Y(y[1])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.v:17.2-21.5" *)
  \$_DFF_P_  \p_reg[0]  /* _4_ */ (
    .C(clk),
    .D(b),
    .Q(p[0])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.v:17.2-21.5" *)
  \$_DFF_P_  \p_reg[1]  /* _5_ */ (
    .C(clk),
    .D(a),
    .Q(p[1])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.v:17.2-21.5" *)
  \$_DFF_P_  \p_reg[2]  /* _6_ */ (
    .C(clk),
    .D(q[2]),
    .Q(p[2])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.v:17.2-21.5" *)
  \$_DFF_P_  \x_reg[1]  /* _7_ */ (
    .C(clk),
    .D(q[3]),
    .Q(x[1])
  );
  assign k = 32'd4;
  assign { y[3], y[0] } = { 1'h0, b };
  assign { x[3:2], x[0] } = { 1'h0, p[1:0] };
  assign q[1:0] = { a, b };
  assign p[3] = p[1];
endmodule

(* src = "dut.v:29.1-39.10" *)
module forloops02(clk, a, b, q, x, y);
  (* src = "dut.v:29.26-29.29" *)
  input clk;
  wire clk;
  (* src = "dut.v:29.31-29.32" *)
  input a;
  wire a;
  (* src = "dut.v:29.34-29.35" *)
  input b;
  wire b;
  (* src = "dut.v:29.54-29.55" *)
  output [3:0] q;
  wire [3:0] q;
  (* src = "dut.v:29.57-29.58" *)
  output [3:0] x;
  wire [3:0] x;
  (* src = "dut.v:29.73-29.74" *)
  output [3:0] y;
  wire [3:0] y;
  (* src = "dut.v:30.10-30.11" *)
  wire signed [31:0] k;
  \$_NOT_  _0_ (
    .A(b),
    .Y(q[2])
  );
  \$_NOT_  _1_ (
    .A(a),
    .Y(q[3])
  );
  \$_NOR_  _2_ (
    .A(b),
    .B(a),
    .Y(y[2])
  );
  \$_XOR_  _3_ (
    .A(b),
    .B(a),
    .Y(y[1])
  );
  assign k = 32'd4;
  assign { y[3], y[0] } = { 1'h0, b };
  assign x = { 2'h1, a, b };
  assign q[1:0] = { a, b };
endmodule

(* src = "dut.v:4.1-13.10" *)
(* top =  1  *)
module simple_forloops(clk, a1, b1, p1, q1, x1, y1, a2, b2, q2, x2, y2);
  (* src = "dut.v:5.15-5.18" *)
  input clk;
  wire clk;
  (* src = "dut.v:6.15-6.17" *)
  input a1;
  wire a1;
  (* src = "dut.v:6.19-6.21" *)
  input b1;
  wire b1;
  (* src = "dut.v:7.15-7.17" *)
  output [3:0] p1;
  wire [3:0] p1;
  (* src = "dut.v:7.19-7.21" *)
  output [3:0] q1;
  wire [3:0] q1;
  (* src = "dut.v:7.23-7.25" *)
  output [3:0] x1;
  wire [3:0] x1;
  (* src = "dut.v:7.27-7.29" *)
  output [3:0] y1;
  wire [3:0] y1;
  (* src = "dut.v:8.15-8.17" *)
  input a2;
  wire a2;
  (* src = "dut.v:8.19-8.21" *)
  input b2;
  wire b2;
  (* src = "dut.v:9.15-9.17" *)
  output [3:0] q2;
  wire [3:0] q2;
  (* src = "dut.v:9.19-9.21" *)
  output [3:0] x2;
  wire [3:0] x2;
  (* src = "dut.v:9.23-9.25" *)
  output [3:0] y2;
  wire [3:0] y2;
  forloops01 u1 (
    .a(a1),
    .b(b1),
    .clk(clk),
    .p(p1),
    .q(q1),
    .x(x1),
    .y(y1)
  );
  forloops02 u2 (
    .a(a2),
    .b(b2),
    .clk(clk),
    .q(q2),
    .x(x2),
    .y(y2)
  );
endmodule
