/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* src = "dut.sv:1.1-7.10" *)
(* top =  1  *)
module top(o);
  (* src = "dut.sv:1.31-1.32" *)
  output [7:0] o;
  wire [7:0] o;
  (* src = "dut.sv:5.14-5.15" *)
  (* wiretype = "\\my_struct" *)
  wire [7:0] s;
  assign s = 8'hxx;
  assign o = 8'hxx;
endmodule
