/* Generated by Yosys 0.62+39 (git sha1 131911291-dirty, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* dynports =  1  *)
(* src = "dut.sv:65.5-65.86" *)
(* hdlname = "RippleCarryAdder" *)
module \$paramod\RippleCarryAdder\N=s32'00000000000000000000000000000101 (A, B, Cin, S, Cout);
  (* src = "dut.sv:109.43-109.44" *)
  input [4:0] A;
  wire [4:0] A;
  (* src = "dut.sv:109.45-109.46" *)
  input [4:0] B;
  wire [4:0] B;
  (* src = "dut.sv:109.47-109.50" *)
  input Cin;
  wire Cin;
  (* src = "dut.sv:109.51-109.52" *)
  output [4:0] S;
  wire [4:0] S;
  (* src = "dut.sv:109.53-109.57" *)
  output Cout;
  wire Cout;
  (* src = "dut.sv:116.12-116.14" *)
  wire [5:0] CC;
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit (
    .A(A[0]),
    .B(B[0]),
    .Cin(Cin),
    .Cout(CC[1]),
    .S(S[0])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_1 (
    .A(A[1]),
    .B(B[1]),
    .Cin(CC[1]),
    .Cout(CC[2]),
    .S(S[1])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_2 (
    .A(A[2]),
    .B(B[2]),
    .Cin(CC[2]),
    .Cout(CC[3]),
    .S(S[2])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_3 (
    .A(A[3]),
    .B(B[3]),
    .Cin(CC[3]),
    .Cout(CC[4]),
    .S(S[3])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_4 (
    .A(A[4]),
    .B(B[4]),
    .Cin(CC[4]),
    .Cout(Cout),
    .S(S[4])
  );
  assign { CC[5], CC[0] } = { Cout, Cin };
endmodule

(* dynports =  1  *)
(* src = "dut.sv:65.5-65.86" *)
(* hdlname = "RippleCarryAdder" *)
module \$paramod\RippleCarryAdder\N=s32'00000000000000000000000000000110 (A, B, Cin, S, Cout);
  (* src = "dut.sv:109.43-109.44" *)
  input [5:0] A;
  wire [5:0] A;
  (* src = "dut.sv:109.45-109.46" *)
  input [5:0] B;
  wire [5:0] B;
  (* src = "dut.sv:109.47-109.50" *)
  input Cin;
  wire Cin;
  (* src = "dut.sv:109.51-109.52" *)
  output [5:0] S;
  wire [5:0] S;
  (* src = "dut.sv:109.53-109.57" *)
  output Cout;
  wire Cout;
  (* src = "dut.sv:116.12-116.14" *)
  wire [6:0] CC;
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit (
    .A(A[0]),
    .B(B[0]),
    .Cin(Cin),
    .Cout(CC[1]),
    .S(S[0])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_1 (
    .A(A[1]),
    .B(B[1]),
    .Cin(CC[1]),
    .Cout(CC[2]),
    .S(S[1])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_2 (
    .A(A[2]),
    .B(B[2]),
    .Cin(CC[2]),
    .Cout(CC[3]),
    .S(S[2])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_3 (
    .A(A[3]),
    .B(B[3]),
    .Cin(CC[3]),
    .Cout(CC[4]),
    .S(S[3])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_4 (
    .A(A[4]),
    .B(B[4]),
    .Cin(CC[4]),
    .Cout(CC[5]),
    .S(S[4])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_5 (
    .A(A[5]),
    .B(B[5]),
    .Cin(CC[5]),
    .Cout(Cout),
    .S(S[5])
  );
  assign { CC[6], CC[0] } = { Cout, Cin };
endmodule

(* dynports =  1  *)
(* src = "dut.sv:65.5-65.86" *)
(* hdlname = "RippleCarryAdder" *)
module \$paramod\RippleCarryAdder\N=s32'00000000000000000000000000000111 (A, B, Cin, S, Cout);
  (* src = "dut.sv:109.43-109.44" *)
  input [6:0] A;
  wire [6:0] A;
  (* src = "dut.sv:109.45-109.46" *)
  input [6:0] B;
  wire [6:0] B;
  (* src = "dut.sv:109.47-109.50" *)
  input Cin;
  wire Cin;
  (* src = "dut.sv:109.51-109.52" *)
  output [6:0] S;
  wire [6:0] S;
  (* src = "dut.sv:109.53-109.57" *)
  output Cout;
  wire Cout;
  (* src = "dut.sv:116.12-116.14" *)
  wire [7:0] CC;
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit (
    .A(A[0]),
    .B(B[0]),
    .Cin(Cin),
    .Cout(CC[1]),
    .S(S[0])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_1 (
    .A(A[1]),
    .B(B[1]),
    .Cin(CC[1]),
    .Cout(CC[2]),
    .S(S[1])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_2 (
    .A(A[2]),
    .B(B[2]),
    .Cin(CC[2]),
    .Cout(CC[3]),
    .S(S[2])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_3 (
    .A(A[3]),
    .B(B[3]),
    .Cin(CC[3]),
    .Cout(CC[4]),
    .S(S[3])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_4 (
    .A(A[4]),
    .B(B[4]),
    .Cin(CC[4]),
    .Cout(CC[5]),
    .S(S[4])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_5 (
    .A(A[5]),
    .B(B[5]),
    .Cin(CC[5]),
    .Cout(CC[6]),
    .S(S[5])
  );
  (* src = "dut.sv:124.5-124.50" *)
  FullAdder unit_6 (
    .A(A[6]),
    .B(B[6]),
    .Cin(CC[6]),
    .Cout(Cout),
    .S(S[6])
  );
  assign { CC[7], CC[0] } = { Cout, Cin };
endmodule

(* src = "dut.sv:130.1-132.10" *)
module FullAdder(A, B, Cin, S, Cout);
  (* src = "dut.sv:130.24-130.25" *)
  input A;
  wire A;
  (* src = "dut.sv:130.26-130.27" *)
  input B;
  wire B;
  (* src = "dut.sv:130.28-130.31" *)
  input Cin;
  wire Cin;
  (* src = "dut.sv:130.45-130.46" *)
  output S;
  wire S;
  (* src = "dut.sv:130.47-130.51" *)
  output Cout;
  wire Cout;
  wire _0_;
  wire _1_;
  wire _2_;
  \$_AND_  _3_ (
    .A(Cin),
    .B(A),
    .Y(_0_)
  );
  \$_XNOR_  _4_ (
    .A(Cin),
    .B(A),
    .Y(_1_)
  );
  \$_ANDNOT_  _5_ (
    .A(B),
    .B(_1_),
    .Y(_2_)
  );
  \$_OR_  _6_ (
    .A(_2_),
    .B(_0_),
    .Y(Cout)
  );
  \$_XNOR_  _7_ (
    .A(_1_),
    .B(B),
    .Y(S)
  );
endmodule

(* dynports =  1  *)
(* src = "dut.sv:77.1-107.10" *)
(* top =  1  *)
module Multiplier_2D(A, B, P);
  (* src = "dut.sv:78.15-78.16" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "dut.sv:79.15-79.16" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "dut.sv:80.18-80.19" *)
  output [7:0] P;
  wire [7:0] P;
  (* src = "dut.sv:82.16-82.18" *)
  wire [7:0] \PP[0] ;
  (* src = "dut.sv:82.16-82.18" *)
  wire [7:0] \PP[1] ;
  (* src = "dut.sv:82.16-82.18" *)
  wire [7:0] \PP[2] ;
  (* src = "dut.sv:82.16-82.18" *)
  wire [7:0] \PP[3] ;
  wire \addPartialProduct[1].Cout ;
  wire [4:0] \addPartialProduct[1].gA ;
  wire [3:0] \addPartialProduct[1].gB ;
  wire [4:0] \addPartialProduct[1].gS ;
  wire \addPartialProduct[2].Cout ;
  wire [5:0] \addPartialProduct[2].gA ;
  wire [5:0] \addPartialProduct[2].gB ;
  wire [5:0] \addPartialProduct[2].gS ;
  wire \addPartialProduct[3].Cout ;
  wire [6:0] \addPartialProduct[3].gA ;
  wire [6:0] \addPartialProduct[3].gB ;
  wire [6:0] \addPartialProduct[3].gS ;
  \$_AND_  _00_ (
    .A(B[0]),
    .B(A[2]),
    .Y(\addPartialProduct[1].gB [2])
  );
  \$_AND_  _01_ (
    .A(A[1]),
    .B(B[0]),
    .Y(\addPartialProduct[1].gB [1])
  );
  \$_AND_  _02_ (
    .A(A[0]),
    .B(B[0]),
    .Y(\addPartialProduct[1].gB [0])
  );
  \$_AND_  _03_ (
    .A(B[3]),
    .B(A[2]),
    .Y(\addPartialProduct[3].gA [5])
  );
  \$_AND_  _04_ (
    .A(B[3]),
    .B(A[1]),
    .Y(\addPartialProduct[3].gA [4])
  );
  \$_AND_  _05_ (
    .A(B[3]),
    .B(A[0]),
    .Y(\addPartialProduct[3].gA [3])
  );
  \$_AND_  _06_ (
    .A(B[2]),
    .B(A[2]),
    .Y(\addPartialProduct[2].gA [4])
  );
  \$_AND_  _07_ (
    .A(B[2]),
    .B(A[1]),
    .Y(\addPartialProduct[2].gA [3])
  );
  \$_AND_  _08_ (
    .A(B[2]),
    .B(A[0]),
    .Y(\addPartialProduct[2].gA [2])
  );
  \$_AND_  _09_ (
    .A(B[1]),
    .B(A[2]),
    .Y(\addPartialProduct[1].gA [3])
  );
  \$_AND_  _10_ (
    .A(B[1]),
    .B(A[1]),
    .Y(\addPartialProduct[1].gA [2])
  );
  \$_AND_  _11_ (
    .A(B[1]),
    .B(A[0]),
    .Y(\addPartialProduct[1].gA [1])
  );
  \$_AND_  _12_ (
    .A(A[3]),
    .B(B[2]),
    .Y(\addPartialProduct[2].gA [5])
  );
  \$_AND_  _13_ (
    .A(A[3]),
    .B(B[3]),
    .Y(\addPartialProduct[3].gA [6])
  );
  \$_AND_  _14_ (
    .A(A[3]),
    .B(B[0]),
    .Y(\addPartialProduct[1].gB [3])
  );
  \$_AND_  _15_ (
    .A(A[3]),
    .B(B[1]),
    .Y(\addPartialProduct[1].gA [4])
  );
  (* src = "dut.sv:100.5-101.56" *)
  \$paramod\RippleCarryAdder\N=s32'00000000000000000000000000000101  \addPartialProduct[1].adder  (
    .A({ \addPartialProduct[1].gA [4:1], 1'h0 }),
    .B({ 1'h0, \addPartialProduct[1].gB  }),
    .Cin(1'h0),
    .Cout(\addPartialProduct[1].Cout ),
    .S(\addPartialProduct[1].gS )
  );
  (* src = "dut.sv:100.5-101.56" *)
  \$paramod\RippleCarryAdder\N=s32'00000000000000000000000000000110  \addPartialProduct[2].adder  (
    .A({ \addPartialProduct[2].gA [5:2], 2'h0 }),
    .B({ \addPartialProduct[1].Cout , \addPartialProduct[1].gS  }),
    .Cin(1'h0),
    .Cout(\addPartialProduct[2].Cout ),
    .S(\addPartialProduct[2].gS )
  );
  (* src = "dut.sv:100.5-101.56" *)
  \$paramod\RippleCarryAdder\N=s32'00000000000000000000000000000111  \addPartialProduct[3].adder  (
    .A({ \addPartialProduct[3].gA [6:3], 3'h0 }),
    .B({ \addPartialProduct[2].Cout , \addPartialProduct[2].gS  }),
    .Cin(1'h0),
    .Cout(\addPartialProduct[3].Cout ),
    .S(\addPartialProduct[3].gS )
  );
  assign \addPartialProduct[2].gB  = { \addPartialProduct[1].Cout , \addPartialProduct[1].gS  };
  assign \addPartialProduct[2].gA [1:0] = 2'h0;
  assign \addPartialProduct[3].gA [2:0] = 3'h0;
  assign \addPartialProduct[3].gB  = { \addPartialProduct[2].Cout , \addPartialProduct[2].gS  };
  assign \addPartialProduct[1].gA [0] = 1'h0;
  assign \PP[3]  = { \addPartialProduct[3].Cout , \addPartialProduct[3].gS  };
  assign \PP[2]  = { 1'h0, \addPartialProduct[2].Cout , \addPartialProduct[2].gS  };
  assign \PP[1]  = { 2'h0, \addPartialProduct[1].Cout , \addPartialProduct[1].gS  };
  assign \PP[0]  = { 4'h0, \addPartialProduct[1].gB  };
  assign P = { \addPartialProduct[3].Cout , \addPartialProduct[3].gS  };
endmodule
