/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) */

(* dynports =  1  *)
(* src = "dut.sv:25.5-30.7" *)
(* hdlname = "submodule" *)
module \$paramod\submodule\WIDTH=s32'00000000000000000000000000001000 (a, b, c, out);
  (* src = "dut.sv:4.29-4.30" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "dut.sv:5.29-5.30" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "dut.sv:6.29-6.30" *)
  input [7:0] c;
  wire [7:0] c;
  (* src = "dut.sv:7.29-7.32" *)
  output [7:0] out;
  wire [7:0] out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  \$_AND_  _08_ (
    .A(c[6]),
    .B(a[6]),
    .Y(_00_)
  );
  \$_AND_  _09_ (
    .A(b[6]),
    .B(_00_),
    .Y(out[6])
  );
  \$_AND_  _10_ (
    .A(c[5]),
    .B(a[5]),
    .Y(_01_)
  );
  \$_AND_  _11_ (
    .A(b[5]),
    .B(_01_),
    .Y(out[5])
  );
  \$_AND_  _12_ (
    .A(c[4]),
    .B(a[4]),
    .Y(_02_)
  );
  \$_AND_  _13_ (
    .A(b[4]),
    .B(_02_),
    .Y(out[4])
  );
  \$_AND_  _14_ (
    .A(c[3]),
    .B(a[3]),
    .Y(_03_)
  );
  \$_AND_  _15_ (
    .A(b[3]),
    .B(_03_),
    .Y(out[3])
  );
  \$_AND_  _16_ (
    .A(c[2]),
    .B(a[2]),
    .Y(_04_)
  );
  \$_AND_  _17_ (
    .A(b[2]),
    .B(_04_),
    .Y(out[2])
  );
  \$_AND_  _18_ (
    .A(c[1]),
    .B(a[1]),
    .Y(_05_)
  );
  \$_AND_  _19_ (
    .A(b[1]),
    .B(_05_),
    .Y(out[1])
  );
  \$_AND_  _20_ (
    .A(c[0]),
    .B(a[0]),
    .Y(_06_)
  );
  \$_AND_  _21_ (
    .A(b[0]),
    .B(_06_),
    .Y(out[0])
  );
  \$_AND_  _22_ (
    .A(c[7]),
    .B(a[7]),
    .Y(_07_)
  );
  \$_AND_  _23_ (
    .A(b[7]),
    .B(_07_),
    .Y(out[7])
  );
endmodule

(* dynports =  1  *)
(* src = "dut.sv:41.5-46.7" *)
(* hdlname = "submodule" *)
module \$paramod\submodule\WIDTH=s32'00000000000000000000000000010000 (a, b, c, out);
  (* src = "dut.sv:4.29-4.30" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "dut.sv:5.29-5.30" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "dut.sv:6.29-6.30" *)
  input [15:0] c;
  wire [15:0] c;
  (* src = "dut.sv:7.29-7.32" *)
  output [15:0] out;
  wire [15:0] out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  \$_AND_  _16_ (
    .A(c[14]),
    .B(a[14]),
    .Y(_00_)
  );
  \$_AND_  _17_ (
    .A(b[14]),
    .B(_00_),
    .Y(out[14])
  );
  \$_AND_  _18_ (
    .A(c[13]),
    .B(a[13]),
    .Y(_01_)
  );
  \$_AND_  _19_ (
    .A(b[13]),
    .B(_01_),
    .Y(out[13])
  );
  \$_AND_  _20_ (
    .A(c[12]),
    .B(a[12]),
    .Y(_02_)
  );
  \$_AND_  _21_ (
    .A(b[12]),
    .B(_02_),
    .Y(out[12])
  );
  \$_AND_  _22_ (
    .A(c[11]),
    .B(a[11]),
    .Y(_03_)
  );
  \$_AND_  _23_ (
    .A(b[11]),
    .B(_03_),
    .Y(out[11])
  );
  \$_AND_  _24_ (
    .A(c[10]),
    .B(a[10]),
    .Y(_04_)
  );
  \$_AND_  _25_ (
    .A(b[10]),
    .B(_04_),
    .Y(out[10])
  );
  \$_AND_  _26_ (
    .A(c[9]),
    .B(a[9]),
    .Y(_05_)
  );
  \$_AND_  _27_ (
    .A(b[9]),
    .B(_05_),
    .Y(out[9])
  );
  \$_AND_  _28_ (
    .A(c[8]),
    .B(a[8]),
    .Y(_06_)
  );
  \$_AND_  _29_ (
    .A(b[8]),
    .B(_06_),
    .Y(out[8])
  );
  \$_AND_  _30_ (
    .A(c[7]),
    .B(a[7]),
    .Y(_07_)
  );
  \$_AND_  _31_ (
    .A(b[7]),
    .B(_07_),
    .Y(out[7])
  );
  \$_AND_  _32_ (
    .A(c[6]),
    .B(a[6]),
    .Y(_08_)
  );
  \$_AND_  _33_ (
    .A(b[6]),
    .B(_08_),
    .Y(out[6])
  );
  \$_AND_  _34_ (
    .A(c[5]),
    .B(a[5]),
    .Y(_09_)
  );
  \$_AND_  _35_ (
    .A(b[5]),
    .B(_09_),
    .Y(out[5])
  );
  \$_AND_  _36_ (
    .A(c[4]),
    .B(a[4]),
    .Y(_10_)
  );
  \$_AND_  _37_ (
    .A(b[4]),
    .B(_10_),
    .Y(out[4])
  );
  \$_AND_  _38_ (
    .A(c[3]),
    .B(a[3]),
    .Y(_11_)
  );
  \$_AND_  _39_ (
    .A(b[3]),
    .B(_11_),
    .Y(out[3])
  );
  \$_AND_  _40_ (
    .A(c[2]),
    .B(a[2]),
    .Y(_12_)
  );
  \$_AND_  _41_ (
    .A(b[2]),
    .B(_12_),
    .Y(out[2])
  );
  \$_AND_  _42_ (
    .A(c[1]),
    .B(a[1]),
    .Y(_13_)
  );
  \$_AND_  _43_ (
    .A(b[1]),
    .B(_13_),
    .Y(out[1])
  );
  \$_AND_  _44_ (
    .A(c[0]),
    .B(a[0]),
    .Y(_14_)
  );
  \$_AND_  _45_ (
    .A(b[0]),
    .B(_14_),
    .Y(out[0])
  );
  \$_AND_  _46_ (
    .A(c[15]),
    .B(a[15]),
    .Y(_15_)
  );
  \$_AND_  _47_ (
    .A(b[15]),
    .B(_15_),
    .Y(out[15])
  );
endmodule

(* src = "dut.sv:15.1-48.10" *)
(* top =  1  *)
module simple_hierarchy(a1, b1, c1, a2, b2, c2, a3, b3, c3, out1, out2, out3);
  (* src = "dut.sv:16.24-16.26" *)
  input [7:0] a1;
  wire [7:0] a1;
  (* src = "dut.sv:16.28-16.30" *)
  input [7:0] b1;
  wire [7:0] b1;
  (* src = "dut.sv:16.32-16.34" *)
  input [7:0] c1;
  wire [7:0] c1;
  (* src = "dut.sv:17.24-17.26" *)
  input [7:0] a2;
  wire [7:0] a2;
  (* src = "dut.sv:17.28-17.30" *)
  input [7:0] b2;
  wire [7:0] b2;
  (* src = "dut.sv:17.32-17.34" *)
  input [7:0] c2;
  wire [7:0] c2;
  (* src = "dut.sv:18.24-18.26" *)
  input [15:0] a3;
  wire [15:0] a3;
  (* src = "dut.sv:18.28-18.30" *)
  input [15:0] b3;
  wire [15:0] b3;
  (* src = "dut.sv:18.32-18.34" *)
  input [15:0] c3;
  wire [15:0] c3;
  (* src = "dut.sv:19.24-19.28" *)
  output [7:0] out1;
  wire [7:0] out1;
  (* src = "dut.sv:20.24-20.28" *)
  output [7:0] out2;
  wire [7:0] out2;
  (* src = "dut.sv:21.24-21.28" *)
  output [15:0] out3;
  wire [15:0] out3;
  \$paramod\submodule\WIDTH=s32'00000000000000000000000000001000  inst1 (
    .a(a1),
    .b(b1),
    .c(c1),
    .out(out1)
  );
  \$paramod\submodule\WIDTH=s32'00000000000000000000000000001000  inst2 (
    .a(a2),
    .b(b2),
    .c(c2),
    .out(out2)
  );
  \$paramod\submodule\WIDTH=s32'00000000000000000000000000010000  inst3 (
    .a(a3),
    .b(b3),
    .c(c3),
    .out(out3)
  );
endmodule
