/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:1.1-11.10" *)
(* top =  1  *)
module top(a, b);
  (* src = "dut.sv:1.23-1.24" *)
  output signed [31:0] a;
  wire signed [31:0] a;
  (* src = "dut.sv:1.37-1.38" *)
  output signed [31:0] b;
  wire signed [31:0] b;
  assign b = 32'd50;
  assign a = 32'd110;
endmodule
