/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:15.1-23.10" *)
(* top =  1  *)
module iface_array_internal_assign(v0, r0, v1, r1, o0, o1);
  (* src = "dut.sv:16.16-16.18" *)
  input v0;
  wire v0;
  (* src = "dut.sv:16.32-16.34" *)
  input r0;
  wire r0;
  (* src = "dut.sv:16.48-16.50" *)
  input v1;
  wire v1;
  (* src = "dut.sv:16.64-16.66" *)
  input r1;
  wire r1;
  (* src = "dut.sv:17.17-17.19" *)
  output o0;
  wire o0;
  (* src = "dut.sv:17.34-17.36" *)
  output o1;
  wire o1;
  (* src = "dut.sv:6.14-6.17" *)
  wire \s[0].rdy ;
  (* src = "dut.sv:6.19-6.22" *)
  wire \s[0].trn ;
  (* src = "dut.sv:6.9-6.12" *)
  wire \s[0].vld ;
  (* src = "dut.sv:6.14-6.17" *)
  wire \s[1].rdy ;
  (* src = "dut.sv:6.19-6.22" *)
  wire \s[1].trn ;
  (* src = "dut.sv:6.9-6.12" *)
  wire \s[1].vld ;
  \$_AND_  _0_ (
    .A(v1),
    .B(r1),
    .Y(\s[1].trn )
  );
  \$_AND_  _1_ (
    .A(v0),
    .B(r0),
    .Y(\s[0].trn )
  );
  sink u0 (
    .o(o0),
    .trn(\s[0].trn )
  );
  sink u1 (
    .o(o1),
    .trn(\s[1].trn )
  );
  assign \s[1].rdy  = r1;
  assign \s[1].vld  = v1;
  assign \s[0].rdy  = r0;
  assign \s[0].vld  = v0;
endmodule

(* src = "dut.sv:11.1-13.10" *)
module sink(trn, o);
  (* src = "dut.sv:11.26-11.29" *)
  input trn;
  wire trn;
  (* src = "dut.sv:11.44-11.45" *)
  output o;
  wire o;
  assign o = trn;
endmodule
