/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:6.1-12.10" *)
(* top =  1  *)
module top();
  (* src = "dut.sv:7.5-7.11" *)
  wire signed [31:0] a;
  (* src = "dut.sv:8.5-8.10" *)
  wire signed [31:0] b;
  assign b = 32'd5;
  assign a = 32'd12;
endmodule
