/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "dut.sv:1.1-20.10" *)
module simple_memory_noreset(clk, we, addr, data_in, data_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  (* src = "dut.sv:4.24-4.28" *)
  input [3:0] addr;
  wire [3:0] addr;
  (* src = "dut.sv:2.24-2.27" *)
  input clk;
  wire clk;
  (* src = "dut.sv:5.24-5.31" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "dut.sv:6.24-6.32" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  wire [7:0] \memory[0] ;
  wire [7:0] \memory[10] ;
  wire [7:0] \memory[11] ;
  wire [7:0] \memory[12] ;
  wire [7:0] \memory[13] ;
  wire [7:0] \memory[14] ;
  wire [7:0] \memory[15] ;
  wire [7:0] \memory[1] ;
  wire [7:0] \memory[2] ;
  wire [7:0] \memory[3] ;
  wire [7:0] \memory[4] ;
  wire [7:0] \memory[5] ;
  wire [7:0] \memory[6] ;
  wire [7:0] \memory[7] ;
  wire [7:0] \memory[8] ;
  wire [7:0] \memory[9] ;
  wire [7:0] memrd_memory_DATA;
  (* src = "dut.sv:3.24-3.26" *)
  input we;
  wire we;
  \$_MUX_  _152_ (
    .A(\memory[0] [0]),
    .B(\memory[1] [0]),
    .S(addr[0]),
    .Y(_016_)
  );
  \$_MUX_  _153_ (
    .A(\memory[2] [0]),
    .B(\memory[3] [0]),
    .S(addr[0]),
    .Y(_017_)
  );
  \$_MUX_  _154_ (
    .A(_016_),
    .B(_017_),
    .S(addr[1]),
    .Y(_018_)
  );
  \$_MUX_  _155_ (
    .A(\memory[4] [0]),
    .B(\memory[5] [0]),
    .S(addr[0]),
    .Y(_019_)
  );
  \$_MUX_  _156_ (
    .A(\memory[6] [0]),
    .B(\memory[7] [0]),
    .S(addr[0]),
    .Y(_020_)
  );
  \$_MUX_  _157_ (
    .A(_019_),
    .B(_020_),
    .S(addr[1]),
    .Y(_021_)
  );
  \$_MUX_  _158_ (
    .A(_018_),
    .B(_021_),
    .S(addr[2]),
    .Y(_022_)
  );
  \$_MUX_  _159_ (
    .A(\memory[8] [0]),
    .B(\memory[9] [0]),
    .S(addr[0]),
    .Y(_023_)
  );
  \$_MUX_  _160_ (
    .A(\memory[10] [0]),
    .B(\memory[11] [0]),
    .S(addr[0]),
    .Y(_024_)
  );
  \$_MUX_  _161_ (
    .A(_023_),
    .B(_024_),
    .S(addr[1]),
    .Y(_025_)
  );
  \$_MUX_  _162_ (
    .A(\memory[12] [0]),
    .B(\memory[13] [0]),
    .S(addr[0]),
    .Y(_026_)
  );
  \$_MUX_  _163_ (
    .A(\memory[14] [0]),
    .B(\memory[15] [0]),
    .S(addr[0]),
    .Y(_027_)
  );
  \$_MUX_  _164_ (
    .A(_026_),
    .B(_027_),
    .S(addr[1]),
    .Y(_028_)
  );
  \$_MUX_  _165_ (
    .A(_025_),
    .B(_028_),
    .S(addr[2]),
    .Y(_029_)
  );
  \$_MUX_  _166_ (
    .A(_022_),
    .B(_029_),
    .S(addr[3]),
    .Y(data_out[0])
  );
  \$_MUX_  _167_ (
    .A(\memory[0] [1]),
    .B(\memory[1] [1]),
    .S(addr[0]),
    .Y(_030_)
  );
  \$_MUX_  _168_ (
    .A(\memory[2] [1]),
    .B(\memory[3] [1]),
    .S(addr[0]),
    .Y(_031_)
  );
  \$_MUX_  _169_ (
    .A(_030_),
    .B(_031_),
    .S(addr[1]),
    .Y(_032_)
  );
  \$_MUX_  _170_ (
    .A(\memory[4] [1]),
    .B(\memory[5] [1]),
    .S(addr[0]),
    .Y(_033_)
  );
  \$_MUX_  _171_ (
    .A(\memory[6] [1]),
    .B(\memory[7] [1]),
    .S(addr[0]),
    .Y(_034_)
  );
  \$_MUX_  _172_ (
    .A(_033_),
    .B(_034_),
    .S(addr[1]),
    .Y(_035_)
  );
  \$_MUX_  _173_ (
    .A(_032_),
    .B(_035_),
    .S(addr[2]),
    .Y(_036_)
  );
  \$_MUX_  _174_ (
    .A(\memory[8] [1]),
    .B(\memory[9] [1]),
    .S(addr[0]),
    .Y(_037_)
  );
  \$_MUX_  _175_ (
    .A(\memory[10] [1]),
    .B(\memory[11] [1]),
    .S(addr[0]),
    .Y(_038_)
  );
  \$_MUX_  _176_ (
    .A(_037_),
    .B(_038_),
    .S(addr[1]),
    .Y(_039_)
  );
  \$_MUX_  _177_ (
    .A(\memory[12] [1]),
    .B(\memory[13] [1]),
    .S(addr[0]),
    .Y(_040_)
  );
  \$_MUX_  _178_ (
    .A(\memory[14] [1]),
    .B(\memory[15] [1]),
    .S(addr[0]),
    .Y(_041_)
  );
  \$_MUX_  _179_ (
    .A(_040_),
    .B(_041_),
    .S(addr[1]),
    .Y(_042_)
  );
  \$_MUX_  _180_ (
    .A(_039_),
    .B(_042_),
    .S(addr[2]),
    .Y(_043_)
  );
  \$_MUX_  _181_ (
    .A(_036_),
    .B(_043_),
    .S(addr[3]),
    .Y(data_out[1])
  );
  \$_MUX_  _182_ (
    .A(\memory[0] [2]),
    .B(\memory[1] [2]),
    .S(addr[0]),
    .Y(_044_)
  );
  \$_MUX_  _183_ (
    .A(\memory[2] [2]),
    .B(\memory[3] [2]),
    .S(addr[0]),
    .Y(_045_)
  );
  \$_MUX_  _184_ (
    .A(_044_),
    .B(_045_),
    .S(addr[1]),
    .Y(_046_)
  );
  \$_MUX_  _185_ (
    .A(\memory[4] [2]),
    .B(\memory[5] [2]),
    .S(addr[0]),
    .Y(_047_)
  );
  \$_MUX_  _186_ (
    .A(\memory[6] [2]),
    .B(\memory[7] [2]),
    .S(addr[0]),
    .Y(_048_)
  );
  \$_MUX_  _187_ (
    .A(_047_),
    .B(_048_),
    .S(addr[1]),
    .Y(_049_)
  );
  \$_MUX_  _188_ (
    .A(_046_),
    .B(_049_),
    .S(addr[2]),
    .Y(_050_)
  );
  \$_MUX_  _189_ (
    .A(\memory[8] [2]),
    .B(\memory[9] [2]),
    .S(addr[0]),
    .Y(_051_)
  );
  \$_MUX_  _190_ (
    .A(\memory[10] [2]),
    .B(\memory[11] [2]),
    .S(addr[0]),
    .Y(_052_)
  );
  \$_MUX_  _191_ (
    .A(_051_),
    .B(_052_),
    .S(addr[1]),
    .Y(_053_)
  );
  \$_MUX_  _192_ (
    .A(\memory[12] [2]),
    .B(\memory[13] [2]),
    .S(addr[0]),
    .Y(_054_)
  );
  \$_MUX_  _193_ (
    .A(\memory[14] [2]),
    .B(\memory[15] [2]),
    .S(addr[0]),
    .Y(_055_)
  );
  \$_MUX_  _194_ (
    .A(_054_),
    .B(_055_),
    .S(addr[1]),
    .Y(_056_)
  );
  \$_MUX_  _195_ (
    .A(_053_),
    .B(_056_),
    .S(addr[2]),
    .Y(_057_)
  );
  \$_MUX_  _196_ (
    .A(_050_),
    .B(_057_),
    .S(addr[3]),
    .Y(data_out[2])
  );
  \$_MUX_  _197_ (
    .A(\memory[0] [3]),
    .B(\memory[1] [3]),
    .S(addr[0]),
    .Y(_058_)
  );
  \$_MUX_  _198_ (
    .A(\memory[2] [3]),
    .B(\memory[3] [3]),
    .S(addr[0]),
    .Y(_059_)
  );
  \$_MUX_  _199_ (
    .A(_058_),
    .B(_059_),
    .S(addr[1]),
    .Y(_060_)
  );
  \$_MUX_  _200_ (
    .A(\memory[4] [3]),
    .B(\memory[5] [3]),
    .S(addr[0]),
    .Y(_061_)
  );
  \$_MUX_  _201_ (
    .A(\memory[6] [3]),
    .B(\memory[7] [3]),
    .S(addr[0]),
    .Y(_062_)
  );
  \$_MUX_  _202_ (
    .A(_061_),
    .B(_062_),
    .S(addr[1]),
    .Y(_063_)
  );
  \$_MUX_  _203_ (
    .A(_060_),
    .B(_063_),
    .S(addr[2]),
    .Y(_064_)
  );
  \$_MUX_  _204_ (
    .A(\memory[8] [3]),
    .B(\memory[9] [3]),
    .S(addr[0]),
    .Y(_065_)
  );
  \$_MUX_  _205_ (
    .A(\memory[10] [3]),
    .B(\memory[11] [3]),
    .S(addr[0]),
    .Y(_066_)
  );
  \$_MUX_  _206_ (
    .A(_065_),
    .B(_066_),
    .S(addr[1]),
    .Y(_067_)
  );
  \$_MUX_  _207_ (
    .A(\memory[12] [3]),
    .B(\memory[13] [3]),
    .S(addr[0]),
    .Y(_068_)
  );
  \$_MUX_  _208_ (
    .A(\memory[14] [3]),
    .B(\memory[15] [3]),
    .S(addr[0]),
    .Y(_069_)
  );
  \$_MUX_  _209_ (
    .A(_068_),
    .B(_069_),
    .S(addr[1]),
    .Y(_070_)
  );
  \$_MUX_  _210_ (
    .A(_067_),
    .B(_070_),
    .S(addr[2]),
    .Y(_071_)
  );
  \$_MUX_  _211_ (
    .A(_064_),
    .B(_071_),
    .S(addr[3]),
    .Y(data_out[3])
  );
  \$_MUX_  _212_ (
    .A(\memory[0] [4]),
    .B(\memory[1] [4]),
    .S(addr[0]),
    .Y(_072_)
  );
  \$_MUX_  _213_ (
    .A(\memory[2] [4]),
    .B(\memory[3] [4]),
    .S(addr[0]),
    .Y(_073_)
  );
  \$_MUX_  _214_ (
    .A(_072_),
    .B(_073_),
    .S(addr[1]),
    .Y(_074_)
  );
  \$_MUX_  _215_ (
    .A(\memory[4] [4]),
    .B(\memory[5] [4]),
    .S(addr[0]),
    .Y(_075_)
  );
  \$_MUX_  _216_ (
    .A(\memory[6] [4]),
    .B(\memory[7] [4]),
    .S(addr[0]),
    .Y(_076_)
  );
  \$_MUX_  _217_ (
    .A(_075_),
    .B(_076_),
    .S(addr[1]),
    .Y(_077_)
  );
  \$_MUX_  _218_ (
    .A(_074_),
    .B(_077_),
    .S(addr[2]),
    .Y(_078_)
  );
  \$_MUX_  _219_ (
    .A(\memory[8] [4]),
    .B(\memory[9] [4]),
    .S(addr[0]),
    .Y(_079_)
  );
  \$_MUX_  _220_ (
    .A(\memory[10] [4]),
    .B(\memory[11] [4]),
    .S(addr[0]),
    .Y(_080_)
  );
  \$_MUX_  _221_ (
    .A(_079_),
    .B(_080_),
    .S(addr[1]),
    .Y(_081_)
  );
  \$_MUX_  _222_ (
    .A(\memory[12] [4]),
    .B(\memory[13] [4]),
    .S(addr[0]),
    .Y(_082_)
  );
  \$_MUX_  _223_ (
    .A(\memory[14] [4]),
    .B(\memory[15] [4]),
    .S(addr[0]),
    .Y(_083_)
  );
  \$_MUX_  _224_ (
    .A(_082_),
    .B(_083_),
    .S(addr[1]),
    .Y(_084_)
  );
  \$_MUX_  _225_ (
    .A(_081_),
    .B(_084_),
    .S(addr[2]),
    .Y(_085_)
  );
  \$_MUX_  _226_ (
    .A(_078_),
    .B(_085_),
    .S(addr[3]),
    .Y(data_out[4])
  );
  \$_MUX_  _227_ (
    .A(\memory[0] [5]),
    .B(\memory[1] [5]),
    .S(addr[0]),
    .Y(_086_)
  );
  \$_MUX_  _228_ (
    .A(\memory[2] [5]),
    .B(\memory[3] [5]),
    .S(addr[0]),
    .Y(_087_)
  );
  \$_MUX_  _229_ (
    .A(_086_),
    .B(_087_),
    .S(addr[1]),
    .Y(_088_)
  );
  \$_MUX_  _230_ (
    .A(\memory[4] [5]),
    .B(\memory[5] [5]),
    .S(addr[0]),
    .Y(_089_)
  );
  \$_MUX_  _231_ (
    .A(\memory[6] [5]),
    .B(\memory[7] [5]),
    .S(addr[0]),
    .Y(_090_)
  );
  \$_MUX_  _232_ (
    .A(_089_),
    .B(_090_),
    .S(addr[1]),
    .Y(_091_)
  );
  \$_MUX_  _233_ (
    .A(_088_),
    .B(_091_),
    .S(addr[2]),
    .Y(_092_)
  );
  \$_MUX_  _234_ (
    .A(\memory[8] [5]),
    .B(\memory[9] [5]),
    .S(addr[0]),
    .Y(_093_)
  );
  \$_MUX_  _235_ (
    .A(\memory[10] [5]),
    .B(\memory[11] [5]),
    .S(addr[0]),
    .Y(_094_)
  );
  \$_MUX_  _236_ (
    .A(_093_),
    .B(_094_),
    .S(addr[1]),
    .Y(_095_)
  );
  \$_MUX_  _237_ (
    .A(\memory[12] [5]),
    .B(\memory[13] [5]),
    .S(addr[0]),
    .Y(_096_)
  );
  \$_MUX_  _238_ (
    .A(\memory[14] [5]),
    .B(\memory[15] [5]),
    .S(addr[0]),
    .Y(_097_)
  );
  \$_MUX_  _239_ (
    .A(_096_),
    .B(_097_),
    .S(addr[1]),
    .Y(_098_)
  );
  \$_MUX_  _240_ (
    .A(_095_),
    .B(_098_),
    .S(addr[2]),
    .Y(_099_)
  );
  \$_MUX_  _241_ (
    .A(_092_),
    .B(_099_),
    .S(addr[3]),
    .Y(data_out[5])
  );
  \$_MUX_  _242_ (
    .A(\memory[0] [6]),
    .B(\memory[1] [6]),
    .S(addr[0]),
    .Y(_100_)
  );
  \$_MUX_  _243_ (
    .A(\memory[2] [6]),
    .B(\memory[3] [6]),
    .S(addr[0]),
    .Y(_101_)
  );
  \$_MUX_  _244_ (
    .A(_100_),
    .B(_101_),
    .S(addr[1]),
    .Y(_102_)
  );
  \$_MUX_  _245_ (
    .A(\memory[4] [6]),
    .B(\memory[5] [6]),
    .S(addr[0]),
    .Y(_103_)
  );
  \$_MUX_  _246_ (
    .A(\memory[6] [6]),
    .B(\memory[7] [6]),
    .S(addr[0]),
    .Y(_104_)
  );
  \$_MUX_  _247_ (
    .A(_103_),
    .B(_104_),
    .S(addr[1]),
    .Y(_105_)
  );
  \$_MUX_  _248_ (
    .A(_102_),
    .B(_105_),
    .S(addr[2]),
    .Y(_106_)
  );
  \$_MUX_  _249_ (
    .A(\memory[8] [6]),
    .B(\memory[9] [6]),
    .S(addr[0]),
    .Y(_107_)
  );
  \$_MUX_  _250_ (
    .A(\memory[10] [6]),
    .B(\memory[11] [6]),
    .S(addr[0]),
    .Y(_108_)
  );
  \$_MUX_  _251_ (
    .A(_107_),
    .B(_108_),
    .S(addr[1]),
    .Y(_109_)
  );
  \$_MUX_  _252_ (
    .A(\memory[12] [6]),
    .B(\memory[13] [6]),
    .S(addr[0]),
    .Y(_110_)
  );
  \$_MUX_  _253_ (
    .A(\memory[14] [6]),
    .B(\memory[15] [6]),
    .S(addr[0]),
    .Y(_111_)
  );
  \$_MUX_  _254_ (
    .A(_110_),
    .B(_111_),
    .S(addr[1]),
    .Y(_112_)
  );
  \$_MUX_  _255_ (
    .A(_109_),
    .B(_112_),
    .S(addr[2]),
    .Y(_113_)
  );
  \$_MUX_  _256_ (
    .A(_106_),
    .B(_113_),
    .S(addr[3]),
    .Y(data_out[6])
  );
  \$_MUX_  _257_ (
    .A(\memory[0] [7]),
    .B(\memory[1] [7]),
    .S(addr[0]),
    .Y(_114_)
  );
  \$_MUX_  _258_ (
    .A(\memory[2] [7]),
    .B(\memory[3] [7]),
    .S(addr[0]),
    .Y(_115_)
  );
  \$_MUX_  _259_ (
    .A(_114_),
    .B(_115_),
    .S(addr[1]),
    .Y(_116_)
  );
  \$_MUX_  _260_ (
    .A(\memory[4] [7]),
    .B(\memory[5] [7]),
    .S(addr[0]),
    .Y(_117_)
  );
  \$_MUX_  _261_ (
    .A(\memory[6] [7]),
    .B(\memory[7] [7]),
    .S(addr[0]),
    .Y(_118_)
  );
  \$_MUX_  _262_ (
    .A(_117_),
    .B(_118_),
    .S(addr[1]),
    .Y(_119_)
  );
  \$_MUX_  _263_ (
    .A(_116_),
    .B(_119_),
    .S(addr[2]),
    .Y(_120_)
  );
  \$_MUX_  _264_ (
    .A(\memory[8] [7]),
    .B(\memory[9] [7]),
    .S(addr[0]),
    .Y(_121_)
  );
  \$_MUX_  _265_ (
    .A(\memory[10] [7]),
    .B(\memory[11] [7]),
    .S(addr[0]),
    .Y(_122_)
  );
  \$_MUX_  _266_ (
    .A(_121_),
    .B(_122_),
    .S(addr[1]),
    .Y(_123_)
  );
  \$_MUX_  _267_ (
    .A(\memory[12] [7]),
    .B(\memory[13] [7]),
    .S(addr[0]),
    .Y(_124_)
  );
  \$_MUX_  _268_ (
    .A(\memory[14] [7]),
    .B(\memory[15] [7]),
    .S(addr[0]),
    .Y(_125_)
  );
  \$_MUX_  _269_ (
    .A(_124_),
    .B(_125_),
    .S(addr[1]),
    .Y(_126_)
  );
  \$_MUX_  _270_ (
    .A(_123_),
    .B(_126_),
    .S(addr[2]),
    .Y(_127_)
  );
  \$_MUX_  _271_ (
    .A(_120_),
    .B(_127_),
    .S(addr[3]),
    .Y(data_out[7])
  );
  \$_OR_  _272_ (
    .A(addr[0]),
    .B(addr[1]),
    .Y(_128_)
  );
  \$_OR_  _273_ (
    .A(addr[2]),
    .B(addr[3]),
    .Y(_129_)
  );
  \$_OR_  _274_ (
    .A(_129_),
    .B(_128_),
    .Y(_130_)
  );
  \$_ANDNOT_  _275_ (
    .A(we),
    .B(_130_),
    .Y(_000_)
  );
  \$_ORNOT_  _276_ (
    .A(addr[1]),
    .B(addr[0]),
    .Y(_131_)
  );
  \$_OR_  _277_ (
    .A(_131_),
    .B(_129_),
    .Y(_132_)
  );
  \$_ANDNOT_  _278_ (
    .A(we),
    .B(_132_),
    .Y(_007_)
  );
  \$_ORNOT_  _279_ (
    .A(addr[0]),
    .B(addr[1]),
    .Y(_133_)
  );
  \$_OR_  _280_ (
    .A(_133_),
    .B(_129_),
    .Y(_134_)
  );
  \$_ANDNOT_  _281_ (
    .A(we),
    .B(_134_),
    .Y(_008_)
  );
  \$_NAND_  _282_ (
    .A(addr[0]),
    .B(addr[1]),
    .Y(_135_)
  );
  \$_OR_  _283_ (
    .A(_135_),
    .B(_129_),
    .Y(_136_)
  );
  \$_ANDNOT_  _284_ (
    .A(we),
    .B(_136_),
    .Y(_009_)
  );
  \$_ORNOT_  _285_ (
    .A(addr[3]),
    .B(addr[2]),
    .Y(_137_)
  );
  \$_OR_  _286_ (
    .A(_137_),
    .B(_128_),
    .Y(_138_)
  );
  \$_ANDNOT_  _287_ (
    .A(we),
    .B(_138_),
    .Y(_010_)
  );
  \$_OR_  _288_ (
    .A(_137_),
    .B(_131_),
    .Y(_139_)
  );
  \$_ANDNOT_  _289_ (
    .A(we),
    .B(_139_),
    .Y(_011_)
  );
  \$_OR_  _290_ (
    .A(_137_),
    .B(_133_),
    .Y(_140_)
  );
  \$_ANDNOT_  _291_ (
    .A(we),
    .B(_140_),
    .Y(_012_)
  );
  \$_OR_  _292_ (
    .A(_137_),
    .B(_135_),
    .Y(_141_)
  );
  \$_ANDNOT_  _293_ (
    .A(we),
    .B(_141_),
    .Y(_013_)
  );
  \$_ORNOT_  _294_ (
    .A(addr[2]),
    .B(addr[3]),
    .Y(_142_)
  );
  \$_OR_  _295_ (
    .A(_142_),
    .B(_128_),
    .Y(_143_)
  );
  \$_ANDNOT_  _296_ (
    .A(we),
    .B(_143_),
    .Y(_014_)
  );
  \$_OR_  _297_ (
    .A(_142_),
    .B(_131_),
    .Y(_144_)
  );
  \$_ANDNOT_  _298_ (
    .A(we),
    .B(_144_),
    .Y(_015_)
  );
  \$_OR_  _299_ (
    .A(_142_),
    .B(_133_),
    .Y(_145_)
  );
  \$_ANDNOT_  _300_ (
    .A(we),
    .B(_145_),
    .Y(_001_)
  );
  \$_OR_  _301_ (
    .A(_142_),
    .B(_135_),
    .Y(_146_)
  );
  \$_ANDNOT_  _302_ (
    .A(we),
    .B(_146_),
    .Y(_002_)
  );
  \$_NAND_  _303_ (
    .A(addr[2]),
    .B(addr[3]),
    .Y(_147_)
  );
  \$_OR_  _304_ (
    .A(_147_),
    .B(_128_),
    .Y(_148_)
  );
  \$_ANDNOT_  _305_ (
    .A(we),
    .B(_148_),
    .Y(_003_)
  );
  \$_OR_  _306_ (
    .A(_147_),
    .B(_131_),
    .Y(_149_)
  );
  \$_ANDNOT_  _307_ (
    .A(we),
    .B(_149_),
    .Y(_004_)
  );
  \$_OR_  _308_ (
    .A(_147_),
    .B(_133_),
    .Y(_150_)
  );
  \$_ANDNOT_  _309_ (
    .A(we),
    .B(_150_),
    .Y(_005_)
  );
  \$_OR_  _310_ (
    .A(_147_),
    .B(_135_),
    .Y(_151_)
  );
  \$_ANDNOT_  _311_ (
    .A(we),
    .B(_151_),
    .Y(_006_)
  );
  \$_DFFE_PP_  \memory_reg[3][0]  /* _312_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_009_),
    .Q(\memory[3] [0])
  );
  \$_DFFE_PP_  \memory_reg[3][1]  /* _313_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_009_),
    .Q(\memory[3] [1])
  );
  \$_DFFE_PP_  \memory_reg[3][2]  /* _314_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_009_),
    .Q(\memory[3] [2])
  );
  \$_DFFE_PP_  \memory_reg[3][3]  /* _315_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_009_),
    .Q(\memory[3] [3])
  );
  \$_DFFE_PP_  \memory_reg[3][4]  /* _316_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_009_),
    .Q(\memory[3] [4])
  );
  \$_DFFE_PP_  \memory_reg[3][5]  /* _317_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_009_),
    .Q(\memory[3] [5])
  );
  \$_DFFE_PP_  \memory_reg[3][6]  /* _318_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_009_),
    .Q(\memory[3] [6])
  );
  \$_DFFE_PP_  \memory_reg[3][7]  /* _319_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_009_),
    .Q(\memory[3] [7])
  );
  \$_DFFE_PP_  \memory_reg[2][0]  /* _320_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_008_),
    .Q(\memory[2] [0])
  );
  \$_DFFE_PP_  \memory_reg[2][1]  /* _321_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_008_),
    .Q(\memory[2] [1])
  );
  \$_DFFE_PP_  \memory_reg[2][2]  /* _322_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_008_),
    .Q(\memory[2] [2])
  );
  \$_DFFE_PP_  \memory_reg[2][3]  /* _323_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_008_),
    .Q(\memory[2] [3])
  );
  \$_DFFE_PP_  \memory_reg[2][4]  /* _324_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_008_),
    .Q(\memory[2] [4])
  );
  \$_DFFE_PP_  \memory_reg[2][5]  /* _325_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_008_),
    .Q(\memory[2] [5])
  );
  \$_DFFE_PP_  \memory_reg[2][6]  /* _326_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_008_),
    .Q(\memory[2] [6])
  );
  \$_DFFE_PP_  \memory_reg[2][7]  /* _327_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_008_),
    .Q(\memory[2] [7])
  );
  \$_DFFE_PP_  \memory_reg[15][0]  /* _328_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_006_),
    .Q(\memory[15] [0])
  );
  \$_DFFE_PP_  \memory_reg[15][1]  /* _329_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_006_),
    .Q(\memory[15] [1])
  );
  \$_DFFE_PP_  \memory_reg[15][2]  /* _330_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_006_),
    .Q(\memory[15] [2])
  );
  \$_DFFE_PP_  \memory_reg[15][3]  /* _331_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_006_),
    .Q(\memory[15] [3])
  );
  \$_DFFE_PP_  \memory_reg[15][4]  /* _332_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_006_),
    .Q(\memory[15] [4])
  );
  \$_DFFE_PP_  \memory_reg[15][5]  /* _333_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_006_),
    .Q(\memory[15] [5])
  );
  \$_DFFE_PP_  \memory_reg[15][6]  /* _334_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_006_),
    .Q(\memory[15] [6])
  );
  \$_DFFE_PP_  \memory_reg[15][7]  /* _335_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_006_),
    .Q(\memory[15] [7])
  );
  \$_DFFE_PP_  \memory_reg[1][0]  /* _336_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_007_),
    .Q(\memory[1] [0])
  );
  \$_DFFE_PP_  \memory_reg[1][1]  /* _337_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_007_),
    .Q(\memory[1] [1])
  );
  \$_DFFE_PP_  \memory_reg[1][2]  /* _338_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_007_),
    .Q(\memory[1] [2])
  );
  \$_DFFE_PP_  \memory_reg[1][3]  /* _339_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_007_),
    .Q(\memory[1] [3])
  );
  \$_DFFE_PP_  \memory_reg[1][4]  /* _340_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_007_),
    .Q(\memory[1] [4])
  );
  \$_DFFE_PP_  \memory_reg[1][5]  /* _341_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_007_),
    .Q(\memory[1] [5])
  );
  \$_DFFE_PP_  \memory_reg[1][6]  /* _342_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_007_),
    .Q(\memory[1] [6])
  );
  \$_DFFE_PP_  \memory_reg[1][7]  /* _343_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_007_),
    .Q(\memory[1] [7])
  );
  \$_DFFE_PP_  \memory_reg[4][0]  /* _344_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_010_),
    .Q(\memory[4] [0])
  );
  \$_DFFE_PP_  \memory_reg[4][1]  /* _345_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_010_),
    .Q(\memory[4] [1])
  );
  \$_DFFE_PP_  \memory_reg[4][2]  /* _346_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_010_),
    .Q(\memory[4] [2])
  );
  \$_DFFE_PP_  \memory_reg[4][3]  /* _347_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_010_),
    .Q(\memory[4] [3])
  );
  \$_DFFE_PP_  \memory_reg[4][4]  /* _348_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_010_),
    .Q(\memory[4] [4])
  );
  \$_DFFE_PP_  \memory_reg[4][5]  /* _349_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_010_),
    .Q(\memory[4] [5])
  );
  \$_DFFE_PP_  \memory_reg[4][6]  /* _350_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_010_),
    .Q(\memory[4] [6])
  );
  \$_DFFE_PP_  \memory_reg[4][7]  /* _351_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_010_),
    .Q(\memory[4] [7])
  );
  \$_DFFE_PP_  \memory_reg[5][0]  /* _352_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_011_),
    .Q(\memory[5] [0])
  );
  \$_DFFE_PP_  \memory_reg[5][1]  /* _353_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_011_),
    .Q(\memory[5] [1])
  );
  \$_DFFE_PP_  \memory_reg[5][2]  /* _354_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_011_),
    .Q(\memory[5] [2])
  );
  \$_DFFE_PP_  \memory_reg[5][3]  /* _355_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_011_),
    .Q(\memory[5] [3])
  );
  \$_DFFE_PP_  \memory_reg[5][4]  /* _356_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_011_),
    .Q(\memory[5] [4])
  );
  \$_DFFE_PP_  \memory_reg[5][5]  /* _357_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_011_),
    .Q(\memory[5] [5])
  );
  \$_DFFE_PP_  \memory_reg[5][6]  /* _358_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_011_),
    .Q(\memory[5] [6])
  );
  \$_DFFE_PP_  \memory_reg[5][7]  /* _359_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_011_),
    .Q(\memory[5] [7])
  );
  \$_DFFE_PP_  \memory_reg[6][0]  /* _360_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_012_),
    .Q(\memory[6] [0])
  );
  \$_DFFE_PP_  \memory_reg[6][1]  /* _361_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_012_),
    .Q(\memory[6] [1])
  );
  \$_DFFE_PP_  \memory_reg[6][2]  /* _362_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_012_),
    .Q(\memory[6] [2])
  );
  \$_DFFE_PP_  \memory_reg[6][3]  /* _363_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_012_),
    .Q(\memory[6] [3])
  );
  \$_DFFE_PP_  \memory_reg[6][4]  /* _364_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_012_),
    .Q(\memory[6] [4])
  );
  \$_DFFE_PP_  \memory_reg[6][5]  /* _365_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_012_),
    .Q(\memory[6] [5])
  );
  \$_DFFE_PP_  \memory_reg[6][6]  /* _366_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_012_),
    .Q(\memory[6] [6])
  );
  \$_DFFE_PP_  \memory_reg[6][7]  /* _367_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_012_),
    .Q(\memory[6] [7])
  );
  \$_DFFE_PP_  \memory_reg[7][0]  /* _368_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_013_),
    .Q(\memory[7] [0])
  );
  \$_DFFE_PP_  \memory_reg[7][1]  /* _369_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_013_),
    .Q(\memory[7] [1])
  );
  \$_DFFE_PP_  \memory_reg[7][2]  /* _370_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_013_),
    .Q(\memory[7] [2])
  );
  \$_DFFE_PP_  \memory_reg[7][3]  /* _371_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_013_),
    .Q(\memory[7] [3])
  );
  \$_DFFE_PP_  \memory_reg[7][4]  /* _372_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_013_),
    .Q(\memory[7] [4])
  );
  \$_DFFE_PP_  \memory_reg[7][5]  /* _373_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_013_),
    .Q(\memory[7] [5])
  );
  \$_DFFE_PP_  \memory_reg[7][6]  /* _374_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_013_),
    .Q(\memory[7] [6])
  );
  \$_DFFE_PP_  \memory_reg[7][7]  /* _375_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_013_),
    .Q(\memory[7] [7])
  );
  \$_DFFE_PP_  \memory_reg[8][0]  /* _376_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_014_),
    .Q(\memory[8] [0])
  );
  \$_DFFE_PP_  \memory_reg[8][1]  /* _377_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_014_),
    .Q(\memory[8] [1])
  );
  \$_DFFE_PP_  \memory_reg[8][2]  /* _378_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_014_),
    .Q(\memory[8] [2])
  );
  \$_DFFE_PP_  \memory_reg[8][3]  /* _379_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_014_),
    .Q(\memory[8] [3])
  );
  \$_DFFE_PP_  \memory_reg[8][4]  /* _380_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_014_),
    .Q(\memory[8] [4])
  );
  \$_DFFE_PP_  \memory_reg[8][5]  /* _381_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_014_),
    .Q(\memory[8] [5])
  );
  \$_DFFE_PP_  \memory_reg[8][6]  /* _382_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_014_),
    .Q(\memory[8] [6])
  );
  \$_DFFE_PP_  \memory_reg[8][7]  /* _383_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_014_),
    .Q(\memory[8] [7])
  );
  \$_DFFE_PP_  \memory_reg[0][0]  /* _384_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_000_),
    .Q(\memory[0] [0])
  );
  \$_DFFE_PP_  \memory_reg[0][1]  /* _385_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_000_),
    .Q(\memory[0] [1])
  );
  \$_DFFE_PP_  \memory_reg[0][2]  /* _386_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_000_),
    .Q(\memory[0] [2])
  );
  \$_DFFE_PP_  \memory_reg[0][3]  /* _387_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_000_),
    .Q(\memory[0] [3])
  );
  \$_DFFE_PP_  \memory_reg[0][4]  /* _388_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_000_),
    .Q(\memory[0] [4])
  );
  \$_DFFE_PP_  \memory_reg[0][5]  /* _389_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_000_),
    .Q(\memory[0] [5])
  );
  \$_DFFE_PP_  \memory_reg[0][6]  /* _390_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_000_),
    .Q(\memory[0] [6])
  );
  \$_DFFE_PP_  \memory_reg[0][7]  /* _391_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_000_),
    .Q(\memory[0] [7])
  );
  \$_DFFE_PP_  \memory_reg[10][0]  /* _392_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_001_),
    .Q(\memory[10] [0])
  );
  \$_DFFE_PP_  \memory_reg[10][1]  /* _393_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_001_),
    .Q(\memory[10] [1])
  );
  \$_DFFE_PP_  \memory_reg[10][2]  /* _394_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_001_),
    .Q(\memory[10] [2])
  );
  \$_DFFE_PP_  \memory_reg[10][3]  /* _395_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_001_),
    .Q(\memory[10] [3])
  );
  \$_DFFE_PP_  \memory_reg[10][4]  /* _396_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_001_),
    .Q(\memory[10] [4])
  );
  \$_DFFE_PP_  \memory_reg[10][5]  /* _397_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_001_),
    .Q(\memory[10] [5])
  );
  \$_DFFE_PP_  \memory_reg[10][6]  /* _398_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_001_),
    .Q(\memory[10] [6])
  );
  \$_DFFE_PP_  \memory_reg[10][7]  /* _399_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_001_),
    .Q(\memory[10] [7])
  );
  \$_DFFE_PP_  \memory_reg[11][0]  /* _400_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_002_),
    .Q(\memory[11] [0])
  );
  \$_DFFE_PP_  \memory_reg[11][1]  /* _401_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_002_),
    .Q(\memory[11] [1])
  );
  \$_DFFE_PP_  \memory_reg[11][2]  /* _402_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_002_),
    .Q(\memory[11] [2])
  );
  \$_DFFE_PP_  \memory_reg[11][3]  /* _403_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_002_),
    .Q(\memory[11] [3])
  );
  \$_DFFE_PP_  \memory_reg[11][4]  /* _404_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_002_),
    .Q(\memory[11] [4])
  );
  \$_DFFE_PP_  \memory_reg[11][5]  /* _405_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_002_),
    .Q(\memory[11] [5])
  );
  \$_DFFE_PP_  \memory_reg[11][6]  /* _406_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_002_),
    .Q(\memory[11] [6])
  );
  \$_DFFE_PP_  \memory_reg[11][7]  /* _407_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_002_),
    .Q(\memory[11] [7])
  );
  \$_DFFE_PP_  \memory_reg[12][0]  /* _408_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_003_),
    .Q(\memory[12] [0])
  );
  \$_DFFE_PP_  \memory_reg[12][1]  /* _409_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_003_),
    .Q(\memory[12] [1])
  );
  \$_DFFE_PP_  \memory_reg[12][2]  /* _410_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_003_),
    .Q(\memory[12] [2])
  );
  \$_DFFE_PP_  \memory_reg[12][3]  /* _411_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_003_),
    .Q(\memory[12] [3])
  );
  \$_DFFE_PP_  \memory_reg[12][4]  /* _412_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_003_),
    .Q(\memory[12] [4])
  );
  \$_DFFE_PP_  \memory_reg[12][5]  /* _413_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_003_),
    .Q(\memory[12] [5])
  );
  \$_DFFE_PP_  \memory_reg[12][6]  /* _414_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_003_),
    .Q(\memory[12] [6])
  );
  \$_DFFE_PP_  \memory_reg[12][7]  /* _415_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_003_),
    .Q(\memory[12] [7])
  );
  \$_DFFE_PP_  \memory_reg[13][0]  /* _416_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_004_),
    .Q(\memory[13] [0])
  );
  \$_DFFE_PP_  \memory_reg[13][1]  /* _417_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_004_),
    .Q(\memory[13] [1])
  );
  \$_DFFE_PP_  \memory_reg[13][2]  /* _418_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_004_),
    .Q(\memory[13] [2])
  );
  \$_DFFE_PP_  \memory_reg[13][3]  /* _419_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_004_),
    .Q(\memory[13] [3])
  );
  \$_DFFE_PP_  \memory_reg[13][4]  /* _420_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_004_),
    .Q(\memory[13] [4])
  );
  \$_DFFE_PP_  \memory_reg[13][5]  /* _421_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_004_),
    .Q(\memory[13] [5])
  );
  \$_DFFE_PP_  \memory_reg[13][6]  /* _422_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_004_),
    .Q(\memory[13] [6])
  );
  \$_DFFE_PP_  \memory_reg[13][7]  /* _423_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_004_),
    .Q(\memory[13] [7])
  );
  \$_DFFE_PP_  \memory_reg[14][0]  /* _424_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_005_),
    .Q(\memory[14] [0])
  );
  \$_DFFE_PP_  \memory_reg[14][1]  /* _425_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_005_),
    .Q(\memory[14] [1])
  );
  \$_DFFE_PP_  \memory_reg[14][2]  /* _426_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_005_),
    .Q(\memory[14] [2])
  );
  \$_DFFE_PP_  \memory_reg[14][3]  /* _427_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_005_),
    .Q(\memory[14] [3])
  );
  \$_DFFE_PP_  \memory_reg[14][4]  /* _428_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_005_),
    .Q(\memory[14] [4])
  );
  \$_DFFE_PP_  \memory_reg[14][5]  /* _429_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_005_),
    .Q(\memory[14] [5])
  );
  \$_DFFE_PP_  \memory_reg[14][6]  /* _430_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_005_),
    .Q(\memory[14] [6])
  );
  \$_DFFE_PP_  \memory_reg[14][7]  /* _431_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_005_),
    .Q(\memory[14] [7])
  );
  \$_DFFE_PP_  \memory_reg[9][0]  /* _432_ */ (
    .C(clk),
    .D(data_in[0]),
    .E(_015_),
    .Q(\memory[9] [0])
  );
  \$_DFFE_PP_  \memory_reg[9][1]  /* _433_ */ (
    .C(clk),
    .D(data_in[1]),
    .E(_015_),
    .Q(\memory[9] [1])
  );
  \$_DFFE_PP_  \memory_reg[9][2]  /* _434_ */ (
    .C(clk),
    .D(data_in[2]),
    .E(_015_),
    .Q(\memory[9] [2])
  );
  \$_DFFE_PP_  \memory_reg[9][3]  /* _435_ */ (
    .C(clk),
    .D(data_in[3]),
    .E(_015_),
    .Q(\memory[9] [3])
  );
  \$_DFFE_PP_  \memory_reg[9][4]  /* _436_ */ (
    .C(clk),
    .D(data_in[4]),
    .E(_015_),
    .Q(\memory[9] [4])
  );
  \$_DFFE_PP_  \memory_reg[9][5]  /* _437_ */ (
    .C(clk),
    .D(data_in[5]),
    .E(_015_),
    .Q(\memory[9] [5])
  );
  \$_DFFE_PP_  \memory_reg[9][6]  /* _438_ */ (
    .C(clk),
    .D(data_in[6]),
    .E(_015_),
    .Q(\memory[9] [6])
  );
  \$_DFFE_PP_  \memory_reg[9][7]  /* _439_ */ (
    .C(clk),
    .D(data_in[7]),
    .E(_015_),
    .Q(\memory[9] [7])
  );
  assign memrd_memory_DATA = data_out;
endmodule
