/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "dut.sv:1.1-36.10" *)
module simple_memory(clk, rst, we, addr, data_in, data_out);
  (* src = "dut.sv:9.34-9.38" *)
  input [3:0] addr;
  wire [3:0] addr;
  (* src = "dut.sv:6.34-6.37" *)
  input clk;
  wire clk;
  (* src = "dut.sv:10.34-10.41" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "dut.sv:11.34-11.42" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  (* src = "dut.sv:7.34-7.37" *)
  input rst;
  wire rst;
  (* src = "dut.sv:8.34-8.36" *)
  input we;
  wire we;
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:19.5-34.8" *)
  \$_DFF_PN0_  \data_out_reg[0]  /* _0_ */ (
    .C(clk),
    .D(addr[0]),
    .Q(data_out[0]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:19.5-34.8" *)
  \$_DFF_PN0_  \data_out_reg[1]  /* _1_ */ (
    .C(clk),
    .D(addr[1]),
    .Q(data_out[1]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:19.5-34.8" *)
  \$_DFF_PN0_  \data_out_reg[2]  /* _2_ */ (
    .C(clk),
    .D(addr[2]),
    .Q(data_out[2]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:19.5-34.8" *)
  \$_DFF_PN0_  \data_out_reg[3]  /* _3_ */ (
    .C(clk),
    .D(addr[3]),
    .Q(data_out[3]),
    .R(rst)
  );
  assign data_out[7:4] = 4'h0;
endmodule
