/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) */

(* top =  1  *)
(* src = "dut.sv:1.1-22.10" *)
module top(CLK, LED);
  (* src = "dut.sv:3.9-3.12" *)
  input CLK;
  wire CLK;
  (* src = "dut.sv:4.16-4.19" *)
  output [5:0] LED;
  wire [5:0] LED;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:13.7-13.30|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17" *)
  wire [18:0] _046_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:18.19-18.35|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [5:0] _047_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:14.21-14.39|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [23:0] _048_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:14.21-14.39|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [23:0] _049_;
  (* init = 6'h00 *)
  (* src = "dut.sv:8.11-8.21" *)
  wire [5:0] ledCounter;
  (* init = 24'h000000 *)
  (* src = "dut.sv:7.12-7.24" *)
  wire [23:0] wait_counter;
  \$_NOT_  _050_ (
    .A(ledCounter[4]),
    .Y(LED[4])
  );
  \$_NOT_  _051_ (
    .A(ledCounter[3]),
    .Y(LED[3])
  );
  \$_NOT_  _052_ (
    .A(ledCounter[2]),
    .Y(LED[2])
  );
  \$_NOT_  _053_ (
    .A(ledCounter[1]),
    .Y(LED[1])
  );
  \$_NOT_  _054_ (
    .A(ledCounter[0]),
    .Y(LED[0])
  );
  \$_NOT_  _055_ (
    .A(ledCounter[5]),
    .Y(LED[5])
  );
  \$_NOT_  _056_ (
    .A(wait_counter[0]),
    .Y(_048_[0])
  );
  \$_AND_  _057_ (
    .A(ledCounter[1]),
    .B(ledCounter[0]),
    .Y(_025_)
  );
  \$_AND_  _058_ (
    .A(ledCounter[2]),
    .B(_025_),
    .Y(_026_)
  );
  \$_AND_  _059_ (
    .A(ledCounter[3]),
    .B(_026_),
    .Y(_027_)
  );
  \$_AND_  _060_ (
    .A(ledCounter[4]),
    .B(_027_),
    .Y(_028_)
  );
  \$_XNOR_  _061_ (
    .A(LED[4]),
    .B(_027_),
    .Y(_047_[4])
  );
  \$_XNOR_  _062_ (
    .A(LED[3]),
    .B(_026_),
    .Y(_047_[3])
  );
  \$_XNOR_  _063_ (
    .A(LED[2]),
    .B(_025_),
    .Y(_047_[2])
  );
  \$_XOR_  _064_ (
    .A(ledCounter[1]),
    .B(ledCounter[0]),
    .Y(_047_[1])
  );
  \$_XNOR_  _065_ (
    .A(LED[5]),
    .B(_028_),
    .Y(_047_[5])
  );
  \$_AND_  _066_ (
    .A(wait_counter[16]),
    .B(wait_counter[15]),
    .Y(_029_)
  );
  \$_AND_  _067_ (
    .A(wait_counter[1]),
    .B(wait_counter[0]),
    .Y(_030_)
  );
  \$_AND_  _068_ (
    .A(wait_counter[2]),
    .B(_030_),
    .Y(_031_)
  );
  \$_AND_  _069_ (
    .A(wait_counter[3]),
    .B(_031_),
    .Y(_032_)
  );
  \$_AND_  _070_ (
    .A(wait_counter[4]),
    .B(_032_),
    .Y(_033_)
  );
  \$_AND_  _071_ (
    .A(wait_counter[5]),
    .B(wait_counter[6]),
    .Y(_034_)
  );
  \$_NAND_  _072_ (
    .A(wait_counter[5]),
    .B(_033_),
    .Y(_035_)
  );
  \$_AND_  _073_ (
    .A(_033_),
    .B(_034_),
    .Y(_036_)
  );
  \$_AND_  _074_ (
    .A(wait_counter[7]),
    .B(_036_),
    .Y(_037_)
  );
  \$_AND_  _075_ (
    .A(wait_counter[8]),
    .B(_037_),
    .Y(_038_)
  );
  \$_AND_  _076_ (
    .A(wait_counter[10]),
    .B(wait_counter[9]),
    .Y(_039_)
  );
  \$_AND_  _077_ (
    .A(_038_),
    .B(_039_),
    .Y(_040_)
  );
  \$_AND_  _078_ (
    .A(wait_counter[12]),
    .B(wait_counter[11]),
    .Y(_041_)
  );
  \$_AND_  _079_ (
    .A(wait_counter[14]),
    .B(wait_counter[13]),
    .Y(_042_)
  );
  \$_AND_  _080_ (
    .A(_041_),
    .B(_042_),
    .Y(_043_)
  );
  \$_AND_  _081_ (
    .A(_040_),
    .B(_043_),
    .Y(_044_)
  );
  \$_AND_  _082_ (
    .A(_029_),
    .B(_044_),
    .Y(_045_)
  );
  \$_AND_  _083_ (
    .A(wait_counter[17]),
    .B(_045_),
    .Y(_000_)
  );
  \$_NAND_  _084_ (
    .A(wait_counter[18]),
    .B(_000_),
    .Y(_001_)
  );
  \$_AND_  _085_ (
    .A(wait_counter[15]),
    .B(_044_),
    .Y(_002_)
  );
  \$_AND_  _086_ (
    .A(wait_counter[16]),
    .B(_002_),
    .Y(_003_)
  );
  \$_AND_  _087_ (
    .A(wait_counter[17]),
    .B(_003_),
    .Y(_004_)
  );
  \$_AND_  _088_ (
    .A(wait_counter[18]),
    .B(wait_counter[19]),
    .Y(_005_)
  );
  \$_AND_  _089_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  \$_AND_  _090_ (
    .A(wait_counter[20]),
    .B(_006_),
    .Y(_007_)
  );
  \$_AND_  _091_ (
    .A(wait_counter[21]),
    .B(_007_),
    .Y(_008_)
  );
  \$_NAND_  _092_ (
    .A(wait_counter[22]),
    .B(_008_),
    .Y(_009_)
  );
  \$_AND_  _093_ (
    .A(wait_counter[9]),
    .B(_038_),
    .Y(_010_)
  );
  \$_AND_  _094_ (
    .A(wait_counter[10]),
    .B(_010_),
    .Y(_011_)
  );
  \$_AND_  _095_ (
    .A(wait_counter[11]),
    .B(_011_),
    .Y(_012_)
  );
  \$_AND_  _096_ (
    .A(wait_counter[12]),
    .B(_012_),
    .Y(_013_)
  );
  \$_NAND_  _097_ (
    .A(wait_counter[13]),
    .B(_013_),
    .Y(_014_)
  );
  \$_AND_  _098_ (
    .A(wait_counter[22]),
    .B(wait_counter[23]),
    .Y(_015_)
  );
  \$_XNOR_  _099_ (
    .A(wait_counter[23]),
    .B(_009_),
    .Y(_049_[23])
  );
  \$_XOR_  _100_ (
    .A(wait_counter[22]),
    .B(_008_),
    .Y(_049_[22])
  );
  \$_XOR_  _101_ (
    .A(wait_counter[21]),
    .B(_007_),
    .Y(_049_[21])
  );
  \$_XOR_  _102_ (
    .A(wait_counter[20]),
    .B(_006_),
    .Y(_049_[20])
  );
  \$_XNOR_  _103_ (
    .A(wait_counter[19]),
    .B(_001_),
    .Y(_049_[19])
  );
  \$_XOR_  _104_ (
    .A(wait_counter[18]),
    .B(_000_),
    .Y(_049_[18])
  );
  \$_XOR_  _105_ (
    .A(wait_counter[17]),
    .B(_045_),
    .Y(_049_[17])
  );
  \$_XOR_  _106_ (
    .A(wait_counter[16]),
    .B(_002_),
    .Y(_049_[16])
  );
  \$_XOR_  _107_ (
    .A(wait_counter[15]),
    .B(_044_),
    .Y(_049_[15])
  );
  \$_XNOR_  _108_ (
    .A(wait_counter[14]),
    .B(_014_),
    .Y(_049_[14])
  );
  \$_XOR_  _109_ (
    .A(wait_counter[13]),
    .B(_013_),
    .Y(_049_[13])
  );
  \$_XOR_  _110_ (
    .A(wait_counter[12]),
    .B(_012_),
    .Y(_049_[12])
  );
  \$_XOR_  _111_ (
    .A(wait_counter[11]),
    .B(_040_),
    .Y(_049_[11])
  );
  \$_XOR_  _112_ (
    .A(wait_counter[10]),
    .B(_010_),
    .Y(_049_[10])
  );
  \$_XOR_  _113_ (
    .A(wait_counter[9]),
    .B(_038_),
    .Y(_049_[9])
  );
  \$_XOR_  _114_ (
    .A(wait_counter[8]),
    .B(_037_),
    .Y(_049_[8])
  );
  \$_XOR_  _115_ (
    .A(wait_counter[7]),
    .B(_036_),
    .Y(_049_[7])
  );
  \$_XNOR_  _116_ (
    .A(wait_counter[6]),
    .B(_035_),
    .Y(_049_[6])
  );
  \$_XOR_  _117_ (
    .A(wait_counter[5]),
    .B(_033_),
    .Y(_049_[5])
  );
  \$_XOR_  _118_ (
    .A(wait_counter[4]),
    .B(_032_),
    .Y(_049_[4])
  );
  \$_XOR_  _119_ (
    .A(wait_counter[3]),
    .B(_031_),
    .Y(_049_[3])
  );
  \$_XOR_  _120_ (
    .A(wait_counter[2]),
    .B(_030_),
    .Y(_049_[2])
  );
  \$_XOR_  _121_ (
    .A(wait_counter[1]),
    .B(wait_counter[0]),
    .Y(_049_[1])
  );
  \$_OR_  _122_ (
    .A(wait_counter[8]),
    .B(wait_counter[7]),
    .Y(_016_)
  );
  \$_OR_  _123_ (
    .A(_034_),
    .B(_016_),
    .Y(_017_)
  );
  \$_AND_  _124_ (
    .A(_029_),
    .B(_039_),
    .Y(_018_)
  );
  \$_AND_  _125_ (
    .A(_043_),
    .B(_018_),
    .Y(_019_)
  );
  \$_AND_  _126_ (
    .A(_017_),
    .B(_019_),
    .Y(_020_)
  );
  \$_OR_  _127_ (
    .A(wait_counter[17]),
    .B(_020_),
    .Y(_021_)
  );
  \$_NAND_  _128_ (
    .A(_005_),
    .B(_021_),
    .Y(_022_)
  );
  \$_NOR_  _129_ (
    .A(wait_counter[20]),
    .B(wait_counter[21]),
    .Y(_023_)
  );
  \$_NAND_  _130_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  \$_AND_  _131_ (
    .A(_015_),
    .B(_024_),
    .Y(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_DFFE_PP_  \ledCounter_reg[0]  /* _132_ */ (
    .C(CLK),
    .D(LED[0]),
    .E(_046_[18]),
    .Q(ledCounter[0])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_DFFE_PP_  \ledCounter_reg[1]  /* _133_ */ (
    .C(CLK),
    .D(_047_[1]),
    .E(_046_[18]),
    .Q(ledCounter[1])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_DFFE_PP_  \ledCounter_reg[2]  /* _134_ */ (
    .C(CLK),
    .D(_047_[2]),
    .E(_046_[18]),
    .Q(ledCounter[2])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_DFFE_PP_  \ledCounter_reg[3]  /* _135_ */ (
    .C(CLK),
    .D(_047_[3]),
    .E(_046_[18]),
    .Q(ledCounter[3])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_DFFE_PP_  \ledCounter_reg[4]  /* _136_ */ (
    .C(CLK),
    .D(_047_[4]),
    .E(_046_[18]),
    .Q(ledCounter[4])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_DFFE_PP_  \ledCounter_reg[5]  /* _137_ */ (
    .C(CLK),
    .D(_047_[5]),
    .E(_046_[18]),
    .Q(ledCounter[5])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[0]  /* _138_ */ (
    .C(CLK),
    .D(_048_[0]),
    .Q(wait_counter[0]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[1]  /* _139_ */ (
    .C(CLK),
    .D(_049_[1]),
    .Q(wait_counter[1]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[2]  /* _140_ */ (
    .C(CLK),
    .D(_049_[2]),
    .Q(wait_counter[2]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[3]  /* _141_ */ (
    .C(CLK),
    .D(_049_[3]),
    .Q(wait_counter[3]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[4]  /* _142_ */ (
    .C(CLK),
    .D(_049_[4]),
    .Q(wait_counter[4]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[5]  /* _143_ */ (
    .C(CLK),
    .D(_049_[5]),
    .Q(wait_counter[5]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[6]  /* _144_ */ (
    .C(CLK),
    .D(_049_[6]),
    .Q(wait_counter[6]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[7]  /* _145_ */ (
    .C(CLK),
    .D(_049_[7]),
    .Q(wait_counter[7]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[8]  /* _146_ */ (
    .C(CLK),
    .D(_049_[8]),
    .Q(wait_counter[8]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[9]  /* _147_ */ (
    .C(CLK),
    .D(_049_[9]),
    .Q(wait_counter[9]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[10]  /* _148_ */ (
    .C(CLK),
    .D(_049_[10]),
    .Q(wait_counter[10]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[11]  /* _149_ */ (
    .C(CLK),
    .D(_049_[11]),
    .Q(wait_counter[11]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[12]  /* _150_ */ (
    .C(CLK),
    .D(_049_[12]),
    .Q(wait_counter[12]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[13]  /* _151_ */ (
    .C(CLK),
    .D(_049_[13]),
    .Q(wait_counter[13]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[14]  /* _152_ */ (
    .C(CLK),
    .D(_049_[14]),
    .Q(wait_counter[14]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[15]  /* _153_ */ (
    .C(CLK),
    .D(_049_[15]),
    .Q(wait_counter[15]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[16]  /* _154_ */ (
    .C(CLK),
    .D(_049_[16]),
    .Q(wait_counter[16]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[17]  /* _155_ */ (
    .C(CLK),
    .D(_049_[17]),
    .Q(wait_counter[17]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[18]  /* _156_ */ (
    .C(CLK),
    .D(_049_[18]),
    .Q(wait_counter[18]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[19]  /* _157_ */ (
    .C(CLK),
    .D(_049_[19]),
    .Q(wait_counter[19]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[20]  /* _158_ */ (
    .C(CLK),
    .D(_049_[20]),
    .Q(wait_counter[20]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[21]  /* _159_ */ (
    .C(CLK),
    .D(_049_[21]),
    .Q(wait_counter[21]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[22]  /* _160_ */ (
    .C(CLK),
    .D(_049_[22]),
    .Q(wait_counter[22]),
    .R(_046_[18])
  );
  (* src = "dut.sv:12.1-20.4" *)
  \$_SDFF_PP0_  \wait_counter_reg[23]  /* _161_ */ (
    .C(CLK),
    .D(_049_[23]),
    .Q(wait_counter[23]),
    .R(_046_[18])
  );
  assign _047_[0] = LED[0];
  assign _049_[0] = _048_[0];
  assign _048_[23:1] = wait_counter[23:1];
  assign _046_[0] = wait_counter[5];
endmodule
