/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* dynports =  1  *)
(* src = "dut.sv:12.4-14.32" *)
(* hdlname = "aes_cipher_core" *)
module \$paramod\aes_cipher_core\P_PKG=s32'00000000000000000000000000000000\P_INSTANCE=s32'00000000000000000000000000000000 (x);
  (* src = "dut.sv:6.54-6.55" *)
  output signed [31:0] x;
  wire signed [31:0] x;
  assign x = 32'd1961980218;
endmodule

(* dynports =  1  *)
(* src = "dut.sv:11.1-15.10" *)
(* top =  1  *)
module top(o);
  (* src = "dut.sv:11.42-11.43" *)
  output signed [31:0] o;
  wire signed [31:0] o;
  \$paramod\aes_cipher_core\P_PKG=s32'00000000000000000000000000000000\P_INSTANCE=s32'00000000000000000000000000000000  u_aes_cipher_core (
    .x(o)
  );
endmodule
