/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* src = "dut.sv:4.1-82.10" *)
(* top =  1  *)
module subbytes_00(clk, reset, start_i, decrypt_i, data_i, ready_o, data_o, sbox_data_o, sbox_data_i, sbox_decrypt_o);
  (* src = "dut.sv:4.20-4.23" *)
  input clk;
  wire clk;
  (* src = "dut.sv:4.25-4.30" *)
  input reset;
  wire reset;
  (* src = "dut.sv:4.32-4.39" *)
  input start_i;
  wire start_i;
  (* src = "dut.sv:4.41-4.50" *)
  input decrypt_i;
  wire decrypt_i;
  (* src = "dut.sv:4.52-4.58" *)
  input [31:0] data_i;
  wire [31:0] data_i;
  (* src = "dut.sv:4.60-4.67" *)
  output ready_o;
  wire ready_o;
  (* src = "dut.sv:4.69-4.75" *)
  output [31:0] data_o;
  wire [31:0] data_o;
  (* src = "dut.sv:4.77-4.88" *)
  output [7:0] sbox_data_o;
  wire [7:0] sbox_data_o;
  (* src = "dut.sv:4.90-4.101" *)
  input [7:0] sbox_data_i;
  wire [7:0] sbox_data_i;
  (* src = "dut.sv:4.103-4.117" *)
  output sbox_decrypt_o;
  wire sbox_decrypt_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  (* src = "dut.sv:42.11-42.21" *)
  wire [7:0] \data_array[0] ;
  (* src = "dut.sv:42.11-42.21" *)
  wire [7:0] \data_array[1] ;
  (* src = "dut.sv:42.11-42.21" *)
  wire [7:0] \data_array[2] ;
  (* src = "dut.sv:42.11-42.21" *)
  wire [7:0] \data_array[3] ;
  (* src = "dut.sv:41.12-41.22" *)
  wire [31:0] data_i_var;
  (* src = "dut.sv:24.12-24.20" *)
  wire [31:0] data_reg;
  (* src = "dut.sv:41.24-41.36" *)
  wire [31:0] data_reg_128;
  (* src = "dut.sv:43.11-43.23" *)
  wire [7:0] \data_reg_var[0] ;
  (* src = "dut.sv:43.11-43.23" *)
  wire [7:0] \data_reg_var[1] ;
  (* src = "dut.sv:43.11-43.23" *)
  wire [7:0] \data_reg_var[2] ;
  (* src = "dut.sv:43.11-43.23" *)
  wire [7:0] \data_reg_var[3] ;
  (* src = "dut.sv:26.5-26.17" *)
  wire next_ready_o;
  (* src = "dut.sv:23.11-23.21" *)
  wire [1:0] next_state;
  (* src = "dut.sv:22.11-22.16" *)
  wire [1:0] state;
  \$_ORNOT_  _019_ (
    .A(1'h0),
    .B(state[0]),
    .Y(_001_)
  );
  \$_ORNOT_  _020_ (
    .A(state[0]),
    .B(1'h0),
    .Y(_002_)
  );
  \$_MUX_  _021_ (
    .A(data_i[14]),
    .B(data_i[6]),
    .S(_002_),
    .Y(_003_)
  );
  \$_MUX_  _022_ (
    .A(data_i[22]),
    .B(_003_),
    .S(_001_),
    .Y(_004_)
  );
  \$_MUX_  _023_ (
    .A(data_i[30]),
    .B(_004_),
    .S(state[0]),
    .Y(sbox_data_o[6])
  );
  \$_MUX_  _024_ (
    .A(data_i[13]),
    .B(data_i[5]),
    .S(_002_),
    .Y(_005_)
  );
  \$_MUX_  _025_ (
    .A(data_i[21]),
    .B(_005_),
    .S(_001_),
    .Y(_006_)
  );
  \$_MUX_  _026_ (
    .A(data_i[29]),
    .B(_006_),
    .S(state[0]),
    .Y(sbox_data_o[5])
  );
  \$_MUX_  _027_ (
    .A(data_i[12]),
    .B(data_i[4]),
    .S(_002_),
    .Y(_007_)
  );
  \$_MUX_  _028_ (
    .A(data_i[20]),
    .B(_007_),
    .S(_001_),
    .Y(_008_)
  );
  \$_MUX_  _029_ (
    .A(data_i[28]),
    .B(_008_),
    .S(state[0]),
    .Y(sbox_data_o[4])
  );
  \$_MUX_  _030_ (
    .A(data_i[11]),
    .B(data_i[3]),
    .S(_002_),
    .Y(_009_)
  );
  \$_MUX_  _031_ (
    .A(data_i[19]),
    .B(_009_),
    .S(_001_),
    .Y(_010_)
  );
  \$_MUX_  _032_ (
    .A(data_i[27]),
    .B(_010_),
    .S(state[0]),
    .Y(sbox_data_o[3])
  );
  \$_MUX_  _033_ (
    .A(data_i[10]),
    .B(data_i[2]),
    .S(_002_),
    .Y(_011_)
  );
  \$_MUX_  _034_ (
    .A(data_i[18]),
    .B(_011_),
    .S(_001_),
    .Y(_012_)
  );
  \$_MUX_  _035_ (
    .A(data_i[26]),
    .B(_012_),
    .S(state[0]),
    .Y(sbox_data_o[2])
  );
  \$_MUX_  _036_ (
    .A(data_i[9]),
    .B(data_i[1]),
    .S(_002_),
    .Y(_013_)
  );
  \$_MUX_  _037_ (
    .A(data_i[17]),
    .B(_013_),
    .S(_001_),
    .Y(_014_)
  );
  \$_MUX_  _038_ (
    .A(data_i[25]),
    .B(_014_),
    .S(state[0]),
    .Y(sbox_data_o[1])
  );
  \$_MUX_  _039_ (
    .A(data_i[8]),
    .B(data_i[0]),
    .S(_002_),
    .Y(_015_)
  );
  \$_MUX_  _040_ (
    .A(data_i[16]),
    .B(_015_),
    .S(_001_),
    .Y(_016_)
  );
  \$_MUX_  _041_ (
    .A(data_i[24]),
    .B(_016_),
    .S(state[0]),
    .Y(sbox_data_o[0])
  );
  \$_MUX_  _042_ (
    .A(data_i[15]),
    .B(data_i[7]),
    .S(_002_),
    .Y(_017_)
  );
  \$_MUX_  _043_ (
    .A(data_i[23]),
    .B(_017_),
    .S(_001_),
    .Y(_018_)
  );
  \$_MUX_  _044_ (
    .A(data_i[31]),
    .B(_018_),
    .S(state[0]),
    .Y(sbox_data_o[7])
  );
  \$_ORNOT_  _045_ (
    .A(start_i),
    .B(state[0]),
    .Y(_000_)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[0]  /* _046_ */ (
    .C(clk),
    .D(data_reg_128[0]),
    .E(state[0]),
    .Q(data_reg[0]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[1]  /* _047_ */ (
    .C(clk),
    .D(data_reg_128[1]),
    .E(state[0]),
    .Q(data_reg[1]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[2]  /* _048_ */ (
    .C(clk),
    .D(data_reg_128[2]),
    .E(state[0]),
    .Q(data_reg[2]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[3]  /* _049_ */ (
    .C(clk),
    .D(data_reg_128[3]),
    .E(state[0]),
    .Q(data_reg[3]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[4]  /* _050_ */ (
    .C(clk),
    .D(data_reg_128[4]),
    .E(state[0]),
    .Q(data_reg[4]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[5]  /* _051_ */ (
    .C(clk),
    .D(data_reg_128[5]),
    .E(state[0]),
    .Q(data_reg[5]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[6]  /* _052_ */ (
    .C(clk),
    .D(data_reg_128[6]),
    .E(state[0]),
    .Q(data_reg[6]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[7]  /* _053_ */ (
    .C(clk),
    .D(data_reg_128[7]),
    .E(state[0]),
    .Q(data_reg[7]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[8]  /* _054_ */ (
    .C(clk),
    .D(data_reg_128[8]),
    .E(state[0]),
    .Q(data_reg[8]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[9]  /* _055_ */ (
    .C(clk),
    .D(data_reg_128[9]),
    .E(state[0]),
    .Q(data_reg[9]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[10]  /* _056_ */ (
    .C(clk),
    .D(data_reg_128[10]),
    .E(state[0]),
    .Q(data_reg[10]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[11]  /* _057_ */ (
    .C(clk),
    .D(data_reg_128[11]),
    .E(state[0]),
    .Q(data_reg[11]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[12]  /* _058_ */ (
    .C(clk),
    .D(data_reg_128[12]),
    .E(state[0]),
    .Q(data_reg[12]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[13]  /* _059_ */ (
    .C(clk),
    .D(data_reg_128[13]),
    .E(state[0]),
    .Q(data_reg[13]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[14]  /* _060_ */ (
    .C(clk),
    .D(data_reg_128[14]),
    .E(state[0]),
    .Q(data_reg[14]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[15]  /* _061_ */ (
    .C(clk),
    .D(data_reg_128[15]),
    .E(state[0]),
    .Q(data_reg[15]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[16]  /* _062_ */ (
    .C(clk),
    .D(data_reg_128[16]),
    .E(state[0]),
    .Q(data_reg[16]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[17]  /* _063_ */ (
    .C(clk),
    .D(data_reg_128[17]),
    .E(state[0]),
    .Q(data_reg[17]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[18]  /* _064_ */ (
    .C(clk),
    .D(data_reg_128[18]),
    .E(state[0]),
    .Q(data_reg[18]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[19]  /* _065_ */ (
    .C(clk),
    .D(data_reg_128[19]),
    .E(state[0]),
    .Q(data_reg[19]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[20]  /* _066_ */ (
    .C(clk),
    .D(data_reg_128[20]),
    .E(state[0]),
    .Q(data_reg[20]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[21]  /* _067_ */ (
    .C(clk),
    .D(data_reg_128[21]),
    .E(state[0]),
    .Q(data_reg[21]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[22]  /* _068_ */ (
    .C(clk),
    .D(data_reg_128[22]),
    .E(state[0]),
    .Q(data_reg[22]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[23]  /* _069_ */ (
    .C(clk),
    .D(data_reg_128[23]),
    .E(state[0]),
    .Q(data_reg[23]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[24]  /* _070_ */ (
    .C(clk),
    .D(data_reg_128[24]),
    .E(state[0]),
    .Q(data_reg[24]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[25]  /* _071_ */ (
    .C(clk),
    .D(data_reg_128[25]),
    .E(state[0]),
    .Q(data_reg[25]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[26]  /* _072_ */ (
    .C(clk),
    .D(data_reg_128[26]),
    .E(state[0]),
    .Q(data_reg[26]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[27]  /* _073_ */ (
    .C(clk),
    .D(data_reg_128[27]),
    .E(state[0]),
    .Q(data_reg[27]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[28]  /* _074_ */ (
    .C(clk),
    .D(data_reg_128[28]),
    .E(state[0]),
    .Q(data_reg[28]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[29]  /* _075_ */ (
    .C(clk),
    .D(data_reg_128[29]),
    .E(state[0]),
    .Q(data_reg[29]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[30]  /* _076_ */ (
    .C(clk),
    .D(data_reg_128[30]),
    .E(state[0]),
    .Q(data_reg[30]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0N_  \data_reg_reg[31]  /* _077_ */ (
    .C(clk),
    .D(data_reg_128[31]),
    .E(state[0]),
    .Q(data_reg[31]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:28.1-39.4" *)
  \$_DFFE_PN0P_  \state_reg[0]  /* _078_ */ (
    .C(clk),
    .D(1'h1),
    .E(_000_),
    .Q(state[0]),
    .R(reset)
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[0]  /* _079_ */ (
    .D(data_reg[0]),
    .E(state[0]),
    .Q(data_reg_128[0])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[1]  /* _080_ */ (
    .D(data_reg[1]),
    .E(state[0]),
    .Q(data_reg_128[1])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[2]  /* _081_ */ (
    .D(data_reg[2]),
    .E(state[0]),
    .Q(data_reg_128[2])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[3]  /* _082_ */ (
    .D(data_reg[3]),
    .E(state[0]),
    .Q(data_reg_128[3])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[4]  /* _083_ */ (
    .D(data_reg[4]),
    .E(state[0]),
    .Q(data_reg_128[4])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[5]  /* _084_ */ (
    .D(data_reg[5]),
    .E(state[0]),
    .Q(data_reg_128[5])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[6]  /* _085_ */ (
    .D(data_reg[6]),
    .E(state[0]),
    .Q(data_reg_128[6])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[7]  /* _086_ */ (
    .D(data_reg[7]),
    .E(state[0]),
    .Q(data_reg_128[7])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[8]  /* _087_ */ (
    .D(data_reg[8]),
    .E(state[0]),
    .Q(data_reg_128[8])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[9]  /* _088_ */ (
    .D(data_reg[9]),
    .E(state[0]),
    .Q(data_reg_128[9])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[10]  /* _089_ */ (
    .D(data_reg[10]),
    .E(state[0]),
    .Q(data_reg_128[10])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[11]  /* _090_ */ (
    .D(data_reg[11]),
    .E(state[0]),
    .Q(data_reg_128[11])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[12]  /* _091_ */ (
    .D(data_reg[12]),
    .E(state[0]),
    .Q(data_reg_128[12])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[13]  /* _092_ */ (
    .D(data_reg[13]),
    .E(state[0]),
    .Q(data_reg_128[13])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[14]  /* _093_ */ (
    .D(data_reg[14]),
    .E(state[0]),
    .Q(data_reg_128[14])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[15]  /* _094_ */ (
    .D(data_reg[15]),
    .E(state[0]),
    .Q(data_reg_128[15])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[16]  /* _095_ */ (
    .D(data_reg[16]),
    .E(state[0]),
    .Q(data_reg_128[16])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[17]  /* _096_ */ (
    .D(data_reg[17]),
    .E(state[0]),
    .Q(data_reg_128[17])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[18]  /* _097_ */ (
    .D(data_reg[18]),
    .E(state[0]),
    .Q(data_reg_128[18])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[19]  /* _098_ */ (
    .D(data_reg[19]),
    .E(state[0]),
    .Q(data_reg_128[19])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[20]  /* _099_ */ (
    .D(data_reg[20]),
    .E(state[0]),
    .Q(data_reg_128[20])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[21]  /* _100_ */ (
    .D(data_reg[21]),
    .E(state[0]),
    .Q(data_reg_128[21])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[22]  /* _101_ */ (
    .D(data_reg[22]),
    .E(state[0]),
    .Q(data_reg_128[22])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[23]  /* _102_ */ (
    .D(data_reg[23]),
    .E(state[0]),
    .Q(data_reg_128[23])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[24]  /* _103_ */ (
    .D(data_reg[24]),
    .E(state[0]),
    .Q(data_reg_128[24])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[25]  /* _104_ */ (
    .D(data_reg[25]),
    .E(state[0]),
    .Q(data_reg_128[25])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[26]  /* _105_ */ (
    .D(data_reg[26]),
    .E(state[0]),
    .Q(data_reg_128[26])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[27]  /* _106_ */ (
    .D(data_reg[27]),
    .E(state[0]),
    .Q(data_reg_128[27])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[28]  /* _107_ */ (
    .D(data_reg[28]),
    .E(state[0]),
    .Q(data_reg_128[28])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[29]  /* _108_ */ (
    .D(data_reg[29]),
    .E(state[0]),
    .Q(data_reg_128[29])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[30]  /* _109_ */ (
    .D(data_reg[30]),
    .E(state[0]),
    .Q(data_reg_128[30])
  );
  (* src = "dut.sv:45.1-80.4" *)
  \$_DLATCH_N_  \data_reg_128_reg[31]  /* _110_ */ (
    .D(data_reg[31]),
    .E(state[0]),
    .Q(data_reg_128[31])
  );
  assign \data_reg_var[3]  = data_reg[7:0];
  assign \data_reg_var[2]  = data_reg[15:8];
  assign \data_reg_var[1]  = data_reg[23:16];
  assign \data_reg_var[0]  = data_reg[31:24];
  assign \data_array[3]  = data_i[7:0];
  assign \data_array[2]  = data_i[15:8];
  assign \data_array[1]  = data_i[23:16];
  assign \data_array[0]  = data_i[31:24];
  assign data_i_var = data_i;
  assign next_ready_o = 1'h0;
  assign next_state = 2'h1;
  assign state[1] = 1'h0;
  assign sbox_decrypt_o = decrypt_i;
  assign data_o = data_reg;
  assign ready_o = 1'h0;
endmodule
