/* Generated by Yosys 0.62+39 (git sha1 131911291-dirty, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* keep =  1  *)
(* dynports =  1  *)
(* src = "dut.sv:1.1-48.10" *)
(* top =  1  *)
module top();
  (* src = "dut.sv:16.4-16.9" *)
  wire [63:0] pack1;
  (* src = "dut.sv:9.4-9.5" *)
  wire [18:0] s;
  (* src = "dut.sv:23.4-23.6" *)
  wire [23:0] s2;
  (* src = "dut.sv:29.13-29.14" *)
  wire [7:0] t;
  (* src = "dut.sv:41.14-41.36" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967295),
    .TRG_ENABLE(32'd0),
    .TRG_POLARITY(),
    .TRG_WIDTH(32'd0)
  ) _0_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG()
  );
  assign t = 8'hff;
  assign s2 = 24'hxx42xx;
  assign pack1 = 64'h0000002aaaaaff55;
  assign s = 19'b111111111101010101x;
endmodule
