/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:6.1-16.10" *)
module DataProcessor(clk, data_in, data_out, internal_ready);
  (* src = "dut.sv:7.23-7.26" *)
  input clk;
  wire clk;
  (* src = "dut.sv:8.23-8.30" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "dut.sv:9.23-9.31" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  (* src = "dut.sv:11.9-11.23" *)
  output internal_ready;
  wire internal_ready;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:13.21-13.36|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _12_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:13.21-13.36|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _13_;
  \$_NOT_  _14_ (
    .A(data_in[0]),
    .Y(_12_[0])
  );
  \$_AND_  _15_ (
    .A(data_in[1]),
    .B(data_in[0]),
    .Y(_01_)
  );
  \$_AND_  _16_ (
    .A(data_in[2]),
    .B(_01_),
    .Y(_02_)
  );
  \$_AND_  _17_ (
    .A(data_in[3]),
    .B(_02_),
    .Y(_03_)
  );
  \$_AND_  _18_ (
    .A(data_in[4]),
    .B(_03_),
    .Y(_04_)
  );
  \$_AND_  _19_ (
    .A(data_in[5]),
    .B(_04_),
    .Y(_05_)
  );
  \$_NAND_  _20_ (
    .A(data_in[6]),
    .B(_05_),
    .Y(_06_)
  );
  \$_XNOR_  _21_ (
    .A(data_in[7]),
    .B(_06_),
    .Y(_13_[7])
  );
  \$_XOR_  _22_ (
    .A(data_in[6]),
    .B(_05_),
    .Y(_13_[6])
  );
  \$_XOR_  _23_ (
    .A(data_in[5]),
    .B(_04_),
    .Y(_13_[5])
  );
  \$_XOR_  _24_ (
    .A(data_in[4]),
    .B(_03_),
    .Y(_13_[4])
  );
  \$_XOR_  _25_ (
    .A(data_in[3]),
    .B(_02_),
    .Y(_13_[3])
  );
  \$_OR_  _26_ (
    .A(data_in[2]),
    .B(_01_),
    .Y(_07_)
  );
  \$_XOR_  _27_ (
    .A(data_in[2]),
    .B(_01_),
    .Y(_13_[2])
  );
  \$_XOR_  _28_ (
    .A(data_in[1]),
    .B(data_in[0]),
    .Y(_13_[1])
  );
  \$_NAND_  _29_ (
    .A(data_in[3]),
    .B(_07_),
    .Y(_08_)
  );
  \$_NOR_  _30_ (
    .A(data_in[6]),
    .B(data_in[4]),
    .Y(_09_)
  );
  \$_NOR_  _31_ (
    .A(data_in[5]),
    .B(data_in[7]),
    .Y(_10_)
  );
  \$_AND_  _32_ (
    .A(_09_),
    .B(_10_),
    .Y(_11_)
  );
  \$_NAND_  _33_ (
    .A(_08_),
    .B(_11_),
    .Y(_00_)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:12.5-15.8" *)
  \$_DFF_P_  \data_out_reg[0]  /* _34_ */ (
    .C(clk),
    .D(_12_[0]),
    .Q(data_out[0])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:12.5-15.8" *)
  \$_DFF_P_  \data_out_reg[1]  /* _35_ */ (
    .C(clk),
    .D(_13_[1]),
    .Q(data_out[1])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:12.5-15.8" *)
  \$_DFF_P_  \data_out_reg[2]  /* _36_ */ (
    .C(clk),
    .D(_13_[2]),
    .Q(data_out[2])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:12.5-15.8" *)
  \$_DFF_P_  \data_out_reg[3]  /* _37_ */ (
    .C(clk),
    .D(_13_[3]),
    .Q(data_out[3])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:12.5-15.8" *)
  \$_DFF_P_  \data_out_reg[4]  /* _38_ */ (
    .C(clk),
    .D(_13_[4]),
    .Q(data_out[4])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:12.5-15.8" *)
  \$_DFF_P_  \data_out_reg[5]  /* _39_ */ (
    .C(clk),
    .D(_13_[5]),
    .Q(data_out[5])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:12.5-15.8" *)
  \$_DFF_P_  \data_out_reg[6]  /* _40_ */ (
    .C(clk),
    .D(_13_[6]),
    .Q(data_out[6])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:12.5-15.8" *)
  \$_DFF_P_  \data_out_reg[7]  /* _41_ */ (
    .C(clk),
    .D(_13_[7]),
    .Q(data_out[7])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:12.5-15.8" *)
  \$_DFF_P_  internal_ready_reg /* _42_ */ (
    .C(clk),
    .D(_00_),
    .Q(internal_ready)
  );
  assign _13_[0] = _12_[0];
  assign _12_[7:1] = data_in[7:1];
endmodule

(* src = "dut.sv:18.1-30.10" *)
(* top =  1  *)
module dut(clk, system_in, system_out, monitor_flag);
  (* src = "dut.sv:19.23-19.26" *)
  input clk;
  wire clk;
  (* src = "dut.sv:20.23-20.32" *)
  input [7:0] system_in;
  wire [7:0] system_in;
  (* src = "dut.sv:21.23-21.33" *)
  output [7:0] system_out;
  wire [7:0] system_out;
  (* src = "dut.sv:22.23-22.35" *)
  output monitor_flag;
  wire monitor_flag;
  wire \u_processor.internal_ready ;
  DataProcessor u_processor (
    .clk(clk),
    .data_in(system_in),
    .data_out(system_out),
    .internal_ready(\u_processor.internal_ready )
  );
  assign monitor_flag = \u_processor.internal_ready ;
endmodule
