/* Generated by Yosys 0.62+39 (git sha1 131911291-dirty, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* src = "dut.sv:1.1-58.10" *)
(* top =  1  *)
module fsm_test(clk, reset, button_a, button_b, red_a, green_a, red_b, green_b);
  (* src = "dut.sv:1.17-1.20" *)
  input clk;
  wire clk;
  (* src = "dut.sv:1.22-1.27" *)
  input reset;
  wire reset;
  (* src = "dut.sv:1.29-1.37" *)
  input button_a;
  wire button_a;
  (* src = "dut.sv:1.39-1.47" *)
  input button_b;
  wire button_b;
  (* src = "dut.sv:1.49-1.54" *)
  output red_a;
  wire red_a;
  (* src = "dut.sv:1.56-1.63" *)
  output green_a;
  wire green_a;
  (* src = "dut.sv:1.65-1.70" *)
  output red_b;
  wire red_b;
  (* src = "dut.sv:1.72-1.79" *)
  output green_b;
  wire green_b;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  (* force_downto = 32'd1 *)
  (* src = "/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _057_;
  (* force_downto = 32'd1 *)
  (* src = "/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _058_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:48.13-54.16|dut.sv:20.9-55.16|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [0:0] _059_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:34.13-40.16|dut.sv:20.9-55.16|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [0:0] _060_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:48.13-54.16|dut.sv:20.9-55.16|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [5:0] _061_;
  (* \reg  = 32'd1 *)
  (* src = "dut.sv:7.11-7.14" *)
  wire [3:0] cnt;
  (* src = "dut.sv:6.9-6.14" *)
  wire [31:0] state;
  \$_ANDNOT_  _062_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_002_)
  );
  \$_ANDNOT_  _063_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_003_)
  );
  \$_OR_  _064_ (
    .A(_003_),
    .B(_002_),
    .Y(_058_[1])
  );
  \$_AND_  _065_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_004_)
  );
  \$_AND_  _066_ (
    .A(_004_),
    .B(cnt[2]),
    .Y(_005_)
  );
  \$_XOR_  _067_ (
    .A(_005_),
    .B(cnt[3]),
    .Y(_058_[3])
  );
  \$_ORNOT_  _068_ (
    .A(state[5]),
    .B(state[4]),
    .Y(_006_)
  );
  \$_ORNOT_  _069_ (
    .A(state[3]),
    .B(state[4]),
    .Y(_007_)
  );
  \$_OR_  _070_ (
    .A(_007_),
    .B(_006_),
    .Y(_008_)
  );
  \$_ORNOT_  _071_ (
    .A(state[5]),
    .B(state[6]),
    .Y(_009_)
  );
  \$_ORNOT_  _072_ (
    .A(state[8]),
    .B(state[7]),
    .Y(_010_)
  );
  \$_OR_  _073_ (
    .A(_010_),
    .B(_009_),
    .Y(_011_)
  );
  \$_OR_  _074_ (
    .A(_011_),
    .B(_008_),
    .Y(_012_)
  );
  \$_ANDNOT_  _075_ (
    .A(cnt[0]),
    .B(_012_),
    .Y(_013_)
  );
  \$_OR_  _076_ (
    .A(state[4]),
    .B(state[5]),
    .Y(_014_)
  );
  \$_ORNOT_  _077_ (
    .A(state[4]),
    .B(state[3]),
    .Y(_015_)
  );
  \$_OR_  _078_ (
    .A(_015_),
    .B(_014_),
    .Y(_016_)
  );
  \$_NOR_  _079_ (
    .A(_016_),
    .B(_011_),
    .Y(_017_)
  );
  \$_OR_  _080_ (
    .A(_017_),
    .B(_013_),
    .Y(_018_)
  );
  \$_ANDNOT_  _081_ (
    .A(_012_),
    .B(_017_),
    .Y(_056_)
  );
  \$_ANDNOT_  _082_ (
    .A(_018_),
    .B(_056_),
    .Y(_060_)
  );
  \$_NOT_  _083_ (
    .A(cnt[0]),
    .Y(_057_[0])
  );
  \$_NAND_  _084_ (
    .A(state[4]),
    .B(state[5]),
    .Y(_019_)
  );
  \$_NOR_  _085_ (
    .A(_019_),
    .B(_007_),
    .Y(_020_)
  );
  \$_ORNOT_  _086_ (
    .A(state[6]),
    .B(state[5]),
    .Y(_021_)
  );
  \$_ORNOT_  _087_ (
    .A(state[7]),
    .B(state[8]),
    .Y(_022_)
  );
  \$_OR_  _088_ (
    .A(_022_),
    .B(_021_),
    .Y(_023_)
  );
  \$_ANDNOT_  _089_ (
    .A(_020_),
    .B(_023_),
    .Y(_024_)
  );
  \$_ANDNOT_  _090_ (
    .A(_024_),
    .B(_057_[0]),
    .Y(_025_)
  );
  \$_ANDNOT_  _091_ (
    .A(state[5]),
    .B(state[4]),
    .Y(_026_)
  );
  \$_ORNOT_  _092_ (
    .A(_015_),
    .B(_026_),
    .Y(_027_)
  );
  \$_NOR_  _093_ (
    .A(_027_),
    .B(_023_),
    .Y(_028_)
  );
  \$_OR_  _094_ (
    .A(_028_),
    .B(_025_),
    .Y(_029_)
  );
  \$_NOR_  _095_ (
    .A(_028_),
    .B(_024_),
    .Y(_055_)
  );
  \$_ANDNOT_  _096_ (
    .A(_029_),
    .B(_055_),
    .Y(_059_)
  );
  \$_ANDNOT_  _097_ (
    .A(_012_),
    .B(_024_),
    .Y(_030_)
  );
  \$_OR_  _098_ (
    .A(_028_),
    .B(_017_),
    .Y(_061_[0])
  );
  \$_XOR_  _099_ (
    .A(_004_),
    .B(cnt[2]),
    .Y(_058_[2])
  );
  \$_ORNOT_  _100_ (
    .A(_028_),
    .B(_030_),
    .Y(_031_)
  );
  \$_NOR_  _101_ (
    .A(_031_),
    .B(_017_),
    .Y(_061_[2])
  );
  \$_ANDNOT_  _102_ (
    .A(button_b),
    .B(button_a),
    .Y(_032_)
  );
  \$_NOT_  _103_ (
    .A(_032_),
    .Y(_033_)
  );
  \$_ORNOT_  _104_ (
    .A(_017_),
    .B(_030_),
    .Y(_034_)
  );
  \$_MUX_  _105_ (
    .A(_034_),
    .B(_033_),
    .S(_061_[2]),
    .Y(_061_[3])
  );
  \$_MUX_  _106_ (
    .A(_028_),
    .B(_032_),
    .S(_061_[2]),
    .Y(_061_[5])
  );
  \$_MUX_  _107_ (
    .A(_031_),
    .B(_032_),
    .S(_061_[2]),
    .Y(_061_[1])
  );
  \$_AND_  _108_ (
    .A(_055_),
    .B(_056_),
    .Y(_035_)
  );
  \$_OR_  _109_ (
    .A(_035_),
    .B(reset),
    .Y(_001_)
  );
  \$_MUX_  _110_ (
    .A(_017_),
    .B(_033_),
    .S(_061_[2]),
    .Y(_061_[4])
  );
  \$_ORNOT_  _111_ (
    .A(cnt[2]),
    .B(cnt[3]),
    .Y(_036_)
  );
  \$_ANDNOT_  _112_ (
    .A(_003_),
    .B(_036_),
    .Y(_037_)
  );
  \$_OR_  _113_ (
    .A(_037_),
    .B(_030_),
    .Y(_038_)
  );
  \$_OR_  _114_ (
    .A(state[4]),
    .B(state[3]),
    .Y(_039_)
  );
  \$_ANDNOT_  _115_ (
    .A(_026_),
    .B(_039_),
    .Y(_040_)
  );
  \$_NAND_  _116_ (
    .A(state[5]),
    .B(state[6]),
    .Y(_041_)
  );
  \$_OR_  _117_ (
    .A(state[8]),
    .B(state[7]),
    .Y(_042_)
  );
  \$_OR_  _118_ (
    .A(_042_),
    .B(_041_),
    .Y(_043_)
  );
  \$_ANDNOT_  _119_ (
    .A(_040_),
    .B(_043_),
    .Y(_044_)
  );
  \$_ANDNOT_  _120_ (
    .A(_035_),
    .B(_044_),
    .Y(_045_)
  );
  \$_ANDNOT_  _121_ (
    .A(_038_),
    .B(_045_),
    .Y(_046_)
  );
  \$_ORNOT_  _122_ (
    .A(cnt[3]),
    .B(cnt[2]),
    .Y(_047_)
  );
  \$_ANDNOT_  _123_ (
    .A(_002_),
    .B(_047_),
    .Y(_048_)
  );
  \$_ANDNOT_  _124_ (
    .A(_017_),
    .B(_048_),
    .Y(_049_)
  );
  \$_ANDNOT_  _125_ (
    .A(_028_),
    .B(_048_),
    .Y(_050_)
  );
  \$_OR_  _126_ (
    .A(_050_),
    .B(_049_),
    .Y(_051_)
  );
  \$_ANDNOT_  _127_ (
    .A(_046_),
    .B(_051_),
    .Y(_052_)
  );
  \$_XOR_  _128_ (
    .A(button_a),
    .B(button_b),
    .Y(_053_)
  );
  \$_ANDNOT_  _129_ (
    .A(_044_),
    .B(_053_),
    .Y(_054_)
  );
  \$_ANDNOT_  _130_ (
    .A(_052_),
    .B(_054_),
    .Y(_000_)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFFE_PP0P_  \state_reg[3]  /* _131_ */ (
    .C(clk),
    .D(_061_[2]),
    .E(_000_),
    .Q(state[3]),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFFE_PP0P_  \state_reg[4]  /* _132_ */ (
    .C(clk),
    .D(_061_[0]),
    .E(_000_),
    .Q(state[4]),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFFE_PP1P_  \state_reg[5]  /* _133_ */ (
    .C(clk),
    .D(_061_[1]),
    .E(_000_),
    .Q(state[5]),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFFE_PP1P_  \state_reg[6]  /* _134_ */ (
    .C(clk),
    .D(_061_[3]),
    .E(_000_),
    .Q(state[6]),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFFE_PP0P_  \state_reg[7]  /* _135_ */ (
    .C(clk),
    .D(_061_[4]),
    .E(_000_),
    .Q(state[7]),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFFE_PP0P_  \state_reg[8]  /* _136_ */ (
    .C(clk),
    .D(_061_[5]),
    .E(_000_),
    .Q(state[8]),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFF_PP1_  red_b_reg /* _137_ */ (
    .C(clk),
    .D(_055_),
    .Q(red_b),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFF_PP1_  red_a_reg /* _138_ */ (
    .C(clk),
    .D(_056_),
    .Q(red_a),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFF_PP0_  green_b_reg /* _139_ */ (
    .C(clk),
    .D(_059_),
    .Q(green_b),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFF_PP0_  green_a_reg /* _140_ */ (
    .C(clk),
    .D(_060_),
    .Q(green_a),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFF_PP0_  \cnt_reg[0]  /* _141_ */ (
    .C(clk),
    .D(_057_[0]),
    .Q(cnt[0]),
    .R(_001_)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFF_PP0_  \cnt_reg[1]  /* _142_ */ (
    .C(clk),
    .D(_058_[1]),
    .Q(cnt[1]),
    .R(_001_)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFF_PP0_  \cnt_reg[2]  /* _143_ */ (
    .C(clk),
    .D(_058_[2]),
    .Q(cnt[2]),
    .R(_001_)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:9.1-56.4" *)
  \$_SDFF_PP0_  \cnt_reg[3]  /* _144_ */ (
    .C(clk),
    .D(_058_[3]),
    .Q(cnt[3]),
    .R(_001_)
  );
  assign _058_[0] = _057_[0];
  assign _057_[3:1] = cnt[3:1];
  assign { state[31:9], state[2:0] } = { 23'h000000, state[5:4], 1'h0 };
endmodule
