/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* dynports =  1  *)
(* top =  1  *)
(* src = "dut.sv:2.1-35.10" *)
module blockrom(clk, address_in, data_out);
  (* src = "dut.sv:3.37-3.40" *)
  input clk;
  wire clk;
  (* src = "dut.sv:4.36-4.46" *)
  input [2:0] address_in;
  wire [2:0] address_in;
  (* src = "dut.sv:5.36-5.44" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  (* unused_bits = "1 6 7" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "dut.sv:10.15-10.25" *)
  wire [7:0] data_out_r;
  (* src = "dut.sv:13.10-13.11" *)
  wire signed [31:0] i;
  (* src = "dut.sv:13.12-13.13" *)
  wire signed [31:0] j;
  \$_NOT_  _12_ (
    .A(address_in[0]),
    .Y(_03_)
  );
  \$_ORNOT_  _13_ (
    .A(address_in[0]),
    .B(address_in[1]),
    .Y(_04_)
  );
  \$_ANDNOT_  _14_ (
    .A(address_in[0]),
    .B(address_in[1]),
    .Y(_05_)
  );
  \$_ORNOT_  _15_ (
    .A(address_in[2]),
    .B(address_in[1]),
    .Y(_02_)
  );
  \$_OR_  _16_ (
    .A(address_in[2]),
    .B(_05_),
    .Y(_06_)
  );
  \$_NAND_  _17_ (
    .A(_04_),
    .B(_06_),
    .Y(_00_[5])
  );
  \$_AND_  _18_ (
    .A(address_in[1]),
    .B(address_in[2]),
    .Y(_01_)
  );
  \$_NAND_  _19_ (
    .A(address_in[0]),
    .B(_02_),
    .Y(_07_)
  );
  \$_ORNOT_  _20_ (
    .A(_06_),
    .B(_04_),
    .Y(_08_)
  );
  \$_AND_  _21_ (
    .A(_04_),
    .B(_07_),
    .Y(_00_[4])
  );
  \$_NAND_  _22_ (
    .A(address_in[1]),
    .B(address_in[0]),
    .Y(_09_)
  );
  \$_NAND_  _23_ (
    .A(address_in[2]),
    .B(_09_),
    .Y(_10_)
  );
  \$_NAND_  _24_ (
    .A(_08_),
    .B(_10_),
    .Y(_00_[3])
  );
  \$_XOR_  _25_ (
    .A(address_in[1]),
    .B(address_in[2]),
    .Y(_11_)
  );
  \$_AND_  _26_ (
    .A(_03_),
    .B(_11_),
    .Y(_00_[0])
  );
  \$_ORNOT_  _27_ (
    .A(_01_),
    .B(_09_),
    .Y(_00_[2])
  );
  \$_DFF_P_  \data_out_r_reg[0]  /* _28_ */ (
    .C(clk),
    .D(_00_[0]),
    .Q(data_out_r[0])
  );
  \$_DFF_P_  \data_out_r_reg[2]  /* _29_ */ (
    .C(clk),
    .D(_00_[2]),
    .Q(data_out_r[2])
  );
  \$_DFF_P_  \data_out_r_reg[3]  /* _30_ */ (
    .C(clk),
    .D(_00_[3]),
    .Q(data_out_r[3])
  );
  \$_DFF_P_  \data_out_r_reg[4]  /* _31_ */ (
    .C(clk),
    .D(_00_[4]),
    .Q(data_out_r[4])
  );
  \$_DFF_P_  \data_out_r_reg[5]  /* _32_ */ (
    .C(clk),
    .D(_00_[5]),
    .Q(data_out_r[5])
  );
  \$_SDFF_PP0_  \data_out_r_reg[7]  /* _33_ */ (
    .C(clk),
    .D(address_in[0]),
    .Q(data_out_r[7]),
    .R(address_in[2])
  );
  \$_SDFF_PP1_  \data_out_r_reg[6]  /* _34_ */ (
    .C(clk),
    .D(_03_),
    .Q(data_out_r[6]),
    .R(_02_)
  );
  \$_SDFF_PN1_  \data_out_r_reg[1]  /* _35_ */ (
    .C(clk),
    .D(address_in[0]),
    .Q(data_out_r[1]),
    .R(_01_)
  );
  assign j = 32'd2810991328;
  assign i = 32'd8;
  assign data_out = data_out_r;
endmodule
