/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* dynports =  1  *)
(* src = "ibex_branch_predict.sv:20.1-100.10" *)
(* top =  1  *)
module ibex_branch_predict(clk_i, rst_ni, fetch_rdata_i, fetch_pc_i, fetch_valid_i, predict_branch_taken_o, predict_branch_pc_o);
  (* src = "ibex_branch_predict.sv:21.16-21.21" *)
  input clk_i;
  wire clk_i;
  (* src = "ibex_branch_predict.sv:22.16-22.22" *)
  input rst_ni;
  wire rst_ni;
  (* src = "ibex_branch_predict.sv:25.23-25.36" *)
  input [31:0] fetch_rdata_i;
  wire [31:0] fetch_rdata_i;
  (* src = "ibex_branch_predict.sv:26.23-26.33" *)
  input [31:0] fetch_pc_i;
  wire [31:0] fetch_pc_i;
  (* src = "ibex_branch_predict.sv:27.23-27.36" *)
  input fetch_valid_i;
  wire fetch_valid_i;
  (* src = "ibex_branch_predict.sv:30.23-30.45" *)
  output predict_branch_taken_o;
  wire predict_branch_taken_o;
  (* src = "ibex_branch_predict.sv:31.23-31.42" *)
  output [31:0] predict_branch_pc_o;
  wire [31:0] predict_branch_pc_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  (* src = "ibex_branch_predict.sv:40.16-40.26" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] branch_imm;
  (* src = "ibex_branch_predict.sv:36.16-36.26" *)
  wire [31:0] imm_b_type;
  (* src = "ibex_branch_predict.sv:38.16-38.27" *)
  wire [31:0] imm_cb_type;
  (* src = "ibex_branch_predict.sv:37.16-37.27" *)
  wire [31:0] imm_cj_type;
  (* src = "ibex_branch_predict.sv:35.16-35.26" *)
  wire [31:0] imm_j_type;
  (* src = "ibex_branch_predict.sv:42.16-42.21" *)
  wire [31:0] instr;
  \$_ANDNOT_  _216_ (
    .A(fetch_rdata_i[0]),
    .B(fetch_rdata_i[1]),
    .Y(_213_)
  );
  \$_AND_  _217_ (
    .A(fetch_rdata_i[15]),
    .B(fetch_rdata_i[14]),
    .Y(_214_)
  );
  \$_AND_  _218_ (
    .A(_213_),
    .B(_214_),
    .Y(_215_)
  );
  \$_ANDNOT_  _219_ (
    .A(fetch_rdata_i[13]),
    .B(fetch_rdata_i[14]),
    .Y(_000_)
  );
  \$_AND_  _220_ (
    .A(_213_),
    .B(_000_),
    .Y(_001_)
  );
  \$_OR_  _221_ (
    .A(_215_),
    .B(_001_),
    .Y(_002_)
  );
  \$_NAND_  _222_ (
    .A(fetch_rdata_i[12]),
    .B(_002_),
    .Y(_003_)
  );
  \$_MUX_  _223_ (
    .A(fetch_rdata_i[31]),
    .B(fetch_rdata_i[12]),
    .S(_002_),
    .Y(_004_)
  );
  \$_NAND_  _224_ (
    .A(fetch_pc_i[30]),
    .B(_004_),
    .Y(_005_)
  );
  \$_OR_  _225_ (
    .A(fetch_pc_i[30]),
    .B(_004_),
    .Y(_006_)
  );
  \$_NAND_  _226_ (
    .A(fetch_pc_i[29]),
    .B(_004_),
    .Y(_007_)
  );
  \$_NAND_  _227_ (
    .A(fetch_pc_i[28]),
    .B(_004_),
    .Y(_008_)
  );
  \$_XOR_  _228_ (
    .A(fetch_pc_i[28]),
    .B(_004_),
    .Y(_009_)
  );
  \$_NAND_  _229_ (
    .A(fetch_pc_i[27]),
    .B(_004_),
    .Y(_010_)
  );
  \$_XOR_  _230_ (
    .A(fetch_pc_i[27]),
    .B(_004_),
    .Y(_011_)
  );
  \$_NAND_  _231_ (
    .A(_009_),
    .B(_011_),
    .Y(_012_)
  );
  \$_NAND_  _232_ (
    .A(fetch_pc_i[24]),
    .B(_004_),
    .Y(_013_)
  );
  \$_XOR_  _233_ (
    .A(fetch_pc_i[24]),
    .B(_004_),
    .Y(_014_)
  );
  \$_NAND_  _234_ (
    .A(fetch_pc_i[23]),
    .B(_004_),
    .Y(_015_)
  );
  \$_XOR_  _235_ (
    .A(fetch_pc_i[23]),
    .B(_004_),
    .Y(_016_)
  );
  \$_NAND_  _236_ (
    .A(_014_),
    .B(_016_),
    .Y(_017_)
  );
  \$_NAND_  _237_ (
    .A(fetch_pc_i[22]),
    .B(_004_),
    .Y(_018_)
  );
  \$_XOR_  _238_ (
    .A(fetch_pc_i[22]),
    .B(_004_),
    .Y(_019_)
  );
  \$_NAND_  _239_ (
    .A(fetch_pc_i[21]),
    .B(_004_),
    .Y(_020_)
  );
  \$_XOR_  _240_ (
    .A(fetch_pc_i[21]),
    .B(_004_),
    .Y(_021_)
  );
  \$_NAND_  _241_ (
    .A(fetch_pc_i[20]),
    .B(_004_),
    .Y(_022_)
  );
  \$_OR_  _242_ (
    .A(fetch_pc_i[20]),
    .B(_004_),
    .Y(_023_)
  );
  \$_AND_  _243_ (
    .A(fetch_rdata_i[6]),
    .B(fetch_rdata_i[5]),
    .Y(_024_)
  );
  \$_ANDNOT_  _244_ (
    .A(_024_),
    .B(fetch_rdata_i[4]),
    .Y(_025_)
  );
  \$_AND_  _245_ (
    .A(fetch_rdata_i[1]),
    .B(fetch_rdata_i[0]),
    .Y(_026_)
  );
  \$_AND_  _246_ (
    .A(fetch_rdata_i[2]),
    .B(fetch_rdata_i[3]),
    .Y(_027_)
  );
  \$_AND_  _247_ (
    .A(_026_),
    .B(_027_),
    .Y(_028_)
  );
  \$_AND_  _248_ (
    .A(_025_),
    .B(_028_),
    .Y(_029_)
  );
  \$_NAND_  _249_ (
    .A(fetch_rdata_i[19]),
    .B(_029_),
    .Y(_030_)
  );
  \$_NOR_  _250_ (
    .A(_001_),
    .B(_029_),
    .Y(_031_)
  );
  \$_NOR_  _251_ (
    .A(_002_),
    .B(_029_),
    .Y(_032_)
  );
  \$_NAND_  _252_ (
    .A(fetch_rdata_i[31]),
    .B(_032_),
    .Y(_033_)
  );
  \$_AND_  _253_ (
    .A(_003_),
    .B(_033_),
    .Y(_034_)
  );
  \$_NAND_  _254_ (
    .A(_030_),
    .B(_034_),
    .Y(_035_)
  );
  \$_NAND_  _255_ (
    .A(fetch_pc_i[19]),
    .B(_035_),
    .Y(_036_)
  );
  \$_XOR_  _256_ (
    .A(fetch_pc_i[19]),
    .B(_035_),
    .Y(_037_)
  );
  \$_NAND_  _257_ (
    .A(fetch_rdata_i[18]),
    .B(_029_),
    .Y(_038_)
  );
  \$_NAND_  _258_ (
    .A(_034_),
    .B(_038_),
    .Y(_039_)
  );
  \$_NAND_  _259_ (
    .A(fetch_pc_i[18]),
    .B(_039_),
    .Y(_040_)
  );
  \$_XOR_  _260_ (
    .A(fetch_pc_i[18]),
    .B(_039_),
    .Y(_041_)
  );
  \$_NAND_  _261_ (
    .A(fetch_rdata_i[17]),
    .B(_029_),
    .Y(_042_)
  );
  \$_NAND_  _262_ (
    .A(_034_),
    .B(_042_),
    .Y(_043_)
  );
  \$_NAND_  _263_ (
    .A(fetch_pc_i[17]),
    .B(_043_),
    .Y(_044_)
  );
  \$_XOR_  _264_ (
    .A(fetch_pc_i[17]),
    .B(_043_),
    .Y(_045_)
  );
  \$_NAND_  _265_ (
    .A(fetch_rdata_i[16]),
    .B(_029_),
    .Y(_046_)
  );
  \$_NAND_  _266_ (
    .A(_034_),
    .B(_046_),
    .Y(_047_)
  );
  \$_NAND_  _267_ (
    .A(fetch_pc_i[16]),
    .B(_047_),
    .Y(_048_)
  );
  \$_OR_  _268_ (
    .A(fetch_pc_i[16]),
    .B(_047_),
    .Y(_049_)
  );
  \$_NAND_  _269_ (
    .A(fetch_rdata_i[15]),
    .B(_029_),
    .Y(_050_)
  );
  \$_NAND_  _270_ (
    .A(_034_),
    .B(_050_),
    .Y(_051_)
  );
  \$_NAND_  _271_ (
    .A(fetch_pc_i[15]),
    .B(_051_),
    .Y(_052_)
  );
  \$_XOR_  _272_ (
    .A(fetch_pc_i[15]),
    .B(_051_),
    .Y(_053_)
  );
  \$_NAND_  _273_ (
    .A(fetch_rdata_i[14]),
    .B(_029_),
    .Y(_054_)
  );
  \$_NAND_  _274_ (
    .A(_034_),
    .B(_054_),
    .Y(_055_)
  );
  \$_OR_  _275_ (
    .A(fetch_pc_i[14]),
    .B(_055_),
    .Y(_056_)
  );
  \$_NAND_  _276_ (
    .A(fetch_pc_i[14]),
    .B(_055_),
    .Y(_057_)
  );
  \$_NAND_  _277_ (
    .A(fetch_rdata_i[13]),
    .B(_029_),
    .Y(_058_)
  );
  \$_NAND_  _278_ (
    .A(_034_),
    .B(_058_),
    .Y(_059_)
  );
  \$_NAND_  _279_ (
    .A(fetch_pc_i[13]),
    .B(_059_),
    .Y(_060_)
  );
  \$_XOR_  _280_ (
    .A(fetch_pc_i[13]),
    .B(_059_),
    .Y(_061_)
  );
  \$_MUX_  _281_ (
    .A(fetch_rdata_i[12]),
    .B(fetch_rdata_i[31]),
    .S(_032_),
    .Y(_062_)
  );
  \$_OR_  _282_ (
    .A(fetch_pc_i[12]),
    .B(_062_),
    .Y(_063_)
  );
  \$_NAND_  _283_ (
    .A(fetch_pc_i[12]),
    .B(_062_),
    .Y(_064_)
  );
  \$_NAND_  _284_ (
    .A(fetch_rdata_i[7]),
    .B(_032_),
    .Y(_065_)
  );
  \$_NAND_  _285_ (
    .A(fetch_rdata_i[20]),
    .B(_029_),
    .Y(_066_)
  );
  \$_AND_  _286_ (
    .A(_003_),
    .B(_066_),
    .Y(_067_)
  );
  \$_NAND_  _287_ (
    .A(_065_),
    .B(_067_),
    .Y(_068_)
  );
  \$_NAND_  _288_ (
    .A(fetch_pc_i[11]),
    .B(_068_),
    .Y(_069_)
  );
  \$_XOR_  _289_ (
    .A(fetch_pc_i[11]),
    .B(_068_),
    .Y(_070_)
  );
  \$_ANDNOT_  _290_ (
    .A(fetch_rdata_i[30]),
    .B(_002_),
    .Y(_071_)
  );
  \$_NAND_  _291_ (
    .A(fetch_rdata_i[8]),
    .B(_001_),
    .Y(_072_)
  );
  \$_NAND_  _292_ (
    .A(fetch_rdata_i[12]),
    .B(_215_),
    .Y(_073_)
  );
  \$_NAND_  _293_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  \$_OR_  _294_ (
    .A(_071_),
    .B(_074_),
    .Y(_075_)
  );
  \$_NAND_  _295_ (
    .A(fetch_pc_i[10]),
    .B(_075_),
    .Y(_076_)
  );
  \$_OR_  _296_ (
    .A(fetch_pc_i[10]),
    .B(_075_),
    .Y(_077_)
  );
  \$_ANDNOT_  _297_ (
    .A(fetch_rdata_i[29]),
    .B(_002_),
    .Y(_078_)
  );
  \$_NAND_  _298_ (
    .A(fetch_rdata_i[10]),
    .B(_001_),
    .Y(_079_)
  );
  \$_NAND_  _299_ (
    .A(_073_),
    .B(_079_),
    .Y(_080_)
  );
  \$_OR_  _300_ (
    .A(_078_),
    .B(_080_),
    .Y(_081_)
  );
  \$_NAND_  _301_ (
    .A(fetch_pc_i[9]),
    .B(_081_),
    .Y(_082_)
  );
  \$_XOR_  _302_ (
    .A(fetch_pc_i[9]),
    .B(_081_),
    .Y(_083_)
  );
  \$_ANDNOT_  _303_ (
    .A(fetch_rdata_i[28]),
    .B(_002_),
    .Y(_084_)
  );
  \$_NAND_  _304_ (
    .A(fetch_rdata_i[9]),
    .B(_001_),
    .Y(_085_)
  );
  \$_NAND_  _305_ (
    .A(_073_),
    .B(_085_),
    .Y(_086_)
  );
  \$_OR_  _306_ (
    .A(_084_),
    .B(_086_),
    .Y(_087_)
  );
  \$_NAND_  _307_ (
    .A(fetch_pc_i[8]),
    .B(_087_),
    .Y(_088_)
  );
  \$_OR_  _308_ (
    .A(fetch_pc_i[8]),
    .B(_087_),
    .Y(_089_)
  );
  \$_MUX_  _309_ (
    .A(fetch_rdata_i[27]),
    .B(fetch_rdata_i[6]),
    .S(_002_),
    .Y(_090_)
  );
  \$_NAND_  _310_ (
    .A(fetch_pc_i[7]),
    .B(_090_),
    .Y(_091_)
  );
  \$_XOR_  _311_ (
    .A(fetch_pc_i[7]),
    .B(_090_),
    .Y(_092_)
  );
  \$_ANDNOT_  _312_ (
    .A(fetch_rdata_i[26]),
    .B(_002_),
    .Y(_093_)
  );
  \$_NAND_  _313_ (
    .A(fetch_rdata_i[7]),
    .B(_001_),
    .Y(_094_)
  );
  \$_NAND_  _314_ (
    .A(fetch_rdata_i[5]),
    .B(_215_),
    .Y(_095_)
  );
  \$_NAND_  _315_ (
    .A(_094_),
    .B(_095_),
    .Y(_096_)
  );
  \$_OR_  _316_ (
    .A(_093_),
    .B(_096_),
    .Y(_097_)
  );
  \$_NAND_  _317_ (
    .A(fetch_pc_i[6]),
    .B(_097_),
    .Y(_098_)
  );
  \$_OR_  _318_ (
    .A(fetch_pc_i[6]),
    .B(_097_),
    .Y(_099_)
  );
  \$_MUX_  _319_ (
    .A(fetch_rdata_i[25]),
    .B(fetch_rdata_i[2]),
    .S(_002_),
    .Y(_100_)
  );
  \$_NAND_  _320_ (
    .A(fetch_pc_i[5]),
    .B(_100_),
    .Y(_101_)
  );
  \$_XOR_  _321_ (
    .A(fetch_pc_i[5]),
    .B(_100_),
    .Y(_102_)
  );
  \$_MUX_  _322_ (
    .A(fetch_rdata_i[11]),
    .B(fetch_rdata_i[24]),
    .S(_029_),
    .Y(_103_)
  );
  \$_NAND_  _323_ (
    .A(fetch_pc_i[4]),
    .B(_103_),
    .Y(_104_)
  );
  \$_OR_  _324_ (
    .A(fetch_pc_i[4]),
    .B(_103_),
    .Y(_105_)
  );
  \$_NAND_  _325_ (
    .A(fetch_rdata_i[10]),
    .B(_031_),
    .Y(_106_)
  );
  \$_NAND_  _326_ (
    .A(fetch_rdata_i[5]),
    .B(_001_),
    .Y(_107_)
  );
  \$_NAND_  _327_ (
    .A(fetch_rdata_i[23]),
    .B(_029_),
    .Y(_108_)
  );
  \$_AND_  _328_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  \$_NAND_  _329_ (
    .A(_106_),
    .B(_109_),
    .Y(_110_)
  );
  \$_NAND_  _330_ (
    .A(fetch_pc_i[3]),
    .B(_110_),
    .Y(_111_)
  );
  \$_NAND_  _331_ (
    .A(fetch_rdata_i[9]),
    .B(_032_),
    .Y(_112_)
  );
  \$_NAND_  _332_ (
    .A(fetch_rdata_i[4]),
    .B(_002_),
    .Y(_113_)
  );
  \$_NAND_  _333_ (
    .A(fetch_rdata_i[22]),
    .B(_029_),
    .Y(_114_)
  );
  \$_AND_  _334_ (
    .A(_113_),
    .B(_114_),
    .Y(_115_)
  );
  \$_NAND_  _335_ (
    .A(_112_),
    .B(_115_),
    .Y(_116_)
  );
  \$_NAND_  _336_ (
    .A(fetch_pc_i[2]),
    .B(_116_),
    .Y(_117_)
  );
  \$_NAND_  _337_ (
    .A(fetch_rdata_i[8]),
    .B(_032_),
    .Y(_118_)
  );
  \$_NAND_  _338_ (
    .A(fetch_rdata_i[3]),
    .B(_002_),
    .Y(_119_)
  );
  \$_NAND_  _339_ (
    .A(fetch_rdata_i[21]),
    .B(_029_),
    .Y(_120_)
  );
  \$_AND_  _340_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  \$_NAND_  _341_ (
    .A(_118_),
    .B(_121_),
    .Y(_122_)
  );
  \$_AND_  _342_ (
    .A(fetch_pc_i[1]),
    .B(_122_),
    .Y(_123_)
  );
  \$_XOR_  _343_ (
    .A(fetch_pc_i[2]),
    .B(_116_),
    .Y(_124_)
  );
  \$_NAND_  _344_ (
    .A(_123_),
    .B(_124_),
    .Y(_125_)
  );
  \$_NAND_  _345_ (
    .A(_117_),
    .B(_125_),
    .Y(_126_)
  );
  \$_XOR_  _346_ (
    .A(fetch_pc_i[3]),
    .B(_110_),
    .Y(_127_)
  );
  \$_NAND_  _347_ (
    .A(_126_),
    .B(_127_),
    .Y(_128_)
  );
  \$_NAND_  _348_ (
    .A(_111_),
    .B(_128_),
    .Y(_129_)
  );
  \$_NAND_  _349_ (
    .A(_105_),
    .B(_129_),
    .Y(_130_)
  );
  \$_NAND_  _350_ (
    .A(_104_),
    .B(_130_),
    .Y(_131_)
  );
  \$_NAND_  _351_ (
    .A(_102_),
    .B(_131_),
    .Y(_132_)
  );
  \$_NAND_  _352_ (
    .A(_101_),
    .B(_132_),
    .Y(_133_)
  );
  \$_NAND_  _353_ (
    .A(_099_),
    .B(_133_),
    .Y(_134_)
  );
  \$_NAND_  _354_ (
    .A(_098_),
    .B(_134_),
    .Y(_135_)
  );
  \$_NAND_  _355_ (
    .A(_092_),
    .B(_135_),
    .Y(_136_)
  );
  \$_NAND_  _356_ (
    .A(_091_),
    .B(_136_),
    .Y(_137_)
  );
  \$_NAND_  _357_ (
    .A(_089_),
    .B(_137_),
    .Y(_138_)
  );
  \$_NAND_  _358_ (
    .A(_088_),
    .B(_138_),
    .Y(_139_)
  );
  \$_NAND_  _359_ (
    .A(_083_),
    .B(_139_),
    .Y(_140_)
  );
  \$_NAND_  _360_ (
    .A(_082_),
    .B(_140_),
    .Y(_141_)
  );
  \$_NAND_  _361_ (
    .A(_077_),
    .B(_141_),
    .Y(_142_)
  );
  \$_NAND_  _362_ (
    .A(_076_),
    .B(_142_),
    .Y(_143_)
  );
  \$_NAND_  _363_ (
    .A(_070_),
    .B(_143_),
    .Y(_144_)
  );
  \$_AND_  _364_ (
    .A(_069_),
    .B(_144_),
    .Y(_145_)
  );
  \$_NAND_  _365_ (
    .A(_064_),
    .B(_145_),
    .Y(_146_)
  );
  \$_AND_  _366_ (
    .A(_063_),
    .B(_146_),
    .Y(_147_)
  );
  \$_NAND_  _367_ (
    .A(_061_),
    .B(_147_),
    .Y(_148_)
  );
  \$_AND_  _368_ (
    .A(_060_),
    .B(_148_),
    .Y(_149_)
  );
  \$_NAND_  _369_ (
    .A(_057_),
    .B(_149_),
    .Y(_150_)
  );
  \$_AND_  _370_ (
    .A(_056_),
    .B(_150_),
    .Y(_151_)
  );
  \$_NAND_  _371_ (
    .A(_053_),
    .B(_151_),
    .Y(_152_)
  );
  \$_NAND_  _372_ (
    .A(_052_),
    .B(_152_),
    .Y(_153_)
  );
  \$_NAND_  _373_ (
    .A(_049_),
    .B(_153_),
    .Y(_154_)
  );
  \$_NAND_  _374_ (
    .A(_048_),
    .B(_154_),
    .Y(_155_)
  );
  \$_NAND_  _375_ (
    .A(_045_),
    .B(_155_),
    .Y(_156_)
  );
  \$_NAND_  _376_ (
    .A(_044_),
    .B(_156_),
    .Y(_157_)
  );
  \$_NAND_  _377_ (
    .A(_041_),
    .B(_157_),
    .Y(_158_)
  );
  \$_NAND_  _378_ (
    .A(_040_),
    .B(_158_),
    .Y(_159_)
  );
  \$_NAND_  _379_ (
    .A(_037_),
    .B(_159_),
    .Y(_160_)
  );
  \$_NAND_  _380_ (
    .A(_036_),
    .B(_160_),
    .Y(_161_)
  );
  \$_NAND_  _381_ (
    .A(_023_),
    .B(_161_),
    .Y(_162_)
  );
  \$_NAND_  _382_ (
    .A(_022_),
    .B(_162_),
    .Y(_163_)
  );
  \$_AND_  _383_ (
    .A(_021_),
    .B(_163_),
    .Y(_164_)
  );
  \$_NAND_  _384_ (
    .A(_019_),
    .B(_164_),
    .Y(_165_)
  );
  \$_OR_  _385_ (
    .A(_017_),
    .B(_165_),
    .Y(_166_)
  );
  \$_AND_  _386_ (
    .A(_018_),
    .B(_020_),
    .Y(_167_)
  );
  \$_OR_  _387_ (
    .A(_017_),
    .B(_167_),
    .Y(_168_)
  );
  \$_AND_  _388_ (
    .A(_013_),
    .B(_015_),
    .Y(_169_)
  );
  \$_AND_  _389_ (
    .A(_168_),
    .B(_169_),
    .Y(_170_)
  );
  \$_NAND_  _390_ (
    .A(_166_),
    .B(_170_),
    .Y(_171_)
  );
  \$_NAND_  _391_ (
    .A(fetch_pc_i[25]),
    .B(_004_),
    .Y(_172_)
  );
  \$_XOR_  _392_ (
    .A(fetch_pc_i[25]),
    .B(_004_),
    .Y(_173_)
  );
  \$_AND_  _393_ (
    .A(_171_),
    .B(_173_),
    .Y(_174_)
  );
  \$_NAND_  _394_ (
    .A(fetch_pc_i[26]),
    .B(_004_),
    .Y(_175_)
  );
  \$_XOR_  _395_ (
    .A(fetch_pc_i[26]),
    .B(_004_),
    .Y(_176_)
  );
  \$_NAND_  _396_ (
    .A(_174_),
    .B(_176_),
    .Y(_177_)
  );
  \$_OR_  _397_ (
    .A(_012_),
    .B(_177_),
    .Y(_178_)
  );
  \$_AND_  _398_ (
    .A(_172_),
    .B(_175_),
    .Y(_179_)
  );
  \$_OR_  _399_ (
    .A(_012_),
    .B(_179_),
    .Y(_180_)
  );
  \$_AND_  _400_ (
    .A(_008_),
    .B(_010_),
    .Y(_181_)
  );
  \$_AND_  _401_ (
    .A(_180_),
    .B(_181_),
    .Y(_182_)
  );
  \$_NAND_  _402_ (
    .A(_178_),
    .B(_182_),
    .Y(_183_)
  );
  \$_XOR_  _403_ (
    .A(fetch_pc_i[29]),
    .B(_004_),
    .Y(_184_)
  );
  \$_NAND_  _404_ (
    .A(_183_),
    .B(_184_),
    .Y(_185_)
  );
  \$_NAND_  _405_ (
    .A(_007_),
    .B(_185_),
    .Y(_186_)
  );
  \$_NAND_  _406_ (
    .A(_006_),
    .B(_186_),
    .Y(_187_)
  );
  \$_NAND_  _407_ (
    .A(_005_),
    .B(_187_),
    .Y(_188_)
  );
  \$_XNOR_  _408_ (
    .A(fetch_pc_i[31]),
    .B(_004_),
    .Y(_189_)
  );
  \$_XNOR_  _409_ (
    .A(_188_),
    .B(_189_),
    .Y(predict_branch_pc_o[31])
  );
  \$_AND_  _410_ (
    .A(_005_),
    .B(_006_),
    .Y(_190_)
  );
  \$_XOR_  _411_ (
    .A(_186_),
    .B(_190_),
    .Y(predict_branch_pc_o[30])
  );
  \$_XOR_  _412_ (
    .A(_183_),
    .B(_184_),
    .Y(predict_branch_pc_o[29])
  );
  \$_NAND_  _413_ (
    .A(_177_),
    .B(_179_),
    .Y(_191_)
  );
  \$_NAND_  _414_ (
    .A(_011_),
    .B(_191_),
    .Y(_192_)
  );
  \$_AND_  _415_ (
    .A(_010_),
    .B(_192_),
    .Y(_193_)
  );
  \$_XNOR_  _416_ (
    .A(_009_),
    .B(_193_),
    .Y(predict_branch_pc_o[28])
  );
  \$_XOR_  _417_ (
    .A(_011_),
    .B(_191_),
    .Y(predict_branch_pc_o[27])
  );
  \$_ANDNOT_  _418_ (
    .A(_172_),
    .B(_174_),
    .Y(_194_)
  );
  \$_XNOR_  _419_ (
    .A(_176_),
    .B(_194_),
    .Y(predict_branch_pc_o[26])
  );
  \$_XOR_  _420_ (
    .A(_171_),
    .B(_173_),
    .Y(predict_branch_pc_o[25])
  );
  \$_NAND_  _421_ (
    .A(_165_),
    .B(_167_),
    .Y(_195_)
  );
  \$_NAND_  _422_ (
    .A(_016_),
    .B(_195_),
    .Y(_196_)
  );
  \$_AND_  _423_ (
    .A(_015_),
    .B(_196_),
    .Y(_197_)
  );
  \$_XNOR_  _424_ (
    .A(_014_),
    .B(_197_),
    .Y(predict_branch_pc_o[24])
  );
  \$_XOR_  _425_ (
    .A(_016_),
    .B(_195_),
    .Y(predict_branch_pc_o[23])
  );
  \$_ANDNOT_  _426_ (
    .A(_020_),
    .B(_164_),
    .Y(_198_)
  );
  \$_XNOR_  _427_ (
    .A(_019_),
    .B(_198_),
    .Y(predict_branch_pc_o[22])
  );
  \$_XOR_  _428_ (
    .A(_021_),
    .B(_163_),
    .Y(predict_branch_pc_o[21])
  );
  \$_AND_  _429_ (
    .A(_022_),
    .B(_023_),
    .Y(_199_)
  );
  \$_XOR_  _430_ (
    .A(_161_),
    .B(_199_),
    .Y(predict_branch_pc_o[20])
  );
  \$_XOR_  _431_ (
    .A(_037_),
    .B(_159_),
    .Y(predict_branch_pc_o[19])
  );
  \$_XOR_  _432_ (
    .A(_041_),
    .B(_157_),
    .Y(predict_branch_pc_o[18])
  );
  \$_XOR_  _433_ (
    .A(_045_),
    .B(_155_),
    .Y(predict_branch_pc_o[17])
  );
  \$_NAND_  _434_ (
    .A(_048_),
    .B(_049_),
    .Y(_200_)
  );
  \$_XNOR_  _435_ (
    .A(_153_),
    .B(_200_),
    .Y(predict_branch_pc_o[16])
  );
  \$_XOR_  _436_ (
    .A(_053_),
    .B(_151_),
    .Y(predict_branch_pc_o[15])
  );
  \$_AND_  _437_ (
    .A(_056_),
    .B(_057_),
    .Y(_201_)
  );
  \$_XNOR_  _438_ (
    .A(_149_),
    .B(_201_),
    .Y(predict_branch_pc_o[14])
  );
  \$_XOR_  _439_ (
    .A(_061_),
    .B(_147_),
    .Y(predict_branch_pc_o[13])
  );
  \$_AND_  _440_ (
    .A(_063_),
    .B(_064_),
    .Y(_202_)
  );
  \$_XNOR_  _441_ (
    .A(_145_),
    .B(_202_),
    .Y(predict_branch_pc_o[12])
  );
  \$_XOR_  _442_ (
    .A(_070_),
    .B(_143_),
    .Y(predict_branch_pc_o[11])
  );
  \$_NAND_  _443_ (
    .A(_076_),
    .B(_077_),
    .Y(_203_)
  );
  \$_XNOR_  _444_ (
    .A(_141_),
    .B(_203_),
    .Y(predict_branch_pc_o[10])
  );
  \$_XOR_  _445_ (
    .A(_083_),
    .B(_139_),
    .Y(predict_branch_pc_o[9])
  );
  \$_NAND_  _446_ (
    .A(_088_),
    .B(_089_),
    .Y(_204_)
  );
  \$_XNOR_  _447_ (
    .A(_137_),
    .B(_204_),
    .Y(predict_branch_pc_o[8])
  );
  \$_XOR_  _448_ (
    .A(_092_),
    .B(_135_),
    .Y(predict_branch_pc_o[7])
  );
  \$_NAND_  _449_ (
    .A(_098_),
    .B(_099_),
    .Y(_205_)
  );
  \$_XNOR_  _450_ (
    .A(_133_),
    .B(_205_),
    .Y(predict_branch_pc_o[6])
  );
  \$_XOR_  _451_ (
    .A(_102_),
    .B(_131_),
    .Y(predict_branch_pc_o[5])
  );
  \$_AND_  _452_ (
    .A(_104_),
    .B(_105_),
    .Y(_206_)
  );
  \$_XOR_  _453_ (
    .A(_129_),
    .B(_206_),
    .Y(predict_branch_pc_o[4])
  );
  \$_XOR_  _454_ (
    .A(_126_),
    .B(_127_),
    .Y(predict_branch_pc_o[3])
  );
  \$_XOR_  _455_ (
    .A(_123_),
    .B(_124_),
    .Y(predict_branch_pc_o[2])
  );
  \$_XOR_  _456_ (
    .A(fetch_pc_i[1]),
    .B(_122_),
    .Y(predict_branch_pc_o[1])
  );
  \$_AND_  _457_ (
    .A(_031_),
    .B(_073_),
    .Y(_207_)
  );
  \$_ANDNOT_  _458_ (
    .A(fetch_rdata_i[31]),
    .B(fetch_rdata_i[2]),
    .Y(_208_)
  );
  \$_ANDNOT_  _459_ (
    .A(_208_),
    .B(fetch_rdata_i[3]),
    .Y(_209_)
  );
  \$_AND_  _460_ (
    .A(_026_),
    .B(_209_),
    .Y(_210_)
  );
  \$_NAND_  _461_ (
    .A(_025_),
    .B(_210_),
    .Y(_211_)
  );
  \$_NAND_  _462_ (
    .A(_207_),
    .B(_211_),
    .Y(_212_)
  );
  \$_AND_  _463_ (
    .A(fetch_valid_i),
    .B(_212_),
    .Y(predict_branch_taken_o)
  );
  assign instr = fetch_rdata_i;
  assign { branch_imm[31:21], branch_imm[0] } = { branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], branch_imm[20], 1'h0 };
  assign imm_cb_type = { fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[6:5], fetch_rdata_i[2], fetch_rdata_i[11:10], fetch_rdata_i[4:3], 1'h0 };
  assign imm_cj_type = { fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[12], fetch_rdata_i[8], fetch_rdata_i[10:9], fetch_rdata_i[6], fetch_rdata_i[7], fetch_rdata_i[2], fetch_rdata_i[11], fetch_rdata_i[5:3], 1'h0 };
  assign imm_b_type = { fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[7], fetch_rdata_i[30:25], fetch_rdata_i[11:8], 1'h0 };
  assign imm_j_type = { fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[31], fetch_rdata_i[19:12], fetch_rdata_i[20], fetch_rdata_i[30:21], 1'h0 };
  assign predict_branch_pc_o[0] = fetch_pc_i[0];
endmodule
