/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* top =  1  *)
(* src = "dut.sv:1.1-20.10" *)
module test(offset_i, data_o, data_ref_o);
  (* src = "dut.sv:6.20-6.28" *)
  input [2:0] offset_i;
  wire [2:0] offset_i;
  (* src = "dut.sv:7.20-7.26" *)
  output [15:0] data_o;
  wire [15:0] data_o;
  (* src = "dut.sv:8.20-8.30" *)
  output [15:0] data_ref_o;
  wire [15:0] data_ref_o;
  wire _00_;
  wire _01_;
  wire _02_;
  \$_NOT_  _03_ (
    .A(offset_i[2]),
    .Y(data_o[3])
  );
  \$_XNOR_  _04_ (
    .A(offset_i[1]),
    .B(offset_i[0]),
    .Y(_00_)
  );
  \$_OR_  _05_ (
    .A(offset_i[1]),
    .B(offset_i[0]),
    .Y(_01_)
  );
  \$_AND_  _06_ (
    .A(offset_i[2]),
    .B(_01_),
    .Y(data_o[8])
  );
  \$_AND_  _07_ (
    .A(_00_),
    .B(data_o[8]),
    .Y(data_o[10])
  );
  \$_NOR_  _08_ (
    .A(offset_i[1]),
    .B(offset_i[2]),
    .Y(data_o[1])
  );
  \$_ANDNOT_  _09_ (
    .A(data_o[1]),
    .B(offset_i[0]),
    .Y(data_o[0])
  );
  \$_XNOR_  _10_ (
    .A(data_o[3]),
    .B(_01_),
    .Y(data_o[4])
  );
  \$_XOR_  _11_ (
    .A(offset_i[1]),
    .B(offset_i[2]),
    .Y(data_o[5])
  );
  \$_AND_  _12_ (
    .A(offset_i[1]),
    .B(offset_i[2]),
    .Y(data_o[9])
  );
  \$_ANDNOT_  _13_ (
    .A(data_o[3]),
    .B(_00_),
    .Y(_02_)
  );
  \$_MUX_  _14_ (
    .A(offset_i[2]),
    .B(data_o[4]),
    .S(_00_),
    .Y(data_o[6])
  );
  \$_OR_  _15_ (
    .A(data_o[0]),
    .B(_02_),
    .Y(data_o[2])
  );
  assign data_ref_o = { 5'h00, data_o[10:8], offset_i[2], data_o[6:0] };
  assign { data_o[15:11], data_o[7] } = { 5'h00, offset_i[2] };
endmodule
