/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:7.1-19.10" *)
(* top =  1  *)
module dut(a0);
  (* src = "dut.sv:7.12-7.14" *)
  input a0;
  wire a0;
  (* src = "dut.sv:12.14-12.15" *)
  wire [3:0] \c[0] ;
  (* src = "dut.sv:12.14-12.15" *)
  wire [3:0] \c[1] ;
  (* src = "dut.sv:12.14-12.15" *)
  wire [3:0] \c[2] ;
  (* src = "dut.sv:12.14-12.15" *)
  wire [3:0] \c[3] ;
  assign \c[3]  = 4'h1;
  assign \c[2]  = 4'h1;
  assign \c[1]  = 4'h1;
  assign \c[0]  = 4'h1;
endmodule
