/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* dynports =  1  *)
(* src = "dut.sv:11.1-19.10" *)
(* top =  1  *)
module top(o);
  (* src = "dut.sv:11.23-11.24" *)
  output signed [31:0] o;
  wire signed [31:0] o;
  (* src = "dut.sv:13.17-13.29" *)
  (* wiretype = "\\my_pkg::hw_key_req_t" *)
  wire [511:0] keymgr_key_i;
  assign keymgr_key_i = 512'hffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff;
  assign o = 32'd4294967295;
endmodule
