/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* dynports =  1  *)
(* src = "dut.sv:59.4-63.6" *)
(* hdlname = "almost_top" *)
module \$paramod\almost_top\TargetCfg=s32'00000000000000000000000000000010 (o);
  (* src = "dut.sv:44.30-44.31" *)
  output signed [31:0] o;
  wire signed [31:0] o;
  \$paramod\prim_pad_attr\PadType=s32'00000000000000000000000000000010  u_prim_pad_attr (
    .o(o)
  );
endmodule

(* dynports =  1  *)
(* src = "dut.sv:27.4-31.6" *)
(* hdlname = "prim_generic_pad_attr" *)
module \$paramod\prim_generic_pad_attr\PadTypeInGeneric=s32'00000000000000000000000000000010 (o);
  (* src = "dut.sv:19.41-19.42" *)
  output signed [31:0] o;
  wire signed [31:0] o;
  assign o = 32'd2;
endmodule

(* dynports =  1  *)
(* src = "dut.sv:48.4-52.6" *)
(* hdlname = "prim_pad_attr" *)
module \$paramod\prim_pad_attr\PadType=s32'00000000000000000000000000000010 (o);
  (* src = "dut.sv:34.33-34.34" *)
  output signed [31:0] o;
  wire signed [31:0] o;
  \$paramod\prim_submodule\PadType=s32'00000000000000000000000000000010  u_submodule (
    .o(o)
  );
endmodule

(* dynports =  1  *)
(* src = "dut.sv:37.4-41.6" *)
(* hdlname = "prim_submodule" *)
module \$paramod\prim_submodule\PadType=s32'00000000000000000000000000000010 (o);
  (* src = "dut.sv:24.34-24.35" *)
  output signed [31:0] o;
  wire signed [31:0] o;
  \$paramod\prim_generic_pad_attr\PadTypeInGeneric=s32'00000000000000000000000000000010  u_impl_generic (
    .o(o)
  );
endmodule

(* dynports =  1  *)
(* src = "dut.sv:55.1-64.10" *)
(* top =  1  *)
module top(o);
  (* src = "dut.sv:55.23-55.24" *)
  output signed [31:0] o;
  wire signed [31:0] o;
  \$paramod\almost_top\TargetCfg=s32'00000000000000000000000000000010  u_top (
    .o(o)
  );
endmodule
