/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* top =  1  *)
(* src = "dut.sv:1.1-8.10" *)
module gen_test6(o);
  (* src = "dut.sv:1.31-1.32" *)
  output [3:0] o;
  wire [3:0] o;
  assign o = 4'h0;
endmodule
