/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* dynports =  1  *)
(* src = "dut.sv:4.1-72.10" *)
module asym_ram_sdp_read_wider(clkA, clkB, enaA, weA, enaB, addrA, addrB, diA, doB);
  (* src = "dut.sv:4.62-4.67" *)
  input [9:0] addrA;
  wire [9:0] addrA;
  (* src = "dut.sv:4.69-4.74" *)
  input [7:0] addrB;
  wire [7:0] addrB;
  (* src = "dut.sv:4.33-4.37" *)
  input clkA;
  wire clkA;
  (* src = "dut.sv:4.39-4.43" *)
  input clkB;
  wire clkB;
  (* src = "dut.sv:4.76-4.79" *)
  input [3:0] diA;
  wire [3:0] diA;
  (* src = "dut.sv:4.81-4.84" *)
  output [15:0] doB;
  wire [15:0] doB;
  (* src = "dut.sv:4.45-4.49" *)
  input enaA;
  wire enaA;
  (* src = "dut.sv:4.56-4.60" *)
  input enaB;
  wire enaB;
  (* \reg  = 32'd1 *)
  (* src = "dut.sv:50.19-50.24" *)
  wire [15:0] readB;
  (* src = "dut.sv:4.51-4.54" *)
  input weA;
  wire weA;
  assign doB = 16'hxxxx;
  assign readB = 16'hxxxx;
endmodule
