/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* keep =  1  *)
(* dynports =  1  *)
(* src = "dut.sv:209.1-439.10" *)
(* top =  1  *)
module dut(clk);
  (* src = "dut.sv:209.18-209.21" *)
  input clk;
  wire clk;
  wire _000_;
  wire _001_;
  (* src = "dut.sv:348.14-348.94" *)
  wire _002_;
  (* src = "dut.sv:368.14-368.81" *)
  wire _003_;
  (* src = "dut.sv:395.14-395.49" *)
  wire _004_;
  (* src = "dut.sv:402.14-402.41" *)
  wire _005_;
  (* src = "dut.sv:418.17-418.60" *)
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:421.5-430.8|dut.sv:332.3-436.10|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:591.28-591.35" *)
  (* unused_bits = "18 19 20 21 22 23 24 25 26" *)
  wire [35:0] _097_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:421.5-430.8|dut.sv:332.3-436.10|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:581.22-581.23" *)
  (* unused_bits = "0 2" *)
  wire [3:0] _098_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:421.5-430.8|dut.sv:332.3-436.10|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [0:0] _099_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:421.5-430.8|dut.sv:332.3-436.10|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:591.28-591.35" *)
  (* unused_bits = "3 4 5 6 7 8" *)
  wire [17:0] _100_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:421.5-430.8|dut.sv:332.3-436.10|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:581.22-581.23" *)
  (* unused_bits = "0 2" *)
  wire [5:0] _101_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:421.5-430.8|dut.sv:332.3-436.10|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [0:0] _102_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:421.5-430.8|dut.sv:332.3-436.10|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:591.28-591.35" *)
  wire [8:0] _103_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:421.5-430.8|dut.sv:332.3-436.10|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:579.28-579.29" *)
  (* unused_bits = "0" *)
  wire [99:0] _104_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:421.5-430.8|dut.sv:332.3-436.10|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:591.28-591.35" *)
  (* unused_bits = "0 6 7 8 9" *)
  wire [99:0] _105_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:421.5-430.8|dut.sv:332.3-436.10|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [9:0] _106_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:429.24-429.39|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:135.22-135.23" *)
  (* unused_bits = "5 6" *)
  wire [10:0] _107_;
  (* enum_type = "$enum0" *)
  (* enum_value_001100000000 = "\\CSR_MSTATUS" *)
  (* enum_value_001100000001 = "\\CSR_MISA" *)
  (* enum_value_001100000100 = "\\CSR_MIE" *)
  (* enum_value_001100000101 = "\\CSR_MTVEC" *)
  (* enum_value_001100100000 = "\\CSR_MCOUNTINHIBIT" *)
  (* enum_value_001100100011 = "\\CSR_MHPMEVENT3" *)
  (* enum_value_001100100100 = "\\CSR_MHPMEVENT4" *)
  (* enum_value_001100100101 = "\\CSR_MHPMEVENT5" *)
  (* enum_value_001100100110 = "\\CSR_MHPMEVENT6" *)
  (* enum_value_001100100111 = "\\CSR_MHPMEVENT7" *)
  (* enum_value_001100101000 = "\\CSR_MHPMEVENT8" *)
  (* enum_value_001100101001 = "\\CSR_MHPMEVENT9" *)
  (* enum_value_001100101010 = "\\CSR_MHPMEVENT10" *)
  (* enum_value_001100101011 = "\\CSR_MHPMEVENT11" *)
  (* enum_value_001100101100 = "\\CSR_MHPMEVENT12" *)
  (* enum_value_001100101101 = "\\CSR_MHPMEVENT13" *)
  (* enum_value_001100101110 = "\\CSR_MHPMEVENT14" *)
  (* enum_value_001100101111 = "\\CSR_MHPMEVENT15" *)
  (* enum_value_001100110000 = "\\CSR_MHPMEVENT16" *)
  (* enum_value_001100110001 = "\\CSR_MHPMEVENT17" *)
  (* enum_value_001100110010 = "\\CSR_MHPMEVENT18" *)
  (* enum_value_001100110011 = "\\CSR_MHPMEVENT19" *)
  (* enum_value_001100110100 = "\\CSR_MHPMEVENT20" *)
  (* enum_value_001100110101 = "\\CSR_MHPMEVENT21" *)
  (* enum_value_001100110110 = "\\CSR_MHPMEVENT22" *)
  (* enum_value_001100110111 = "\\CSR_MHPMEVENT23" *)
  (* enum_value_001100111000 = "\\CSR_MHPMEVENT24" *)
  (* enum_value_001100111001 = "\\CSR_MHPMEVENT25" *)
  (* enum_value_001100111010 = "\\CSR_MHPMEVENT26" *)
  (* enum_value_001100111011 = "\\CSR_MHPMEVENT27" *)
  (* enum_value_001100111100 = "\\CSR_MHPMEVENT28" *)
  (* enum_value_001100111101 = "\\CSR_MHPMEVENT29" *)
  (* enum_value_001100111110 = "\\CSR_MHPMEVENT30" *)
  (* enum_value_001100111111 = "\\CSR_MHPMEVENT31" *)
  (* enum_value_001101000000 = "\\CSR_MSCRATCH" *)
  (* enum_value_001101000001 = "\\CSR_MEPC" *)
  (* enum_value_001101000010 = "\\CSR_MCAUSE" *)
  (* enum_value_001101000011 = "\\CSR_MTVAL" *)
  (* enum_value_001101000100 = "\\CSR_MIP" *)
  (* enum_value_001110100000 = "\\CSR_PMPCFG0" *)
  (* enum_value_001110100001 = "\\CSR_PMPCFG1" *)
  (* enum_value_001110100010 = "\\CSR_PMPCFG2" *)
  (* enum_value_001110100011 = "\\CSR_PMPCFG3" *)
  (* enum_value_001110110000 = "\\CSR_PMPADDR0" *)
  (* enum_value_001110110001 = "\\CSR_PMPADDR1" *)
  (* enum_value_001110110010 = "\\CSR_PMPADDR2" *)
  (* enum_value_001110110011 = "\\CSR_PMPADDR3" *)
  (* enum_value_001110110100 = "\\CSR_PMPADDR4" *)
  (* enum_value_001110110101 = "\\CSR_PMPADDR5" *)
  (* enum_value_001110110110 = "\\CSR_PMPADDR6" *)
  (* enum_value_001110110111 = "\\CSR_PMPADDR7" *)
  (* enum_value_001110111000 = "\\CSR_PMPADDR8" *)
  (* enum_value_001110111001 = "\\CSR_PMPADDR9" *)
  (* enum_value_001110111010 = "\\CSR_PMPADDR10" *)
  (* enum_value_001110111011 = "\\CSR_PMPADDR11" *)
  (* enum_value_001110111100 = "\\CSR_PMPADDR12" *)
  (* enum_value_001110111101 = "\\CSR_PMPADDR13" *)
  (* enum_value_001110111110 = "\\CSR_PMPADDR14" *)
  (* enum_value_001110111111 = "\\CSR_PMPADDR15" *)
  (* enum_value_011110100000 = "\\CSR_TSELECT" *)
  (* enum_value_011110100001 = "\\CSR_TDATA1" *)
  (* enum_value_011110100010 = "\\CSR_TDATA2" *)
  (* enum_value_011110100011 = "\\CSR_TDATA3" *)
  (* enum_value_011110101000 = "\\CSR_MCONTEXT" *)
  (* enum_value_011110101010 = "\\CSR_SCONTEXT" *)
  (* enum_value_011110110000 = "\\CSR_DCSR" *)
  (* enum_value_011110110001 = "\\CSR_DPC" *)
  (* enum_value_011110110010 = "\\CSR_DSCRATCH0" *)
  (* enum_value_011110110011 = "\\CSR_DSCRATCH1" *)
  (* enum_value_011111000000 = "\\CSR_CPUCTRL" *)
  (* enum_value_011111000001 = "\\CSR_SECURESEED" *)
  (* enum_value_101100000000 = "\\CSR_MCYCLE" *)
  (* enum_value_101100000010 = "\\CSR_MINSTRET" *)
  (* enum_value_101100000011 = "\\CSR_MHPMCOUNTER3" *)
  (* enum_value_101100000100 = "\\CSR_MHPMCOUNTER4" *)
  (* enum_value_101100000101 = "\\CSR_MHPMCOUNTER5" *)
  (* enum_value_101100000110 = "\\CSR_MHPMCOUNTER6" *)
  (* enum_value_101100000111 = "\\CSR_MHPMCOUNTER7" *)
  (* enum_value_101100001000 = "\\CSR_MHPMCOUNTER8" *)
  (* enum_value_101100001001 = "\\CSR_MHPMCOUNTER9" *)
  (* enum_value_101100001010 = "\\CSR_MHPMCOUNTER10" *)
  (* enum_value_101100001011 = "\\CSR_MHPMCOUNTER11" *)
  (* enum_value_101100001100 = "\\CSR_MHPMCOUNTER12" *)
  (* enum_value_101100001101 = "\\CSR_MHPMCOUNTER13" *)
  (* enum_value_101100001110 = "\\CSR_MHPMCOUNTER14" *)
  (* enum_value_101100001111 = "\\CSR_MHPMCOUNTER15" *)
  (* enum_value_101100010000 = "\\CSR_MHPMCOUNTER16" *)
  (* enum_value_101100010001 = "\\CSR_MHPMCOUNTER17" *)
  (* enum_value_101100010010 = "\\CSR_MHPMCOUNTER18" *)
  (* enum_value_101100010011 = "\\CSR_MHPMCOUNTER19" *)
  (* enum_value_101100010100 = "\\CSR_MHPMCOUNTER20" *)
  (* enum_value_101100010101 = "\\CSR_MHPMCOUNTER21" *)
  (* enum_value_101100010110 = "\\CSR_MHPMCOUNTER22" *)
  (* enum_value_101100010111 = "\\CSR_MHPMCOUNTER23" *)
  (* enum_value_101100011000 = "\\CSR_MHPMCOUNTER24" *)
  (* enum_value_101100011001 = "\\CSR_MHPMCOUNTER25" *)
  (* enum_value_101100011010 = "\\CSR_MHPMCOUNTER26" *)
  (* enum_value_101100011011 = "\\CSR_MHPMCOUNTER27" *)
  (* enum_value_101100011100 = "\\CSR_MHPMCOUNTER28" *)
  (* enum_value_101100011101 = "\\CSR_MHPMCOUNTER29" *)
  (* enum_value_101100011110 = "\\CSR_MHPMCOUNTER30" *)
  (* enum_value_101100011111 = "\\CSR_MHPMCOUNTER31" *)
  (* enum_value_101110000000 = "\\CSR_MCYCLEH" *)
  (* enum_value_101110000010 = "\\CSR_MINSTRETH" *)
  (* enum_value_101110000011 = "\\CSR_MHPMCOUNTER3H" *)
  (* enum_value_101110000100 = "\\CSR_MHPMCOUNTER4H" *)
  (* enum_value_101110000101 = "\\CSR_MHPMCOUNTER5H" *)
  (* enum_value_101110000110 = "\\CSR_MHPMCOUNTER6H" *)
  (* enum_value_101110000111 = "\\CSR_MHPMCOUNTER7H" *)
  (* enum_value_101110001000 = "\\CSR_MHPMCOUNTER8H" *)
  (* enum_value_101110001001 = "\\CSR_MHPMCOUNTER9H" *)
  (* enum_value_101110001010 = "\\CSR_MHPMCOUNTER10H" *)
  (* enum_value_101110001011 = "\\CSR_MHPMCOUNTER11H" *)
  (* enum_value_101110001100 = "\\CSR_MHPMCOUNTER12H" *)
  (* enum_value_101110001101 = "\\CSR_MHPMCOUNTER13H" *)
  (* enum_value_101110001110 = "\\CSR_MHPMCOUNTER14H" *)
  (* enum_value_101110001111 = "\\CSR_MHPMCOUNTER15H" *)
  (* enum_value_101110010000 = "\\CSR_MHPMCOUNTER16H" *)
  (* enum_value_101110010001 = "\\CSR_MHPMCOUNTER17H" *)
  (* enum_value_101110010010 = "\\CSR_MHPMCOUNTER18H" *)
  (* enum_value_101110010011 = "\\CSR_MHPMCOUNTER19H" *)
  (* enum_value_101110010100 = "\\CSR_MHPMCOUNTER20H" *)
  (* enum_value_101110010101 = "\\CSR_MHPMCOUNTER21H" *)
  (* enum_value_101110010110 = "\\CSR_MHPMCOUNTER22H" *)
  (* enum_value_101110010111 = "\\CSR_MHPMCOUNTER23H" *)
  (* enum_value_101110011000 = "\\CSR_MHPMCOUNTER24H" *)
  (* enum_value_101110011001 = "\\CSR_MHPMCOUNTER25H" *)
  (* enum_value_101110011010 = "\\CSR_MHPMCOUNTER26H" *)
  (* enum_value_101110011011 = "\\CSR_MHPMCOUNTER27H" *)
  (* enum_value_101110011100 = "\\CSR_MHPMCOUNTER28H" *)
  (* enum_value_101110011101 = "\\CSR_MHPMCOUNTER29H" *)
  (* enum_value_101110011110 = "\\CSR_MHPMCOUNTER30H" *)
  (* enum_value_101110011111 = "\\CSR_MHPMCOUNTER31H" *)
  (* enum_value_111100010100 = "\\CSR_MHARTID" *)
  (* enum_value_111111111110 = "\\CSR_END" *)
  (* enum_value_111111111111 = "\\DUMMY_CSR_SETMHPMEVENT31" *)
  (* src = "dut.sv:274.13-274.23" *)
  (* wiretype = "\\ibex_pkg::csr_num_e" *)
  wire [11:0] csr_addr_i;
  (* src = "dut.sv:238.14-238.20" *)
  wire [31:0] dcsr_q;
  (* src = "dut.sv:302.14-302.26" *)
  wire debug_mode_i;
  (* src = "dut.sv:297.14-297.23" *)
  wire [31:0] hart_id_i;
  (* src = "dut.sv:300.14-300.22" *)
  wire [5:0] mcause_q;
  (* onehot = 32'd1 *)
  wire [1:0] mhpmcounter_idx;
  (* src = "dut.sv:314.20-314.29" *)
  wire [1023:0] mhpmevent;
  (* src = "dut.sv:276.14-276.19" *)
  (* wiretype = "\\ibex_pkg::irqs_t" *)
  wire [17:0] mie_q;
  (* src = "dut.sv:277.14-277.17" *)
  (* wiretype = "\\ibex_pkg::irqs_t" *)
  wire [17:0] mip;
  (* src = "dut.sv:275.14-275.23" *)
  wire [5:0] mstatus_q;
  wire [15:0] pmp_addr_rdata;
  (* src = "dut.sv:306.51-306.64" *)
  wire [127:0] pmp_cfg_rdata;
  \$_AND_  _108_ (
    .A(csr_addr_i[1]),
    .B(csr_addr_i[0]),
    .Y(_054_)
  );
  \$_AND_  _109_ (
    .A(csr_addr_i[3]),
    .B(csr_addr_i[2]),
    .Y(_055_)
  );
  \$_AND_  _110_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  \$_NOR_  _111_ (
    .A(csr_addr_i[10]),
    .B(csr_addr_i[11]),
    .Y(_057_)
  );
  \$_AND_  _112_ (
    .A(csr_addr_i[5]),
    .B(csr_addr_i[4]),
    .Y(_058_)
  );
  \$_ANDNOT_  _113_ (
    .A(csr_addr_i[7]),
    .B(csr_addr_i[6]),
    .Y(_059_)
  );
  \$_AND_  _114_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  \$_AND_  _115_ (
    .A(_057_),
    .B(_060_),
    .Y(_061_)
  );
  \$_NAND_  _116_ (
    .A(_056_),
    .B(_061_),
    .Y(_062_)
  );
  \$_NOT_  _117_ (
    .A(_062_),
    .Y(_101_[3])
  );
  \$_AND_  _118_ (
    .A(csr_addr_i[10]),
    .B(csr_addr_i[11]),
    .Y(_063_)
  );
  \$_AND_  _119_ (
    .A(csr_addr_i[7]),
    .B(csr_addr_i[6]),
    .Y(_064_)
  );
  \$_AND_  _120_ (
    .A(_058_),
    .B(_064_),
    .Y(_065_)
  );
  \$_AND_  _121_ (
    .A(_063_),
    .B(_065_),
    .Y(_066_)
  );
  \$_NAND_  _122_ (
    .A(_056_),
    .B(_066_),
    .Y(_067_)
  );
  \$_NOT_  _123_ (
    .A(_067_),
    .Y(_105_[1])
  );
  \$_NOR_  _124_ (
    .A(csr_addr_i[3]),
    .B(csr_addr_i[2]),
    .Y(_068_)
  );
  \$_ORNOT_  _125_ (
    .A(csr_addr_i[4]),
    .B(_068_),
    .Y(_069_)
  );
  \$_OR_  _126_ (
    .A(_054_),
    .B(_069_),
    .Y(_070_)
  );
  \$_NOR_  _127_ (
    .A(csr_addr_i[7]),
    .B(csr_addr_i[6]),
    .Y(_071_)
  );
  \$_AND_  _128_ (
    .A(csr_addr_i[5]),
    .B(_057_),
    .Y(_072_)
  );
  \$_AND_  _129_ (
    .A(_071_),
    .B(_072_),
    .Y(_073_)
  );
  \$_NAND_  _130_ (
    .A(_070_),
    .B(_073_),
    .Y(_074_)
  );
  \$_NOT_  _131_ (
    .A(_074_),
    .Y(_098_[1])
  );
  \$_AND_  _132_ (
    .A(_067_),
    .B(_074_),
    .Y(_075_)
  );
  \$_AND_  _133_ (
    .A(_062_),
    .B(_075_),
    .Y(_076_)
  );
  \$_NOR_  _134_ (
    .A(csr_addr_i[5]),
    .B(csr_addr_i[4]),
    .Y(_077_)
  );
  \$_AND_  _135_ (
    .A(_071_),
    .B(_077_),
    .Y(_078_)
  );
  \$_AND_  _136_ (
    .A(_057_),
    .B(_078_),
    .Y(_079_)
  );
  \$_ANDNOT_  _137_ (
    .A(_079_),
    .B(csr_addr_i[1]),
    .Y(_080_)
  );
  \$_AND_  _138_ (
    .A(_068_),
    .B(_080_),
    .Y(_081_)
  );
  \$_NAND_  _139_ (
    .A(_068_),
    .B(_080_),
    .Y(_082_)
  );
  \$_NAND_  _140_ (
    .A(csr_addr_i[0]),
    .B(_081_),
    .Y(_083_)
  );
  \$_NOT_  _141_ (
    .A(_083_),
    .Y(_097_[35])
  );
  \$_NOR_  _142_ (
    .A(csr_addr_i[1]),
    .B(csr_addr_i[0]),
    .Y(_084_)
  );
  \$_ANDNOT_  _143_ (
    .A(csr_addr_i[2]),
    .B(csr_addr_i[3]),
    .Y(_085_)
  );
  \$_AND_  _144_ (
    .A(_084_),
    .B(_085_),
    .Y(_086_)
  );
  \$_ANDNOT_  _145_ (
    .A(csr_addr_i[4]),
    .B(csr_addr_i[5]),
    .Y(_087_)
  );
  \$_AND_  _146_ (
    .A(_071_),
    .B(_087_),
    .Y(_088_)
  );
  \$_AND_  _147_ (
    .A(_063_),
    .B(_088_),
    .Y(_089_)
  );
  \$_NAND_  _148_ (
    .A(_086_),
    .B(_089_),
    .Y(_090_)
  );
  \$_NOT_  _149_ (
    .A(_090_),
    .Y(_001_)
  );
  \$_AND_  _150_ (
    .A(_083_),
    .B(_090_),
    .Y(_091_)
  );
  \$_NAND_  _151_ (
    .A(_076_),
    .B(_091_),
    .Y(_092_)
  );
  \$_OR_  _152_ (
    .A(mhpmcounter_idx[0]),
    .B(mhpmcounter_idx[1]),
    .Y(_093_)
  );
  \$_OR_  _153_ (
    .A(_074_),
    .B(_093_),
    .Y(_094_)
  );
  \$_NAND_  _154_ (
    .A(_092_),
    .B(_094_),
    .Y(_102_)
  );
  \$_ORNOT_  _155_ (
    .A(_067_),
    .B(_093_),
    .Y(_095_)
  );
  \$_AND_  _156_ (
    .A(_074_),
    .B(_095_),
    .Y(_096_)
  );
  \$_NOT_  _157_ (
    .A(_096_),
    .Y(_106_[9])
  );
  \$_NAND_  _158_ (
    .A(_079_),
    .B(_086_),
    .Y(_007_)
  );
  \$_NOT_  _159_ (
    .A(_007_),
    .Y(_105_[71])
  );
  \$_ANDNOT_  _160_ (
    .A(csr_addr_i[6]),
    .B(csr_addr_i[7]),
    .Y(_008_)
  );
  \$_AND_  _161_ (
    .A(_077_),
    .B(_008_),
    .Y(_009_)
  );
  \$_AND_  _162_ (
    .A(_057_),
    .B(_009_),
    .Y(_010_)
  );
  \$_NAND_  _163_ (
    .A(_086_),
    .B(_010_),
    .Y(_011_)
  );
  \$_NOT_  _164_ (
    .A(_011_),
    .Y(_105_[55])
  );
  \$_NAND_  _165_ (
    .A(_007_),
    .B(_011_),
    .Y(_003_)
  );
  \$_ANDNOT_  _166_ (
    .A(_082_),
    .B(_003_),
    .Y(_012_)
  );
  \$_AND_  _167_ (
    .A(_090_),
    .B(_012_),
    .Y(_013_)
  );
  \$_ANDNOT_  _168_ (
    .A(_068_),
    .B(csr_addr_i[0]),
    .Y(_014_)
  );
  \$_AND_  _169_ (
    .A(_068_),
    .B(_084_),
    .Y(_015_)
  );
  \$_ANDNOT_  _170_ (
    .A(_059_),
    .B(csr_addr_i[4]),
    .Y(_016_)
  );
  \$_AND_  _171_ (
    .A(_072_),
    .B(_016_),
    .Y(_017_)
  );
  \$_NAND_  _172_ (
    .A(_015_),
    .B(_017_),
    .Y(_018_)
  );
  \$_NOT_  _173_ (
    .A(_018_),
    .Y(_100_[13])
  );
  \$_AND_  _174_ (
    .A(_062_),
    .B(_018_),
    .Y(_019_)
  );
  \$_AND_  _175_ (
    .A(csr_addr_i[1]),
    .B(_014_),
    .Y(_020_)
  );
  \$_NAND_  _176_ (
    .A(_010_),
    .B(_020_),
    .Y(_021_)
  );
  \$_NOT_  _177_ (
    .A(_021_),
    .Y(_105_[62])
  );
  \$_AND_  _178_ (
    .A(_074_),
    .B(_021_),
    .Y(_022_)
  );
  \$_AND_  _179_ (
    .A(_019_),
    .B(_022_),
    .Y(_023_)
  );
  \$_NAND_  _180_ (
    .A(_013_),
    .B(_023_),
    .Y(_024_)
  );
  \$_NAND_  _181_ (
    .A(mhpmcounter_idx[1]),
    .B(_024_),
    .Y(_025_)
  );
  \$_NAND_  _182_ (
    .A(_067_),
    .B(_025_),
    .Y(_107_[7])
  );
  \$_NAND_  _183_ (
    .A(_095_),
    .B(_025_),
    .Y(_104_[6])
  );
  \$_ANDNOT_  _184_ (
    .A(csr_addr_i[10]),
    .B(csr_addr_i[11]),
    .Y(_026_)
  );
  \$_AND_  _185_ (
    .A(_060_),
    .B(_026_),
    .Y(_027_)
  );
  \$_NAND_  _186_ (
    .A(_015_),
    .B(_027_),
    .Y(_028_)
  );
  \$_NOT_  _187_ (
    .A(_028_),
    .Y(_103_[6])
  );
  \$_AND_  _188_ (
    .A(_079_),
    .B(_015_),
    .Y(_105_[90])
  );
  \$_AND_  _189_ (
    .A(_075_),
    .B(_019_),
    .Y(_029_)
  );
  \$_NOT_  _190_ (
    .A(_029_),
    .Y(_106_[4])
  );
  \$_AND_  _191_ (
    .A(_021_),
    .B(_028_),
    .Y(_030_)
  );
  \$_AND_  _192_ (
    .A(_091_),
    .B(_030_),
    .Y(_031_)
  );
  \$_AND_  _193_ (
    .A(_029_),
    .B(_031_),
    .Y(_099_)
  );
  \$_OR_  _194_ (
    .A(_067_),
    .B(_093_),
    .Y(_032_)
  );
  \$_ANDNOT_  _195_ (
    .A(_074_),
    .B(_105_[90]),
    .Y(_033_)
  );
  \$_AND_  _196_ (
    .A(_018_),
    .B(_028_),
    .Y(_034_)
  );
  \$_AND_  _197_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  \$_NAND_  _198_ (
    .A(_032_),
    .B(_035_),
    .Y(_106_[0])
  );
  \$_AND_  _199_ (
    .A(_007_),
    .B(_021_),
    .Y(_036_)
  );
  \$_NAND_  _200_ (
    .A(_096_),
    .B(_036_),
    .Y(_106_[6])
  );
  \$_AND_  _201_ (
    .A(_075_),
    .B(_007_),
    .Y(_037_)
  );
  \$_NAND_  _202_ (
    .A(_034_),
    .B(_037_),
    .Y(_106_[1])
  );
  \$_NAND_  _203_ (
    .A(_075_),
    .B(_018_),
    .Y(_106_[3])
  );
  \$_AND_  _204_ (
    .A(_076_),
    .B(_034_),
    .Y(_038_)
  );
  \$_NAND_  _205_ (
    .A(_011_),
    .B(_038_),
    .Y(_106_[5])
  );
  \$_NAND_  _206_ (
    .A(_062_),
    .B(_096_),
    .Y(_106_[8])
  );
  \$_AND_  _207_ (
    .A(_011_),
    .B(_019_),
    .Y(_039_)
  );
  \$_NAND_  _208_ (
    .A(_096_),
    .B(_039_),
    .Y(_106_[7])
  );
  \$_NAND_  _209_ (
    .A(_083_),
    .B(_021_),
    .Y(_040_)
  );
  \$_OR_  _210_ (
    .A(_106_[3]),
    .B(_040_),
    .Y(_106_[2])
  );
  \$_NAND_  _211_ (
    .A(mhpmcounter_idx[0]),
    .B(_024_),
    .Y(_041_)
  );
  \$_NAND_  _212_ (
    .A(_028_),
    .B(_041_),
    .Y(_000_)
  );
  \$_NAND_  _213_ (
    .A(_013_),
    .B(_038_),
    .Y(_042_)
  );
  \$_AND_  _214_ (
    .A(_094_),
    .B(_030_),
    .Y(_043_)
  );
  \$_OR_  _215_ (
    .A(_093_),
    .B(_043_),
    .Y(_044_)
  );
  \$_ANDNOT_  _216_ (
    .A(_036_),
    .B(_106_[5]),
    .Y(_045_)
  );
  \$_NAND_  _217_ (
    .A(_082_),
    .B(_045_),
    .Y(_046_)
  );
  \$_AND_  _218_ (
    .A(_083_),
    .B(_043_),
    .Y(_047_)
  );
  \$_AND_  _219_ (
    .A(_092_),
    .B(_047_),
    .Y(_048_)
  );
  \$_AND_  _220_ (
    .A(_093_),
    .B(_030_),
    .Y(_049_)
  );
  \$_AND_  _221_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  \$_NAND_  _222_ (
    .A(_046_),
    .B(_050_),
    .Y(_051_)
  );
  \$_NAND_  _223_ (
    .A(_044_),
    .B(_051_),
    .Y(_052_)
  );
  \$_AND_  _224_ (
    .A(_042_),
    .B(_052_),
    .Y(_006_)
  );
  \$_ANDNOT_  _225_ (
    .A(_093_),
    .B(_107_[7]),
    .Y(_005_)
  );
  \$_NAND_  _226_ (
    .A(_012_),
    .B(_029_),
    .Y(_053_)
  );
  \$_AND_  _227_ (
    .A(_048_),
    .B(_053_),
    .Y(_004_)
  );
  \$_AND_  _228_ (
    .A(_099_),
    .B(_045_),
    .Y(_002_)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:323.1-437.4" *)
  \$_DFF_P_  \csr_addr_i_reg[0]  /* _229_ */ (
    .C(clk),
    .D(_106_[0]),
    .Q(csr_addr_i[0])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:323.1-437.4" *)
  \$_DFF_P_  \csr_addr_i_reg[1]  /* _230_ */ (
    .C(clk),
    .D(_106_[1]),
    .Q(csr_addr_i[1])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:323.1-437.4" *)
  \$_DFF_P_  \csr_addr_i_reg[2]  /* _231_ */ (
    .C(clk),
    .D(_106_[2]),
    .Q(csr_addr_i[2])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:323.1-437.4" *)
  \$_DFF_P_  \csr_addr_i_reg[3]  /* _232_ */ (
    .C(clk),
    .D(_106_[3]),
    .Q(csr_addr_i[3])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:323.1-437.4" *)
  \$_DFF_P_  \csr_addr_i_reg[4]  /* _233_ */ (
    .C(clk),
    .D(_106_[4]),
    .Q(csr_addr_i[4])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:323.1-437.4" *)
  \$_DFF_P_  \csr_addr_i_reg[5]  /* _234_ */ (
    .C(clk),
    .D(_106_[5]),
    .Q(csr_addr_i[5])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:323.1-437.4" *)
  \$_DFF_P_  \csr_addr_i_reg[6]  /* _235_ */ (
    .C(clk),
    .D(_106_[6]),
    .Q(csr_addr_i[6])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:323.1-437.4" *)
  \$_DFF_P_  \csr_addr_i_reg[7]  /* _236_ */ (
    .C(clk),
    .D(_106_[7]),
    .Q(csr_addr_i[7])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:323.1-437.4" *)
  \$_DFF_P_  \csr_addr_i_reg[10]  /* _237_ */ (
    .C(clk),
    .D(_106_[8]),
    .Q(csr_addr_i[10])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:323.1-437.4" *)
  \$_DFF_P_  \csr_addr_i_reg[11]  /* _238_ */ (
    .C(clk),
    .D(_106_[9]),
    .Q(csr_addr_i[11])
  );
  \$_DFF_P_  \mhpmcounter_idx_reg[0]  /* _239_ */ (
    .C(clk),
    .D(_000_),
    .Q(mhpmcounter_idx[0])
  );
  \$_DFF_P_  \mhpmcounter_idx_reg[1]  /* _240_ */ (
    .C(clk),
    .D(_107_[7]),
    .Q(mhpmcounter_idx[1])
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:403.7-403.58" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967271),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _241_ (
    .A(1'h0),
    .ARGS(),
    .EN(_103_[6]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:404.7-404.39" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967270),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _242_ (
    .A(_103_[6]),
    .ARGS(),
    .EN(_103_[6]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:405.7-405.62" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967269),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _243_ (
    .A(1'h1),
    .ARGS(),
    .EN(_103_[6]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:406.7-406.69" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967268),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _244_ (
    .A(_103_[6]),
    .ARGS(),
    .EN(_103_[6]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:407.7-407.35" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967267),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _245_ (
    .A(1'h1),
    .ARGS(),
    .EN(_103_[6]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:326.1-326.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967293),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _246_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:418.10-418.62" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967266),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _247_ (
    .A(_006_),
    .ARGS(),
    .EN(_098_[1]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:428.7-428.43" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967265),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _248_ (
    .A(_104_[6]),
    .ARGS(),
    .EN(_105_[1]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:429.7-429.58" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967264),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _249_ (
    .A(1'h0),
    .ARGS(),
    .EN(_105_[1]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:327.1-327.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967292),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _250_ (
    .A(1'h0),
    .ARGS(),
    .EN(1'h1),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:336.7-336.42" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967291),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _251_ (
    .A(_001_),
    .ARGS(),
    .EN(_001_),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:346.7-346.67" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967290),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _252_ (
    .A(_102_),
    .ARGS(),
    .EN(_105_[90]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:347.7-347.69" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967289),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _253_ (
    .A(_099_),
    .ARGS(),
    .EN(_105_[90]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:348.7-348.96" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967288),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _254_ (
    .A(_002_),
    .ARGS(),
    .EN(_105_[90]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:349.7-349.69" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967287),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _255_ (
    .A(_099_),
    .ARGS(),
    .EN(_105_[90]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:350.7-350.65" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967286),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _256_ (
    .A(_099_),
    .ARGS(),
    .EN(_105_[90]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:355.7-355.43" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967285),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _257_ (
    .A(_097_[35]),
    .ARGS(),
    .EN(_097_[35]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:356.7-356.47" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967284),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _258_ (
    .A(1'h1),
    .ARGS(),
    .EN(_097_[35]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:324.1-324.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967295),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _259_ (
    .A(1'h1),
    .ARGS(),
    .EN(1'h1),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:365.7-365.65" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967283),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _260_ (
    .A(_102_),
    .ARGS(),
    .EN(_105_[71]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:366.7-366.62" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967282),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _261_ (
    .A(_099_),
    .ARGS(),
    .EN(_105_[71]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:367.7-367.65" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967281),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _262_ (
    .A(_099_),
    .ARGS(),
    .EN(_105_[71]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:368.7-368.83" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967280),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _263_ (
    .A(_003_),
    .ARGS(),
    .EN(_105_[71]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:373.7-373.69" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967279),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _264_ (
    .A(_105_[62]),
    .ARGS(),
    .EN(_105_[62]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:382.7-382.63" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967278),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _265_ (
    .A(_102_),
    .ARGS(),
    .EN(_105_[55]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:383.7-383.60" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967277),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _266_ (
    .A(_099_),
    .ARGS(),
    .EN(_105_[55]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:384.7-384.63" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967276),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _267_ (
    .A(_099_),
    .ARGS(),
    .EN(_105_[55]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:385.7-385.81" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967275),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _268_ (
    .A(_003_),
    .ARGS(),
    .EN(_105_[55]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:390.7-390.69" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967274),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _269_ (
    .A(1'h0),
    .ARGS(),
    .EN(_100_[13]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:325.1-325.41" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967294),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _270_ (
    .A(1'h0),
    .ARGS(),
    .EN(1'h1),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:395.7-395.51" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967273),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _271_ (
    .A(_004_),
    .ARGS(),
    .EN(_101_[3]),
    .TRG(clk)
  );
  (* keep = 32'd1 *)
  (* src = "dut.sv:402.7-402.43" *)
  \$check  #(
    .ARGS_WIDTH(32'd0),
    .FLAVOR("assert"),
    .FORMAT(),
    .PRIORITY(32'd4294967272),
    .TRG_ENABLE(32'd1),
    .TRG_POLARITY(1'h1),
    .TRG_WIDTH(32'd1)
  ) _272_ (
    .A(_005_),
    .ARGS(),
    .EN(_103_[6]),
    .TRG(clk)
  );
  assign { _105_[99:91], _105_[89:72], _105_[70:63], _105_[61:56], _105_[54:7], _105_[5:2] } = { 16'h0000, _097_[35], 5'h00, _105_[71], 8'h00, _105_[62], 7'h00, _105_[55], 8'h00, _100_[13], 1'h0, _100_[13], _100_[13], _100_[13], _100_[13], _100_[13], _100_[13], 1'h0, _101_[3], _101_[3], 1'h0, _101_[3], _101_[3], 8'h00, _103_[6], 3'h0, _103_[6], _103_[6], _098_[1], _098_[1], _098_[1], _098_[1], _098_[1], _098_[1], _098_[1], _098_[1], _098_[1], _098_[1], _105_[6], _105_[6], _105_[6], _105_[1], _105_[1], _105_[1], _105_[1] };
  assign { _100_[17:14], _100_[12:7], _100_[2:0] } = { _097_[35], 7'h00, _100_[6], _100_[6], 3'h0 };
  assign { _097_[34:19], _097_[17:0] } = { 8'h00, _097_[18], _097_[18], _097_[18], _097_[18], _097_[18], _097_[18], _097_[18], _097_[18], 18'h00000 };
  assign { _104_[99:7], _104_[5:1] } = { 90'h00101042110a02fdb008fff, _104_[6], _104_[6], _104_[6], 5'h1f };
  assign { _107_[10:8], _107_[6], _107_[4:0] } = { 1'h0, _107_[7], _107_[7], _107_[5], 5'h00 };
  assign { _101_[5:4], _101_[2:1] } = { _097_[35], _100_[13], _100_[6], _098_[1] };
  assign { _103_[8:7], _103_[5:0] } = { _103_[6], _103_[6], 6'h00 };
  assign _098_[3:2] = { _097_[35], _097_[18] };
  assign mip = 18'h3ffff;
  assign mie_q = 18'h3ffff;
  assign mhpmevent = 1024'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0xxxxxxxxxxxxxxxxxxxxxxxxxxx1111;
  assign pmp_cfg_rdata = 128'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0xxxxxxxxxxx1010;
  assign debug_mode_i = 1'h1;
  assign mcause_q = 6'h3f;
  assign hart_id_i = 32'd286331153;
  assign pmp_addr_rdata = 16'hxxxx;
  assign mstatus_q = 6'h3f;
  assign csr_addr_i[9:8] = 2'h3;
  assign dcsr_q = 32'd42783;
endmodule
