/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) */

(* top =  1  *)
(* src = "dut.sv:7.1-53.10" *)
module code_hdl_models_parallel_crc(clk, reset, enable, init, data_in, crc_out);
  (* src = "dut.sv:16.7-16.10" *)
  input clk;
  wire clk;
  (* src = "dut.sv:17.7-17.12" *)
  input reset;
  wire reset;
  (* src = "dut.sv:18.7-18.13" *)
  input enable;
  wire enable;
  (* src = "dut.sv:19.7-19.11" *)
  input init;
  wire init;
  (* src = "dut.sv:20.13-20.20" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "dut.sv:22.15-22.22" *)
  output [15:0] crc_out;
  wire [15:0] crc_out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  (* src = "dut.sv:24.14-24.21" *)
  wire [15:0] crc_reg;
  (* src = "dut.sv:25.14-25.22" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11" *)
  wire [15:0] next_crc;
  \$_XNOR_  _38_ (
    .A(crc_reg[7]),
    .B(data_in[3]),
    .Y(_00_)
  );
  \$_XNOR_  _39_ (
    .A(crc_reg[0]),
    .B(_00_),
    .Y(_01_)
  );
  \$_ORNOT_  _40_ (
    .A(init),
    .B(_00_),
    .Y(_31_)
  );
  \$_OR_  _41_ (
    .A(init),
    .B(_01_),
    .Y(_36_)
  );
  \$_XNOR_  _42_ (
    .A(crc_reg[6]),
    .B(data_in[2]),
    .Y(_02_)
  );
  \$_XOR_  _43_ (
    .A(crc_reg[11]),
    .B(data_in[7]),
    .Y(_03_)
  );
  \$_XNOR_  _44_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  \$_OR_  _45_ (
    .A(init),
    .B(_04_),
    .Y(_35_)
  );
  \$_XOR_  _46_ (
    .A(crc_reg[5]),
    .B(data_in[1]),
    .Y(_05_)
  );
  \$_XNOR_  _47_ (
    .A(crc_reg[10]),
    .B(data_in[6]),
    .Y(_06_)
  );
  \$_XNOR_  _48_ (
    .A(_05_),
    .B(_06_),
    .Y(_07_)
  );
  \$_OR_  _49_ (
    .A(init),
    .B(_07_),
    .Y(_34_)
  );
  \$_XOR_  _50_ (
    .A(data_in[7]),
    .B(data_in[0]),
    .Y(_08_)
  );
  \$_XOR_  _51_ (
    .A(data_in[5]),
    .B(crc_reg[4]),
    .Y(_09_)
  );
  \$_XNOR_  _52_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  \$_XOR_  _53_ (
    .A(crc_reg[9]),
    .B(crc_reg[11]),
    .Y(_11_)
  );
  \$_NAND_  _54_ (
    .A(_10_),
    .B(_11_),
    .Y(_12_)
  );
  \$_NOR_  _55_ (
    .A(_10_),
    .B(_11_),
    .Y(_13_)
  );
  \$_NOR_  _56_ (
    .A(init),
    .B(_13_),
    .Y(_14_)
  );
  \$_NAND_  _57_ (
    .A(_12_),
    .B(_14_),
    .Y(_33_)
  );
  \$_XOR_  _58_ (
    .A(crc_reg[8]),
    .B(data_in[4]),
    .Y(_15_)
  );
  \$_OR_  _59_ (
    .A(init),
    .B(_15_),
    .Y(_32_)
  );
  \$_ORNOT_  _60_ (
    .A(init),
    .B(_02_),
    .Y(_30_)
  );
  \$_OR_  _61_ (
    .A(init),
    .B(_05_),
    .Y(_29_)
  );
  \$_XOR_  _62_ (
    .A(crc_reg[11]),
    .B(crc_reg[4]),
    .Y(_16_)
  );
  \$_ORNOT_  _63_ (
    .A(_08_),
    .B(_16_),
    .Y(_17_)
  );
  \$_ANDNOT_  _64_ (
    .A(_08_),
    .B(_16_),
    .Y(_18_)
  );
  \$_NOR_  _65_ (
    .A(init),
    .B(_18_),
    .Y(_19_)
  );
  \$_NAND_  _66_ (
    .A(_17_),
    .B(_19_),
    .Y(_26_)
  );
  \$_XNOR_  _67_ (
    .A(crc_reg[3]),
    .B(_06_),
    .Y(_20_)
  );
  \$_OR_  _68_ (
    .A(init),
    .B(_20_),
    .Y(_28_)
  );
  \$_XNOR_  _69_ (
    .A(data_in[5]),
    .B(crc_reg[2]),
    .Y(_21_)
  );
  \$_NAND_  _70_ (
    .A(crc_reg[9]),
    .B(_21_),
    .Y(_22_)
  );
  \$_NOR_  _71_ (
    .A(crc_reg[9]),
    .B(_21_),
    .Y(_23_)
  );
  \$_NOR_  _72_ (
    .A(init),
    .B(_23_),
    .Y(_24_)
  );
  \$_NAND_  _73_ (
    .A(_22_),
    .B(_24_),
    .Y(_27_)
  );
  \$_XOR_  _74_ (
    .A(crc_reg[1]),
    .B(_15_),
    .Y(_25_)
  );
  \$_OR_  _75_ (
    .A(init),
    .B(_25_),
    .Y(_37_)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[0]  /* _76_ */ (
    .C(clk),
    .D(_26_),
    .E(enable),
    .Q(crc_reg[0]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[1]  /* _77_ */ (
    .C(clk),
    .D(_29_),
    .E(enable),
    .Q(crc_reg[1]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[2]  /* _78_ */ (
    .C(clk),
    .D(_30_),
    .E(enable),
    .Q(crc_reg[2]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[3]  /* _79_ */ (
    .C(clk),
    .D(_31_),
    .E(enable),
    .Q(crc_reg[3]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[4]  /* _80_ */ (
    .C(clk),
    .D(_32_),
    .E(enable),
    .Q(crc_reg[4]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[5]  /* _81_ */ (
    .C(clk),
    .D(_33_),
    .E(enable),
    .Q(crc_reg[5]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[6]  /* _82_ */ (
    .C(clk),
    .D(_34_),
    .E(enable),
    .Q(crc_reg[6]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[7]  /* _83_ */ (
    .C(clk),
    .D(_35_),
    .E(enable),
    .Q(crc_reg[7]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[8]  /* _84_ */ (
    .C(clk),
    .D(_36_),
    .E(enable),
    .Q(crc_reg[8]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[9]  /* _85_ */ (
    .C(clk),
    .D(_37_),
    .E(enable),
    .Q(crc_reg[9]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[10]  /* _86_ */ (
    .C(clk),
    .D(_27_),
    .E(enable),
    .Q(crc_reg[10]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[11]  /* _87_ */ (
    .C(clk),
    .D(_28_),
    .E(enable),
    .Q(crc_reg[11]),
    .R(reset)
  );
  (* src = "dut.sv:29.1-38.4" *)
  \$_SDFFE_PP1P_  \crc_reg_reg[14]  /* _88_ */ (
    .C(clk),
    .D(init),
    .E(enable),
    .Q(crc_reg[14]),
    .R(reset)
  );
  assign next_crc[15:12] = 4'hx;
  assign { crc_reg[15], crc_reg[13:12] } = { crc_reg[14], crc_reg[14], crc_reg[14] };
  assign crc_out = { crc_reg[14], crc_reg[14], crc_reg[14], crc_reg[14], crc_reg[11:0] };
endmodule
