#!/bin/bash

# Test script for UHDM workflow: Surelog -> UHDM -> Yosys
# This script demonstrates the complete flow from SystemVerilog to RTLIL via UHDM

set -e  # Exit on any error

echo "=== UHDM Workflow Test ==="
echo "Testing: SystemVerilog -> Surelog -> UHDM -> Yosys -> RTLIL"
echo

# Set up paths
SURELOG_BIN="../../build/third_party/Surelog/bin/surelog"
YOSYS_BIN="../../out/current/bin/yosys"
SV_FILE="dut.sv"
UHDM_FILE="slpp_all/surelog.uhdm"

# Check if binaries exist
if [ ! -f "$SURELOG_BIN" ]; then
    echo "ERROR: Surelog not found at $SURELOG_BIN"
    exit 1
fi

if [ ! -f "$YOSYS_BIN" ]; then
    echo "ERROR: Yosys not found at $YOSYS_BIN"
    exit 1
fi

if [ ! -f "$SV_FILE" ]; then
    echo "ERROR: SystemVerilog file $SV_FILE not found"
    exit 1
fi

# Clean up previous runs
echo "1. Cleaning up previous files..."
rm -f "$UHDM_FILE" *.log *.dot

# Step 1: Use Surelog to parse SystemVerilog and generate UHDM
echo "2. Running Surelog to generate UHDM..."
echo "   Command: $SURELOG_BIN -parse $SV_FILE"
$SURELOG_BIN -parse "$SV_FILE"

# Check if UHDM file was generated
if [ ! -f "$UHDM_FILE" ]; then
    echo "ERROR: UHDM file $UHDM_FILE was not generated by Surelog"
    exit 1
fi

echo "   ✓ UHDM file generated successfully: $UHDM_FILE"
echo "   File size: $(ls -lh $UHDM_FILE | awk '{print $5}')"
echo

# Step 2: Create Yosys script to read UHDM file
echo "3. Creating Yosys script to read UHDM..."
cat > test_uhdm_read.ys << 'EOF'
# Test script to read UHDM file in Yosys
# This tests our custom UHDM frontend

plugin -i uhdm2rtlil

# Read the UHDM file using our frontend
read_uhdm slpp_all/surelog.uhdm

# Display module information
hierarchy -check -top flipflop

# Show statistics
stat


# Perform basic optimizations
opt

# Show final statistics
stat

# Write RTLIL output for verification
write_rtlil flipflop_from_uhdm.il
EOF

echo "   ✓ Yosys script created: test_uhdm_read.ys"
echo

# Step 3: Run Yosys with UHDM input
echo "4. Running Yosys with UHDM input..."
echo "   Command: $YOSYS_BIN test_uhdm_read.ys"
if $YOSYS_BIN test_uhdm_read.ys; then
    echo "   ✓ Yosys successfully processed UHDM file"
else
    echo "   ✗ Yosys failed to process UHDM file"
    echo "   This is expected if the UHDM frontend is not yet implemented"
    echo "   The UHDM file was generated successfully by Surelog"
fi

echo
echo "=== Test Summary ==="
echo "✓ Surelog successfully parsed SystemVerilog and generated UHDM"
if [ -f "flipflop_from_uhdm.il" ]; then
    echo "✓ Yosys successfully read UHDM and generated RTLIL"
    echo "  Output file: flipflop_from_uhdm.il"
else
    echo "ℹ UHDM frontend not yet implemented in this build"
    echo "  Generated UHDM file: $UHDM_FILE (ready for frontend implementation)"
fi

echo
echo "Generated files:"
ls -la *.uhdm *.il *.ys 2>/dev/null || echo "  Only UHDM file generated"
