/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* top =  1  *)
(* src = "dut.sv:1.1-15.10" *)
module top(o);
  (* src = "dut.sv:1.23-1.24" *)
  output signed [31:0] o;
  wire signed [31:0] o;
  (* src = "dut.sv:5.21-5.22" *)
  wire [0:0] \gen_blk[0].z ;
  assign \gen_blk[0].z  = 1'h1;
  assign o = 32'd1;
endmodule
