/* Generated by Yosys 0.62+39 (git sha1 131911291-dirty, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* src = "dut.sv:23.1-59.10" *)
(* top =  1  *)
module nested_struct(in_data, out_data, clk, rst);
  (* src = "dut.sv:24.38-24.45" *)
  input [61:0] in_data;
  wire [61:0] in_data;
  (* src = "dut.sv:25.38-25.46" *)
  output [61:0] out_data;
  wire [61:0] out_data;
  (* src = "dut.sv:26.18-26.21" *)
  input clk;
  wire clk;
  (* src = "dut.sv:27.18-27.21" *)
  input rst;
  wire rst;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* src = "dut.sv:33.21-33.35" *)
  (* wiretype = "\\main_pkg::nested_struct_t" *)
  wire [61:0] processed_data;
  \$_NOT_  _25_ (
    .A(in_data[7]),
    .Y(processed_data[7])
  );
  \$_AND_  _26_ (
    .A(in_data[18]),
    .B(in_data[17]),
    .Y(_00_)
  );
  \$_NAND_  _27_ (
    .A(in_data[15]),
    .B(in_data[16]),
    .Y(_01_)
  );
  \$_ANDNOT_  _28_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  \$_AND_  _29_ (
    .A(in_data[14]),
    .B(in_data[13]),
    .Y(_03_)
  );
  \$_NAND_  _30_ (
    .A(in_data[11]),
    .B(in_data[12]),
    .Y(_04_)
  );
  \$_ORNOT_  _31_ (
    .A(_04_),
    .B(_03_),
    .Y(_05_)
  );
  \$_ANDNOT_  _32_ (
    .A(in_data[12]),
    .B(in_data[11]),
    .Y(_06_)
  );
  \$_AND_  _33_ (
    .A(_06_),
    .B(_03_),
    .Y(_07_)
  );
  \$_NOT_  _34_ (
    .A(in_data[10]),
    .Y(_08_)
  );
  \$_ANDNOT_  _35_ (
    .A(in_data[9]),
    .B(in_data[10]),
    .Y(_09_)
  );
  \$_NAND_  _36_ (
    .A(in_data[8]),
    .B(in_data[7]),
    .Y(_10_)
  );
  \$_ANDNOT_  _37_ (
    .A(_09_),
    .B(_10_),
    .Y(_11_)
  );
  \$_ANDNOT_  _38_ (
    .A(_08_),
    .B(_11_),
    .Y(_12_)
  );
  \$_ANDNOT_  _39_ (
    .A(_07_),
    .B(_12_),
    .Y(_13_)
  );
  \$_ANDNOT_  _40_ (
    .A(_05_),
    .B(_13_),
    .Y(_14_)
  );
  \$_ANDNOT_  _41_ (
    .A(_02_),
    .B(_14_),
    .Y(_15_)
  );
  \$_AND_  _42_ (
    .A(_15_),
    .B(in_data[19]),
    .Y(_16_)
  );
  \$_XOR_  _43_ (
    .A(_16_),
    .B(in_data[20]),
    .Y(processed_data[20])
  );
  \$_XOR_  _44_ (
    .A(_15_),
    .B(in_data[19]),
    .Y(processed_data[19])
  );
  \$_NOR_  _45_ (
    .A(_14_),
    .B(_01_),
    .Y(_17_)
  );
  \$_AND_  _46_ (
    .A(_17_),
    .B(in_data[17]),
    .Y(_18_)
  );
  \$_XOR_  _47_ (
    .A(_18_),
    .B(in_data[18]),
    .Y(processed_data[18])
  );
  \$_XOR_  _48_ (
    .A(_17_),
    .B(in_data[17]),
    .Y(processed_data[17])
  );
  \$_ANDNOT_  _49_ (
    .A(in_data[15]),
    .B(_14_),
    .Y(_19_)
  );
  \$_XOR_  _50_ (
    .A(_19_),
    .B(in_data[16]),
    .Y(processed_data[16])
  );
  \$_XNOR_  _51_ (
    .A(_14_),
    .B(in_data[15]),
    .Y(processed_data[15])
  );
  \$_ANDNOT_  _52_ (
    .A(_06_),
    .B(_12_),
    .Y(_20_)
  );
  \$_ANDNOT_  _53_ (
    .A(_04_),
    .B(_20_),
    .Y(_21_)
  );
  \$_ANDNOT_  _54_ (
    .A(in_data[13]),
    .B(_21_),
    .Y(_22_)
  );
  \$_XOR_  _55_ (
    .A(_22_),
    .B(in_data[14]),
    .Y(processed_data[14])
  );
  \$_XNOR_  _56_ (
    .A(_21_),
    .B(in_data[13]),
    .Y(processed_data[13])
  );
  \$_ORNOT_  _57_ (
    .A(in_data[11]),
    .B(_12_),
    .Y(_23_)
  );
  \$_XOR_  _58_ (
    .A(_23_),
    .B(in_data[12]),
    .Y(processed_data[12])
  );
  \$_XOR_  _59_ (
    .A(_12_),
    .B(in_data[11]),
    .Y(processed_data[11])
  );
  \$_ANDNOT_  _60_ (
    .A(in_data[9]),
    .B(_10_),
    .Y(_24_)
  );
  \$_XOR_  _61_ (
    .A(_24_),
    .B(_08_),
    .Y(processed_data[10])
  );
  \$_XNOR_  _62_ (
    .A(_10_),
    .B(in_data[9]),
    .Y(processed_data[9])
  );
  \$_XOR_  _63_ (
    .A(in_data[8]),
    .B(in_data[7]),
    .Y(processed_data[8])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[1]  /* _64_ */ (
    .C(clk),
    .D(in_data[1]),
    .Q(out_data[1]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[3]  /* _65_ */ (
    .C(clk),
    .D(in_data[3]),
    .Q(out_data[3]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[4]  /* _66_ */ (
    .C(clk),
    .D(1'h1),
    .Q(out_data[4]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[5]  /* _67_ */ (
    .C(clk),
    .D(in_data[5]),
    .Q(out_data[5]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[6]  /* _68_ */ (
    .C(clk),
    .D(in_data[6]),
    .Q(out_data[6]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[7]  /* _69_ */ (
    .C(clk),
    .D(processed_data[7]),
    .Q(out_data[7]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[8]  /* _70_ */ (
    .C(clk),
    .D(processed_data[8]),
    .Q(out_data[8]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[9]  /* _71_ */ (
    .C(clk),
    .D(processed_data[9]),
    .Q(out_data[9]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[10]  /* _72_ */ (
    .C(clk),
    .D(processed_data[10]),
    .Q(out_data[10]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[11]  /* _73_ */ (
    .C(clk),
    .D(processed_data[11]),
    .Q(out_data[11]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[12]  /* _74_ */ (
    .C(clk),
    .D(processed_data[12]),
    .Q(out_data[12]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[13]  /* _75_ */ (
    .C(clk),
    .D(processed_data[13]),
    .Q(out_data[13]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[14]  /* _76_ */ (
    .C(clk),
    .D(processed_data[14]),
    .Q(out_data[14]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[15]  /* _77_ */ (
    .C(clk),
    .D(processed_data[15]),
    .Q(out_data[15]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[16]  /* _78_ */ (
    .C(clk),
    .D(processed_data[16]),
    .Q(out_data[16]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[17]  /* _79_ */ (
    .C(clk),
    .D(processed_data[17]),
    .Q(out_data[17]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[18]  /* _80_ */ (
    .C(clk),
    .D(processed_data[18]),
    .Q(out_data[18]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[19]  /* _81_ */ (
    .C(clk),
    .D(processed_data[19]),
    .Q(out_data[19]),
    .R(rst)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:36.5-42.8" *)
  \$_SDFF_PP0_  \out_data_reg[20]  /* _82_ */ (
    .C(clk),
    .D(processed_data[20]),
    .Q(out_data[20]),
    .R(rst)
  );
  assign { processed_data[61:21], processed_data[6:0] } = { 41'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0, in_data[6:5], 1'h1, in_data[3], 1'h1, in_data[1], 1'hx };
  assign { out_data[61:21], out_data[2], out_data[0] } = { 41'h00000000000, out_data[4], 1'h0 };
endmodule
