/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* src = "dut.sv:11.1-19.10" *)
(* top =  1  *)
module gold(out);
  (* src = "dut.sv:11.13-11.16" *)
  output [1023:0] out;
  wire [1023:0] out;
  (* src = "dut.sv:12.13-12.19" *)
  wire signed [31:0] a;
  (* src = "dut.sv:13.9-13.15" *)
  wire signed [31:0] b;
  (* src = "dut.sv:14.14-14.20" *)
  wire signed [15:0] c;
  (* src = "dut.sv:15.13-15.19" *)
  wire signed [63:0] d;
  (* src = "dut.sv:16.10-16.16" *)
  wire signed [7:0] e;
  assign e = 8'hfb;
  assign d = 64'hfffffffffffffffc;
  assign c = 16'hfffd;
  assign b = 32'd4294967294;
  assign a = 32'd4294967295;
  assign out = 1024'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000fffffffffffffffefffdfffffffffffffffcfb;
endmodule
