/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:6.1-9.10" *)
(* top =  1  *)
module func_struct_repro(instr, opc, imm);
  (* src = "dut.sv:6.46-6.51" *)
  input [31:0] instr;
  wire [31:0] instr;
  (* src = "dut.sv:6.72-6.75" *)
  output [4:0] opc;
  wire [4:0] opc;
  (* src = "dut.sv:6.97-6.100" *)
  output [31:0] imm;
  wire [31:0] imm;
  (* src = "dut.sv:7.9-7.10" *)
  (* wiretype = "\\dec_t" *)
  wire [36:0] d;
  assign d = { instr[6:2], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31:20] };
  assign imm = { instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31:20] };
  assign opc = instr[6:2];
endmodule
