/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* src = "test_union.sv:19.1-40.22" *)
(* top =  1  *)
module test_union(ins, rd, rs1, rs2, imm);
  (* src = "test_union.sv:23.25-23.28" *)
  input [31:0] ins;
  wire [31:0] ins;
  (* src = "test_union.sv:25.25-25.27" *)
  output [4:0] rd;
  wire [4:0] rd;
  (* src = "test_union.sv:26.25-26.28" *)
  output [4:0] rs1;
  wire [4:0] rs1;
  (* src = "test_union.sv:27.25-27.28" *)
  output [4:0] rs2;
  wire [4:0] rs2;
  (* src = "test_union.sv:28.25-28.28" *)
  output [11:0] imm;
  wire [11:0] imm;
  (* src = "test_union.sv:31.8-31.11" *)
  (* unused_bits = "0 1 2 3 4 5 6 12 13 14" *)
  (* wiretype = "\\riscv_isa_pkg::op32_t" *)
  wire [31:0] dec;
  assign dec = ins;
  assign imm = ins[31:20];
  assign rs2 = ins[24:20];
  assign rs1 = ins[19:15];
  assign rd = ins[11:7];
endmodule
