/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* dynports =  1  *)
(* src = "dut.sv:7.1-19.16" *)
(* top =  1  *)
module top(o);
  (* src = "dut.sv:7.23-7.24" *)
  output signed [31:0] o;
  wire signed [31:0] o;
  \$paramod\otp_ctrl_ecc_reg\Depth=s32'00000000000000000000000000000000  u_otp_ctrl_ecc_reg (
    .a(o)
  );
endmodule
