/* Generated by Yosys 0.62+39 (git sha1 131911291-dirty, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* top =  1  *)
(* src = "dut.sv:1.1-9.10" *)
module dffsr(clk, d, clr, set, q);
  (* src = "dut.sv:1.21-1.24" *)
  input clk;
  wire clk;
  (* src = "dut.sv:1.26-1.27" *)
  input d;
  wire d;
  (* src = "dut.sv:1.29-1.32" *)
  input clr;
  wire clr;
  (* src = "dut.sv:1.34-1.37" *)
  input set;
  wire set;
  (* src = "dut.sv:1.50-1.51" *)
  output q;
  wire q;
  wire _0_;
  \$_ANDNOT_  _1_ (
    .A(set),
    .B(clr),
    .Y(_0_)
  );
  (* src = "dut.sv:2.2-8.11" *)
  \$_DFFSR_PPP_  q_reg /* _2_ */ (
    .C(clk),
    .D(d),
    .Q(q),
    .R(clr),
    .S(_0_)
  );
endmodule
