/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:13.1-26.10" *)
(* top =  1  *)
module blocklocal_struct_width(clk_i, wdata_i, asid_o);
  (* src = "dut.sv:14.25-14.30" *)
  input clk_i;
  wire clk_i;
  (* src = "dut.sv:15.25-15.32" *)
  input [63:0] wdata_i;
  wire [63:0] wdata_i;
  (* src = "dut.sv:16.25-16.31" *)
  output [15:0] asid_o;
  wire [15:0] asid_o;
  (* src = "dut.sv:18.13-18.19" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43" *)
  (* wiretype = "\\p::satp_t" *)
  wire [63:0] satp_q;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43" *)
  wire [59:0] \upd.vsatp ;
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[44]  /* _00_ */ (
    .C(clk_i),
    .D(wdata_i[44]),
    .Q(satp_q[44])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[45]  /* _01_ */ (
    .C(clk_i),
    .D(wdata_i[45]),
    .Q(satp_q[45])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[46]  /* _02_ */ (
    .C(clk_i),
    .D(wdata_i[46]),
    .Q(satp_q[46])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[47]  /* _03_ */ (
    .C(clk_i),
    .D(wdata_i[47]),
    .Q(satp_q[47])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[48]  /* _04_ */ (
    .C(clk_i),
    .D(wdata_i[48]),
    .Q(satp_q[48])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[49]  /* _05_ */ (
    .C(clk_i),
    .D(wdata_i[49]),
    .Q(satp_q[49])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[50]  /* _06_ */ (
    .C(clk_i),
    .D(wdata_i[50]),
    .Q(satp_q[50])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[51]  /* _07_ */ (
    .C(clk_i),
    .D(wdata_i[51]),
    .Q(satp_q[51])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[52]  /* _08_ */ (
    .C(clk_i),
    .D(wdata_i[52]),
    .Q(satp_q[52])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[53]  /* _09_ */ (
    .C(clk_i),
    .D(wdata_i[53]),
    .Q(satp_q[53])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[54]  /* _10_ */ (
    .C(clk_i),
    .D(wdata_i[54]),
    .Q(satp_q[54])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[55]  /* _11_ */ (
    .C(clk_i),
    .D(wdata_i[55]),
    .Q(satp_q[55])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[56]  /* _12_ */ (
    .C(clk_i),
    .D(wdata_i[56]),
    .Q(satp_q[56])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[57]  /* _13_ */ (
    .C(clk_i),
    .D(wdata_i[57]),
    .Q(satp_q[57])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[58]  /* _14_ */ (
    .C(clk_i),
    .D(wdata_i[58]),
    .Q(satp_q[58])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:25.3-25.60" *)
  \$_DFF_P_  \satp_q_reg[59]  /* _15_ */ (
    .C(clk_i),
    .D(wdata_i[59]),
    .Q(satp_q[59])
  );
  assign \upd.vsatp  = { satp_q[59:52], 8'h00, satp_q[43:0] };
  assign satp_q[63:60] = 4'hx;
  assign asid_o = satp_q[59:44];
endmodule
