/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* top =  1  *)
(* src = "dut.sv:1.1-15.10" *)
module top(clk, out);
  (* src = "dut.sv:1.24-1.27" *)
  input clk;
  wire clk;
  (* src = "dut.sv:1.47-1.50" *)
  output [3:0] out;
  wire [3:0] out;
  assign out = 4'b1xxx;
endmodule
