/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* dynports =  1  *)
(* src = "dut.sv:1.1-39.10" *)
(* top =  1  *)
module lut_map_cmp(a, o1_1, o1_2, o1_3, o1_4, o1_5, o1_6, o2_1, o2_2, o2_3, o2_4, o2_5, o2_6, o3_1, o3_2, o3_3, o3_4, o3_5, o3_6, o4_1, o4_2
, o4_3, o4_4);
  (* src = "dut.sv:2.14-2.15" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "dut.sv:3.9-3.13" *)
  output o1_1;
  wire o1_1;
  (* src = "dut.sv:3.15-3.19" *)
  output o1_2;
  wire o1_2;
  (* src = "dut.sv:3.21-3.25" *)
  output o1_3;
  wire o1_3;
  (* src = "dut.sv:3.27-3.31" *)
  output o1_4;
  wire o1_4;
  (* src = "dut.sv:3.33-3.37" *)
  output o1_5;
  wire o1_5;
  (* src = "dut.sv:3.39-3.43" *)
  output o1_6;
  wire o1_6;
  (* src = "dut.sv:4.9-4.13" *)
  output o2_1;
  wire o2_1;
  (* src = "dut.sv:4.15-4.19" *)
  output o2_2;
  wire o2_2;
  (* src = "dut.sv:4.21-4.25" *)
  output o2_3;
  wire o2_3;
  (* src = "dut.sv:4.27-4.31" *)
  output o2_4;
  wire o2_4;
  (* src = "dut.sv:4.33-4.37" *)
  output o2_5;
  wire o2_5;
  (* src = "dut.sv:4.39-4.43" *)
  output o2_6;
  wire o2_6;
  (* src = "dut.sv:5.9-5.13" *)
  output o3_1;
  wire o3_1;
  (* src = "dut.sv:5.15-5.19" *)
  output o3_2;
  wire o3_2;
  (* src = "dut.sv:5.21-5.25" *)
  output o3_3;
  wire o3_3;
  (* src = "dut.sv:5.27-5.31" *)
  output o3_4;
  wire o3_4;
  (* src = "dut.sv:5.33-5.37" *)
  output o3_5;
  wire o3_5;
  (* src = "dut.sv:5.39-5.43" *)
  output o3_6;
  wire o3_6;
  (* src = "dut.sv:6.9-6.13" *)
  output o4_1;
  wire o4_1;
  (* src = "dut.sv:6.15-6.19" *)
  output o4_2;
  wire o4_2;
  (* src = "dut.sv:6.21-6.25" *)
  output o4_3;
  wire o4_3;
  (* src = "dut.sv:6.27-6.31" *)
  output o4_4;
  wire o4_4;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  \$_NOR_  _07_ (
    .A(a[3]),
    .B(a[1]),
    .Y(_00_)
  );
  \$_AND_  _08_ (
    .A(a[2]),
    .B(a[1]),
    .Y(_01_)
  );
  \$_NOR_  _09_ (
    .A(a[3]),
    .B(_01_),
    .Y(o3_3)
  );
  \$_NOT_  _10_ (
    .A(o3_3),
    .Y(o3_2)
  );
  \$_AND_  _11_ (
    .A(a[0]),
    .B(a[2]),
    .Y(_02_)
  );
  \$_NAND_  _12_ (
    .A(a[0]),
    .B(a[2]),
    .Y(_03_)
  );
  \$_NAND_  _13_ (
    .A(_00_),
    .B(_02_),
    .Y(o3_6)
  );
  \$_NOT_  _14_ (
    .A(o3_6),
    .Y(o3_5)
  );
  \$_AND_  _15_ (
    .A(o3_3),
    .B(_03_),
    .Y(o3_4)
  );
  \$_NAND_  _16_ (
    .A(o3_3),
    .B(_03_),
    .Y(o3_1)
  );
  \$_OR_  _17_ (
    .A(a[2]),
    .B(a[1]),
    .Y(_04_)
  );
  \$_AND_  _18_ (
    .A(a[3]),
    .B(a[1]),
    .Y(_05_)
  );
  \$_AND_  _19_ (
    .A(a[3]),
    .B(_04_),
    .Y(o1_1)
  );
  \$_NOT_  _20_ (
    .A(o1_1),
    .Y(o1_4)
  );
  \$_NOR_  _21_ (
    .A(a[0]),
    .B(a[2]),
    .Y(_06_)
  );
  \$_NAND_  _22_ (
    .A(_05_),
    .B(_06_),
    .Y(o1_6)
  );
  \$_NOT_  _23_ (
    .A(o1_6),
    .Y(o1_5)
  );
  \$_ANDNOT_  _24_ (
    .A(o1_1),
    .B(_06_),
    .Y(o1_2)
  );
  \$_ORNOT_  _25_ (
    .A(_06_),
    .B(o1_1),
    .Y(o1_3)
  );
  \$_NAND_  _26_ (
    .A(_00_),
    .B(_06_),
    .Y(o4_4)
  );
  \$_NOT_  _27_ (
    .A(o4_4),
    .Y(o4_1)
  );
  assign o4_3 = 1'h1;
  assign o4_2 = 1'h0;
  assign o2_6 = o1_6;
  assign o2_5 = o1_5;
  assign o2_4 = o1_2;
  assign o2_3 = o1_1;
  assign o2_2 = o1_4;
  assign o2_1 = o1_3;
endmodule
