/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:16.1-28.10" *)
(* top =  1  *)
module top(o1, o2);
  (* src = "dut.sv:16.29-16.31" *)
  output signed [31:0] o1;
  wire signed [31:0] o1;
  (* src = "dut.sv:16.44-16.46" *)
  output signed [31:0] o2;
  wire signed [31:0] o2;
  (* src = "dut.sv:19.27-19.53" *)
  wire [63:0] \o.b.j ;
  (* src = "dut.sv:20.17-20.34" *)
  wire [31:0] uct_obj;
  assign uct_obj = 32'd9999;
  assign \o.b.j  = 64'h00000000000008ae;
  assign o2 = 32'hxxxxxxxx;
  assign o1 = 32'd2222;
endmodule
