/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:3.1-9.10" *)
(* top =  1  *)
module gate(a);
  (* src = "dut.sv:3.13-3.14" *)
  output [32:0] a;
  wire [32:0] a;
  wire \genblk1[0].x ;
  wire [1:0] \genblk1[1].x ;
  assign \genblk1[1].x  = 2'h3;
  assign \genblk1[0].x  = 1'h1;
  assign a = 33'h000000016;
endmodule
