/* Generated by Yosys 0.62+39 (git sha1 131911291-dirty, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* hdlname = "cnt" *)
(* src = "dut.sv:6.1-22.10" *)
module \$paramod\cnt\initval=s32'00000000000000000000000000000001 (clock, cnt, delta);
  (* src = "dut.sv:9.8-9.13" *)
  input clock;
  wire clock;
  (* init = 4'h1 *)
  (* src = "dut.sv:10.21-10.24" *)
  output [3:0] cnt;
  wire [3:0] cnt;
  (* defaultvalue = 32'd10 *)
  (* src = "dut.sv:14.14-14.19" *)
  input [3:0] delta;
  wire [3:0] delta;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:21.10-21.21|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:287.21-287.22" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _10_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:21.10-21.21|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _11_;
  \$_XNOR_  _12_ (
    .A(cnt[3]),
    .B(delta[3]),
    .Y(_00_)
  );
  \$_NAND_  _13_ (
    .A(cnt[2]),
    .B(delta[2]),
    .Y(_01_)
  );
  \$_XNOR_  _14_ (
    .A(cnt[2]),
    .B(delta[2]),
    .Y(_02_)
  );
  \$_NAND_  _15_ (
    .A(cnt[1]),
    .B(delta[1]),
    .Y(_03_)
  );
  \$_XOR_  _16_ (
    .A(cnt[1]),
    .B(delta[1]),
    .Y(_04_)
  );
  \$_AND_  _17_ (
    .A(cnt[0]),
    .B(delta[0]),
    .Y(_05_)
  );
  \$_AND_  _18_ (
    .A(_05_),
    .B(_04_),
    .Y(_06_)
  );
  \$_ANDNOT_  _19_ (
    .A(_03_),
    .B(_06_),
    .Y(_07_)
  );
  \$_NOR_  _20_ (
    .A(_07_),
    .B(_02_),
    .Y(_08_)
  );
  \$_ANDNOT_  _21_ (
    .A(_01_),
    .B(_08_),
    .Y(_09_)
  );
  \$_XOR_  _22_ (
    .A(_09_),
    .B(_00_),
    .Y(_11_[3])
  );
  \$_XOR_  _23_ (
    .A(_07_),
    .B(_02_),
    .Y(_11_[2])
  );
  \$_XOR_  _24_ (
    .A(_05_),
    .B(_04_),
    .Y(_11_[1])
  );
  \$_XOR_  _25_ (
    .A(cnt[0]),
    .B(delta[0]),
    .Y(_10_[0])
  );
  (* src = "dut.sv:20.2-21.22" *)
  \$_DFF_P_  \cnt_reg[0]  /* _26_ */ (
    .C(clock),
    .D(_10_[0]),
    .Q(cnt[0])
  );
  (* src = "dut.sv:20.2-21.22" *)
  \$_DFF_P_  \cnt_reg[1]  /* _27_ */ (
    .C(clock),
    .D(_11_[1]),
    .Q(cnt[1])
  );
  (* src = "dut.sv:20.2-21.22" *)
  \$_DFF_P_  \cnt_reg[2]  /* _28_ */ (
    .C(clock),
    .D(_11_[2]),
    .Q(cnt[2])
  );
  (* src = "dut.sv:20.2-21.22" *)
  \$_DFF_P_  \cnt_reg[3]  /* _29_ */ (
    .C(clock),
    .D(_11_[3]),
    .Q(cnt[3])
  );
  assign _11_[0] = _10_[0];
endmodule

(* hdlname = "cnt" *)
(* src = "dut.sv:6.1-22.10" *)
module \$paramod\cnt\initval=s32'00000000000000000000000000000010 (clock, cnt, delta);
  (* src = "dut.sv:9.8-9.13" *)
  input clock;
  wire clock;
  (* init = 4'h2 *)
  (* src = "dut.sv:10.21-10.24" *)
  output [3:0] cnt;
  wire [3:0] cnt;
  (* defaultvalue = 32'd10 *)
  (* src = "dut.sv:14.14-14.19" *)
  input [3:0] delta;
  wire [3:0] delta;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:21.10-21.21|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:287.21-287.22" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _10_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:21.10-21.21|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _11_;
  \$_XNOR_  _12_ (
    .A(cnt[3]),
    .B(delta[3]),
    .Y(_00_)
  );
  \$_NAND_  _13_ (
    .A(cnt[2]),
    .B(delta[2]),
    .Y(_01_)
  );
  \$_XNOR_  _14_ (
    .A(cnt[2]),
    .B(delta[2]),
    .Y(_02_)
  );
  \$_NAND_  _15_ (
    .A(cnt[1]),
    .B(delta[1]),
    .Y(_03_)
  );
  \$_XOR_  _16_ (
    .A(cnt[1]),
    .B(delta[1]),
    .Y(_04_)
  );
  \$_AND_  _17_ (
    .A(cnt[0]),
    .B(delta[0]),
    .Y(_05_)
  );
  \$_AND_  _18_ (
    .A(_05_),
    .B(_04_),
    .Y(_06_)
  );
  \$_ANDNOT_  _19_ (
    .A(_03_),
    .B(_06_),
    .Y(_07_)
  );
  \$_NOR_  _20_ (
    .A(_07_),
    .B(_02_),
    .Y(_08_)
  );
  \$_ANDNOT_  _21_ (
    .A(_01_),
    .B(_08_),
    .Y(_09_)
  );
  \$_XOR_  _22_ (
    .A(_09_),
    .B(_00_),
    .Y(_11_[3])
  );
  \$_XOR_  _23_ (
    .A(_07_),
    .B(_02_),
    .Y(_11_[2])
  );
  \$_XOR_  _24_ (
    .A(_05_),
    .B(_04_),
    .Y(_11_[1])
  );
  \$_XOR_  _25_ (
    .A(cnt[0]),
    .B(delta[0]),
    .Y(_10_[0])
  );
  (* src = "dut.sv:20.2-21.22" *)
  \$_DFF_P_  \cnt_reg[0]  /* _26_ */ (
    .C(clock),
    .D(_10_[0]),
    .Q(cnt[0])
  );
  (* src = "dut.sv:20.2-21.22" *)
  \$_DFF_P_  \cnt_reg[1]  /* _27_ */ (
    .C(clock),
    .D(_11_[1]),
    .Q(cnt[1])
  );
  (* src = "dut.sv:20.2-21.22" *)
  \$_DFF_P_  \cnt_reg[2]  /* _28_ */ (
    .C(clock),
    .D(_11_[2]),
    .Q(cnt[2])
  );
  (* src = "dut.sv:20.2-21.22" *)
  \$_DFF_P_  \cnt_reg[3]  /* _29_ */ (
    .C(clock),
    .D(_11_[3]),
    .Q(cnt[3])
  );
  assign _11_[0] = _10_[0];
endmodule

(* top =  1  *)
(* src = "dut.sv:1.1-4.10" *)
module defvalue_top(clock, delta, cnt1, cnt2);
  (* src = "dut.sv:1.27-1.32" *)
  input clock;
  wire clock;
  (* src = "dut.sv:1.46-1.51" *)
  input [3:0] delta;
  wire [3:0] delta;
  (* src = "dut.sv:1.66-1.70" *)
  output [3:0] cnt1;
  wire [3:0] cnt1;
  (* src = "dut.sv:1.72-1.76" *)
  output [3:0] cnt2;
  wire [3:0] cnt2;
  (* src = "dut.sv:3.11-3.35" *)
  \$paramod\cnt\initval=s32'00000000000000000000000000000010  bar (
    .clock(clock),
    .cnt(cnt2),
    .delta(4'ha)
  );
  (* src = "dut.sv:2.11-2.43" *)
  \$paramod\cnt\initval=s32'00000000000000000000000000000001  foo (
    .clock(clock),
    .cnt(cnt1),
    .delta(delta)
  );
endmodule
