/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* dynports =  1  *)
(* src = "dut.sv:25.3-25.42" *)
(* hdlname = "reader" *)
module \$paramod\reader\ID=s32'00000000000000000000000000000000 (w, \s.data );
  (* src = "dut.sv:18.73-18.74" *)
  output [31:0] w;
  wire [31:0] w;
  (* src = "dut.sv:14.23-14.27" *)
  input [15:0] \s.data ;
  wire [15:0] \s.data ;
  assign w = 32'd8;
endmodule

(* src = "dut.sv:22.1-26.10" *)
(* top =  1  *)
module top(w);
  (* src = "dut.sv:22.33-22.34" *)
  output [31:0] w;
  wire [31:0] w;
  (* src = "dut.sv:14.23-14.27" *)
  wire [15:0] \arr[0].data ;
  \$paramod\reader\ID=s32'00000000000000000000000000000000  u (
    .\s.data (16'hxxxx),
    .w(w)
  );
  assign \arr[0].data  = 16'hxxxx;
endmodule
