/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:6.1-26.10" *)
(* top =  1  *)
module struct_pat_fill(sel, out);
  (* src = "dut.sv:7.24-7.27" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "dut.sv:8.24-8.27" *)
  output [2:0] out;
  wire [2:0] out;
  (* src = "dut.sv:23.11-23.12" *)
  (* wiretype = "\\dec_t" *)
  wire [8:0] d;
  \$_NOT_  _0_ (
    .A(sel[0]),
    .Y(out[2])
  );
  \$_ANDNOT_  _1_ (
    .A(sel[0]),
    .B(sel[1]),
    .Y(out[0])
  );
  \$_XOR_  _2_ (
    .A(sel[1]),
    .B(sel[0]),
    .Y(out[1])
  );
  assign d = { 6'h00, out };
endmodule
