/* Generated by Yosys 0.55+46 (git sha1 aa1daa702, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* top =  1  *)
(* src = "dut.sv:1.1-10.10" *)
module adffn(d, clk, clr, q);
  (* src = "dut.sv:1.24-1.27" *)
  input clk;
  wire clk;
  (* src = "dut.sv:1.29-1.32" *)
  input clr;
  wire clr;
  (* src = "dut.sv:1.21-1.22" *)
  input d;
  wire d;
  (* init = 1'h0 *)
  (* src = "dut.sv:1.45-1.46" *)
  output q;
  wire q;
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:5.4-9.16" *)
  \$_SDFF_PN0_  q_reg /* _0_ */ (
    .C(clk),
    .D(d),
    .Q(q),
    .R(clr)
  );
endmodule
