/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* src = "dut.sv:1.1-12.10" *)
(* top =  1  *)
module top(a);
  (* src = "dut.sv:1.23-1.24" *)
  output signed [31:0] a;
  wire signed [31:0] a;
  assign a = 32'hxxxxxxxx;
endmodule
