/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:10.1-28.10" *)
(* top =  1  *)
module top(a, o);
  (* src = "dut.sv:10.12-10.13" *)
  input a;
  wire a;
  (* src = "dut.sv:10.15-10.16" *)
  output o;
  wire o;
  (* src = "dut.sv:18.7-18.10" *)
  wire bar;
  (* src = "dut.sv:19.7-19.10" *)
  wire baz;
  assign baz = 1'h0;
  assign bar = 1'h0;
  assign o = a;
endmodule
