/* Generated by Yosys 0.62+39 (git sha1 131911291-dirty, g++ 11.4.0-1ubuntu1~22.04.2 -Og -fPIC) */

(* dynports =  1  *)
(* src = "dut.sv:1.1-42.10" *)
(* top =  1  *)
module power_state(clock, reset, state, gnt_0, gnt_1);
  (* src = "dut.sv:2.9-2.14" *)
  input clock;
  wire clock;
  (* src = "dut.sv:3.9-3.14" *)
  input reset;
  wire reset;
  (* src = "dut.sv:4.15-4.20" *)
  input [2:0] state;
  wire [2:0] state;
  (* src = "dut.sv:5.14-5.19" *)
  output gnt_0;
  wire gnt_0;
  (* src = "dut.sv:6.14-6.19" *)
  output gnt_1;
  wire gnt_1;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  \$_ANDNOT_  _4_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_0_)
  );
  \$_ANDNOT_  _5_ (
    .A(_0_),
    .B(state[2]),
    .Y(_2_)
  );
  \$_OR_  _6_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_1_)
  );
  \$_ANDNOT_  _7_ (
    .A(state[2]),
    .B(_1_),
    .Y(_3_)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:14.3-40.6" *)
  \$_SDFF_PP0_  gnt_0_reg /* _8_ */ (
    .C(clock),
    .D(_2_),
    .Q(gnt_0),
    .R(reset)
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:14.3-40.6" *)
  \$_SDFF_PP0_  gnt_1_reg /* _9_ */ (
    .C(clock),
    .D(_3_),
    .Q(gnt_1),
    .R(reset)
  );
endmodule
