/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* src = "dut.sv:15.1-19.10" *)
(* top =  1  *)
module iface_nested_param_field(d, o);
  (* src = "dut.sv:15.52-15.53" *)
  input [2:0] d;
  wire [2:0] d;
  (* src = "dut.sv:15.74-15.75" *)
  output [2:0] o;
  wire [2:0] o;
  (* src = "dut.sv:9.27-9.34" *)
  wire [2:0] \s.dly_reg ;
  mem u (
    .o(o),
    .\sub.dly_reg (d)
  );
  assign \s.dly_reg  = d;
endmodule

(* src = "dut.sv:12.1-14.10" *)
module mem(o, \sub.dly_reg );
  (* src = "dut.sv:12.45-12.46" *)
  output [2:0] o;
  wire [2:0] o;
  (* src = "dut.sv:9.27-9.34" *)
  input [2:0] \sub.dly_reg ;
  wire [2:0] \sub.dly_reg ;
  assign o = \sub.dly_reg ;
endmodule
