/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* src = "dut.sv:6.1-124.10" *)
(* top =  1  *)
module d(cos_z0, sin_z0, done, z0, start, clock, reset);
  (* src = "dut.sv:7.5-7.11" *)
  output signed [19:0] cos_z0;
  wire signed [19:0] cos_z0;
  (* src = "dut.sv:8.5-8.11" *)
  output signed [19:0] sin_z0;
  wire signed [19:0] sin_z0;
  (* src = "dut.sv:9.5-9.9" *)
  output done;
  wire done;
  (* src = "dut.sv:10.5-10.7" *)
  input signed [19:0] z0;
  wire signed [19:0] z0;
  (* src = "dut.sv:11.5-11.10" *)
  input start;
  wire start;
  (* src = "dut.sv:12.5-12.10" *)
  input clock;
  wire clock;
  (* src = "dut.sv:13.5-13.10" *)
  input reset;
  wire reset;
  (* src = "dut.sv:45.1-122.4" *)
  wire [4:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* force_downto = 32'd1 *)
  (* src = "dut.sv:76.13-119.16|dut.sv:65.9-120.16|/home/alain/uhdm2rtlil/out/current/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [0:0] _18_;
  (* src = "dut.sv:49.25-49.27" *)
  wire signed [19:0] dx;
  (* src = "dut.sv:50.25-50.27" *)
  wire signed [19:0] dy;
  (* src = "dut.sv:46.17-46.18" *)
  wire [4:0] i;
  (* src = "dut.sv:47.17-47.22" *)
  wire state;
  (* src = "dut.sv:52.25-52.26" *)
  wire signed [19:0] x;
  (* src = "dut.sv:51.25-51.26" *)
  wire signed [19:0] y;
  \$_ANDNOT_  _19_ (
    .A(state),
    .B(i[0]),
    .Y(_00_[0])
  );
  \$_ANDNOT_  _20_ (
    .A(i[1]),
    .B(i[2]),
    .Y(_04_)
  );
  \$_ANDNOT_  _21_ (
    .A(i[4]),
    .B(i[3]),
    .Y(_05_)
  );
  \$_AND_  _22_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  \$_NAND_  _23_ (
    .A(_00_[0]),
    .B(_06_),
    .Y(_07_)
  );
  \$_NOT_  _24_ (
    .A(_07_),
    .Y(_01_)
  );
  \$_OR_  _25_ (
    .A(state),
    .B(start),
    .Y(_08_)
  );
  \$_AND_  _26_ (
    .A(_07_),
    .B(_08_),
    .Y(_18_)
  );
  \$_AND_  _27_ (
    .A(i[1]),
    .B(i[0]),
    .Y(_09_)
  );
  \$_AND_  _28_ (
    .A(i[2]),
    .B(_09_),
    .Y(_10_)
  );
  \$_NAND_  _29_ (
    .A(i[3]),
    .B(_10_),
    .Y(_11_)
  );
  \$_XOR_  _30_ (
    .A(i[3]),
    .B(_10_),
    .Y(_12_)
  );
  \$_AND_  _31_ (
    .A(state),
    .B(_12_),
    .Y(_00_[3])
  );
  \$_OR_  _32_ (
    .A(i[2]),
    .B(_09_),
    .Y(_13_)
  );
  \$_AND_  _33_ (
    .A(state),
    .B(_13_),
    .Y(_14_)
  );
  \$_ANDNOT_  _34_ (
    .A(_14_),
    .B(_10_),
    .Y(_00_[2])
  );
  \$_OR_  _35_ (
    .A(i[1]),
    .B(i[0]),
    .Y(_15_)
  );
  \$_AND_  _36_ (
    .A(state),
    .B(_15_),
    .Y(_16_)
  );
  \$_ANDNOT_  _37_ (
    .A(_16_),
    .B(_09_),
    .Y(_00_[1])
  );
  \$_ANDNOT_  _38_ (
    .A(start),
    .B(state),
    .Y(_03_)
  );
  \$_OR_  _39_ (
    .A(_01_),
    .B(_03_),
    .Y(_02_)
  );
  \$_XNOR_  _40_ (
    .A(i[4]),
    .B(_11_),
    .Y(_17_)
  );
  \$_AND_  _41_ (
    .A(state),
    .B(_17_),
    .Y(_00_[4])
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:45.1-122.4" *)
  \$_DFFE_PP1P_  \cos_z0_reg[0]  /* _42_ */ (
    .C(clock),
    .D(1'h0),
    .E(_01_),
    .Q(cos_z0[0]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:45.1-122.4" *)
  \$_DFFE_PP0P_  \cos_z0_reg[14]  /* _43_ */ (
    .C(clock),
    .D(x[14]),
    .E(_01_),
    .Q(cos_z0[14]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:45.1-122.4" *)
  \$_DFFE_PP0P_  \x_reg[14]  /* _44_ */ (
    .C(clock),
    .D(1'h1),
    .E(_03_),
    .Q(x[14]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:45.1-122.4" *)
  \$_DFFE_PP0P_  done_reg /* _45_ */ (
    .C(clock),
    .D(state),
    .E(_02_),
    .Q(done),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:45.1-122.4" *)
  \$_DFFE_PP0P_  \i_reg[0]  /* _46_ */ (
    .C(clock),
    .D(_00_[0]),
    .E(_18_),
    .Q(i[0]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:45.1-122.4" *)
  \$_DFFE_PP0P_  \i_reg[1]  /* _47_ */ (
    .C(clock),
    .D(_00_[1]),
    .E(_18_),
    .Q(i[1]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:45.1-122.4" *)
  \$_DFFE_PP0P_  \i_reg[2]  /* _48_ */ (
    .C(clock),
    .D(_00_[2]),
    .E(_18_),
    .Q(i[2]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:45.1-122.4" *)
  \$_DFFE_PP0P_  \i_reg[3]  /* _49_ */ (
    .C(clock),
    .D(_00_[3]),
    .E(_18_),
    .Q(i[3]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:45.1-122.4" *)
  \$_DFFE_PP0P_  \i_reg[4]  /* _50_ */ (
    .C(clock),
    .D(_00_[4]),
    .E(_18_),
    .Q(i[4]),
    .R(reset)
  );
  (* \"has_async_reset"  = 32'd1 *)
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:45.1-122.4" *)
  \$_DFF_PP0_  state_reg /* _51_ */ (
    .C(clock),
    .D(_18_),
    .Q(state),
    .R(reset)
  );
  assign { x[19:15], x[13:0] } = { 2'h0, x[14], 2'h0, x[14], 1'h0, x[14], x[14], 1'h0, x[14], x[14], x[14], 1'h0, x[14], 1'h0, x[14], 2'h0 };
  assign y = 20'h00000;
  assign dy = 20'h00000;
  assign dx = 20'h00000;
  assign sin_z0 = 20'h00000;
  assign { cos_z0[19:15], cos_z0[13:1] } = { 2'h0, cos_z0[14], 2'h0, cos_z0[14], 1'h0, cos_z0[14], cos_z0[14], 1'h0, cos_z0[14], cos_z0[14], cos_z0[14], 1'h0, cos_z0[14], 1'h0, cos_z0[14], 1'h0 };
endmodule
