/* Generated by Yosys 0.68+1 (git sha1 bbc149ed5, Release, GNU /usr/bin/g++ 11.4.0) [github.com/alainmarcel/yosys at HEAD] */

(* dynports =  1  *)
(* src = "dut.sv:6.1-32.10" *)
(* top =  1  *)
module nested_gen_ff(clk_i, rst_ni, en_i, d_i, q_o);
  (* src = "dut.sv:10.23-10.28" *)
  input clk_i;
  wire clk_i;
  (* src = "dut.sv:11.23-11.29" *)
  input rst_ni;
  wire rst_ni;
  (* src = "dut.sv:12.23-12.27" *)
  input en_i;
  wire en_i;
  (* src = "dut.sv:13.23-13.26" *)
  input [7:0] d_i;
  wire [7:0] d_i;
  (* src = "dut.sv:14.23-14.26" *)
  output [7:0] q_o;
  wire [7:0] q_o;
  wire [7:0] \g_stage.q_q ;
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:24.7-26.10" *)
  \$_DFFE_PP_  \g_stage.q_q_reg[0]  /* _0_ */ (
    .C(clk_i),
    .D(d_i[0]),
    .E(en_i),
    .Q(\g_stage.q_q [0])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:24.7-26.10" *)
  \$_DFFE_PP_  \g_stage.q_q_reg[1]  /* _1_ */ (
    .C(clk_i),
    .D(d_i[1]),
    .E(en_i),
    .Q(\g_stage.q_q [1])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:24.7-26.10" *)
  \$_DFFE_PP_  \g_stage.q_q_reg[2]  /* _2_ */ (
    .C(clk_i),
    .D(d_i[2]),
    .E(en_i),
    .Q(\g_stage.q_q [2])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:24.7-26.10" *)
  \$_DFFE_PP_  \g_stage.q_q_reg[3]  /* _3_ */ (
    .C(clk_i),
    .D(d_i[3]),
    .E(en_i),
    .Q(\g_stage.q_q [3])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:24.7-26.10" *)
  \$_DFFE_PP_  \g_stage.q_q_reg[4]  /* _4_ */ (
    .C(clk_i),
    .D(d_i[4]),
    .E(en_i),
    .Q(\g_stage.q_q [4])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:24.7-26.10" *)
  \$_DFFE_PP_  \g_stage.q_q_reg[5]  /* _5_ */ (
    .C(clk_i),
    .D(d_i[5]),
    .E(en_i),
    .Q(\g_stage.q_q [5])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:24.7-26.10" *)
  \$_DFFE_PP_  \g_stage.q_q_reg[6]  /* _6_ */ (
    .C(clk_i),
    .D(d_i[6]),
    .E(en_i),
    .Q(\g_stage.q_q [6])
  );
  (* \always_ff  = 32'd1 *)
  (* src = "dut.sv:24.7-26.10" *)
  \$_DFFE_PP_  \g_stage.q_q_reg[7]  /* _7_ */ (
    .C(clk_i),
    .D(d_i[7]),
    .E(en_i),
    .Q(\g_stage.q_q [7])
  );
  assign q_o = \g_stage.q_q ;
endmodule
