/* Generated by Yosys 0.64+1 (git sha1 d8e0655ed-dirty, g++ 11.4.0-1ubuntu1~22.04.3 -Og -fPIC) [alainmarcel/yosys at v0.64-write-verilog-signed-port] */

(* top =  1  *)
(* src = "dut.sv:1.1-10.10" *)
module top(o);
  (* src = "dut.sv:1.31-1.32" *)
  output [3:0] o;
  wire [3:0] o;
  (* src = "dut.sv:4.6-4.8" *)
  wire [3:0] un;
  assign un = 4'ha;
  assign o = 4'ha;
endmodule
